### ISSUE TITLE
All tabs need to be rewritten for bootstrap 5

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#101]
I will work on it.

**Comment by joomlahenk** [comment]
Which tabs do you mean?

**Comment by skurvish** [comment]
The tabs that are currently being created on the admin side, for a new list for example, are using old style BS3 classes. We should be using the HTMLHelper way to build the tabs so that they are bootstrap agnostic. It is not a big deal, just a little rework.

I image this will also be the case for front end layouts as well but I have not looked yet.

**Comment by skurvish** [comment]
I have the list view all done, it is actually a lot simpler. However, I have a problem with the bootstrap tabs css on the admin side. When you have a vertical tabset and the data for a tab is itself a tabset but a horizontal one, the horizontal tabset is inheriting the vertical css for the tabs. The exact same code on the front end does not exhibit this behaviour.

I need to play with it some more and may have to open a ticket with the J! developers.

**Comment by joomlahenk** [comment]
OK, I thought they were fine. I just copied from J! (com_config, com_content).

**Comment by skurvish** [comment]
I am abandoning this effort. The JHTMLHelper uiTabSet and uiTab systems are not robust enough to use for Fabrik. The nesting of Vertical and Horizontal tabs just does not work and I got no help from the J! developers. I may need to update a class here or there but they basically work as is so I am going to leave them alone. On to something else (after probably 20 hours trying to make this work).
