### ISSUE TITLE
Admin element Group dropdown

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#103]
Doesn't show form/groups hierarchy (ordered by form name)  but only all groups alphabetically.
I think this was working at some point.

**Comment by joomlahenk** [comment]
I could only add 'Please select'. Maybe Alex can add form/groups hierarchy?

**Comment by skurvish** [comment]
I know what is wrong and I know how to fix it, but having just updated my local repo from this one my view elements in the admin is all messed up. Maybe someone can look at the recent merges and figure out why it broke.

**Comment by skurvish** [comment]
Well, after leaving it for an hour coming back it is now all working..grrr...I suspect it was some sort of caching issue. I will get the groups fixed and PR'ed.

**Comment by skurvish** [comment]
Fixed with PR #106
