### ISSUE TITLE
Adminform element: adding Javascript will break Save.

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#105]
It's possible to add one JS and the JS is working (tested with a built-in hide).
But the element can only be saved once (directly after adding this JS). 
An element with JS can't be edited again, it won't save (Console showing "Cannot read properties of undefined (reading 'canSaveForm'"). 
You have to delete the JS in #__fabrik_jsactions to get the element back for editing.

**Comment by skurvish** [comment]
I just tried this on an element and am able to save multiple js actions. I can close the element and reopen it without issue. This is a generic field element.

Can you try again and see if the problem is still happening? If so please provide detailed instructions on how to recreate it.Thanks.

**Comment by trob** [comment]
It's ok meanwhile (because of whatever)
