### ISSUE TITLE
Minifying JS files

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#108]
What is a good tool to do it?

List of modified files:

media/com_fabrik/js/list.js
media/com_fabrik/js/window.js

**Comment by joomlahenk** [comment]
Maybe https://www.minifier.org/

**Comment by skurvish** [comment]
The build process has an option to do this. I will update the wiki. In the mean time I will run the minify and check in the minified files.

**Comment by skurvish** [comment]
Fixed with PR #111
