### ISSUE TITLE
Trying to install fabrik4 in J!4

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#109]
Created an install package as I did before, but now with latest files from GH.
It used to install without any issue, but now I get PLG_FABRIK_SYSTEM_AUTOLOAD_MISSING and the system is locked.

**Comment by trob** [comment]
Disable Fabrik system plugin in the DB (#__extensions)
Try to zip the Fabrik system plugin and install it again, maybe something is missing in the install package.

BTW: Where are you living? Your 1st merge today was Sunday morning 8 UTC ;)

**Comment by skurvish** [comment]
Why not build it using the build process? I created a wiki entry on this.

p.s. FYI, I live In Fort Erie Canada which is part of Niagara Falls Canada, directly across the border from Buffalo NY, and about 200 km from Toronto.

**Comment by joomlahenk** [comment]
Found the cause in the meantime: I tried to install with the Document folder in the site/fabrik/fabrik folder.
It seems that requires an autoload or an extra line in include.php. Thanks for your tips. Will try again.

b.t.w. I live in The Netherlands

**Comment by trob** [comment]
`b.t.w. I live in The Netherlands` So same timezone as Switzerland.

Build process: 
I didn't try and I don't completely understand: 
Is the build process taking the files from 
libraries/fabrik/fabrik and
libraries/src/Document (i.e. the files which are run)? 

Because I did only modify the files there, not in
components/com_fabrik/fabrik/fabrik/ and
components/com_fabrik/Documents

I think these files should be removed to avoid version mismatches etc.

**Comment by skurvish** [comment]
I agree, they should be removed from the build process. Just haven't gotten to it yet.

**Comment by joomlahenk** [comment]
That's what I am trying: remove those from components/com_fabrik/Documents and only have them in components/com_fabrik/Documents, but I can't get the include.php working yet. 
It should load all library files and it does for the Controllers and Helpers. 
I added a line spl_autoload_register(array($this, 'document')); in function __construct()
and added a new function:
	private function document($class)
	{
		if (!strstr(strtolower($class), 'document'))
		{
			return;
		}
		$class = str_replace('\\', '/', $class);
		//$file  = explode('/', $class);
		//$file  = strtolower(array_pop($file));
		$path = preg_replace('#Fabrik\/Document\/#', JPATH_SITE . '/libraries/fabrik/fabrik/Document/', $class);
		$path  = $path . '.php';

		if (file_exists($path))
		{
			require_once $path;
		}
	}

**Comment by trob** [comment]
`remove those from components/com_fabrik/Documents and only have them in components/com_fabrik/Documents`
Not sure what you mean.
The "library" files are in 
libraries/fabrik/fabrik
but the Document files are in
libraries/src/Document (i.e. in the end in the Joomla folder - Joomla doesn't like this at all and kicked Fabrik out of the extensions)

**Comment by joomlahenk** [comment]
Document files should be in the fabrik libraries. They were put in the Joomla folder, because then they would be autoloaded.
And in order to get them there they needed to be copied from component/com_fabrik.

**Comment by trob** [comment]
I think we are talking of two different things.

1. 
Why are these files at two locations in GitHub at all. 
After installation and if you are updating from GitHub etc. the relevant files are in libraries/fabrik/fabrik and (at the moment) in libraries/src/Document. Any modification via GitHub has to be done in these files. So I think the files in components/com_fabrik/fabrik and components/com_fabrik/Document should be removed and the package should be built from the files in libraries/fabrik/fabrik and libraries/src/Document (at the moment, "just make it work")
2.
How can the libraries/src/Document files be moved into libraries/fabrik? I don't know about autoload etc., I only know that Hugh didn't manage to do it.

**Comment by joomlahenk** [comment]
In J!3 and earlier library files were loaded by an include.php file and still can. This is how the Controller and Helper files are loaded.
It's strange that Document was never loaded in that way, what's the difference. In J!3 also all files in the Joomla libraries are autoloaded, so that's why they copied Document in the Joomla library. That was an easy hack. 
In J!4, however, all library files are autoloaded by using the namespace. We also need to specify that in the fabrik.xml install file.
I have to find out more info how this works exactly, but all extensions for J!4 work that way. So why should fabrik not work that way. I will try to find out anyway.

**Comment by skurvish** [comment]
I installed it on a fresh install of J4 but I installed the package from the build not the package that you built. Do you want a current package build to try?

**Comment by joomlahenk** [comment]
The error is caused by the plg_fabrik_system. It is testing if we have the /fabrik/include.php and we realy do and in exact the same place as ever before, but it cannot find it. Maybe JPATH_LIBRARIES has changed ?

		if (!file_exists(JPATH_LIBRARIES . '/fabrik/include.php'))
		{
			throw new Exception('PLG_FABRIK_SYSTEM_AUTOLOAD_MISSING');
		}

Pulling my hairs out.

**Comment by trob** [comment]
@skurvish: Can you put your recent built-package somewhere (in this GitHub or in yours)? I don't have this grunt stuff locally.
I built my package manually 3 days ago (copying administrator to admin etc, then zip with only the component and an extra zip of fabrik system plugin) and it is installing and running without problems (just tested again on a new J4 installation).

@joomlahenk : Did you use the Document in the old place (libraries/src) or did you try with Document inside libraries/fabrik?

**Comment by trob** [comment]
You can add
$x=JPATH_LIBRARIES . '/fabrik/include.php';
var_dump($x);exit;
before if(!file...) to see the path

**Comment by joomlahenk** [comment]
OK, I am stupid! I change the installer script not to move the Document files, but in the same time also did not move the fabrik library files. Fixed now. Thanks for thinking with me.
