### ISSUE TITLE
Update fabrik with proper J4 classes

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#11]
Work in progress. Had to restart this effort due to many other changes merged before my initial one was.

**Comment by joomlahenk** [comment]
OK, I think this is because I forgot to update the classes folder in GitHub. I removed all old FormField overrides and only left the most recent one.

So, I guess you used a very old FormField. This should be OK now.

 

Van: skurvish ***@***.***> 
Verzonden: Tuesday, 5 July 2022 18:11
Aan: joomlahenk/fabrik ***@***.***>
CC: joomlahenk ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [joomlahenk/fabrik] Update fabrik with proper J4 classes (Issue #11)

 

Made significant progress yesterday & today. Have run into an issue with creating new lists as the form object is missing the loadFile function. This function was in a J! override of the Form class under administrator/components/com_fabrik/classes and it looks like Henk has removed these overrides.

@joomlahenk <https://github.com/joomlahenk>  is there some reason you removed these?

**Comment by skurvish** [comment]
Found the problem with the loadFile. With the class changes a function called getJForm was changed to getForm but this function is called on $this which at that point is the element not the plugin. Changing the function and call back to getJForm and calling it with self solved the problem.

**Comment by skurvish** [comment]
PR resubmitted.

**Comment by skurvish** [comment]
Merged.

**Comment by joomlahenk** [comment]
I merged your classes update and after that I committed my updates for the fabrik fields.

On the github desktop now I have a merge conflict and it keeps spinning.

I am afraid something went very wrong here.

 

Van: skurvish ***@***.***> 
Verzonden: Thursday, 7 July 2022 19:25
Aan: joomlahenk/fabrik ***@***.***>
CC: joomlahenk ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [joomlahenk/fabrik] Update fabrik with proper J4 classes (Issue #11)

 

Closed #11 <https://github.com/joomlahenk/fabrik/issues/11>  as completed.

**Comment by skurvish** [comment]
I can't see your update so I cannot see what the merge conflicts are. can you print screen them for me?

**Comment by skurvish** [comment]
Hugh had done some slight of hand for some of the classnames. He namespaced some of the files and then to make sure PHP found the right classname prefixed some with the \ instead of inserting the proper use statements.

You may run across a few similar ones.

**Comment by skurvish** [comment]
The function exists in the form model. I will have to step through with phpStorm to figure out why it isn't being found.

Whet are you doing when this happens?

**Comment by trob** [comment]
One string replace to much
![grafik](https://user-images.githubusercontent.com/1045355/177886618-40afeb55-56d4-4820-bd08-24ab985cec8f.png)
It's working with
`	public function elementJsJLayouts()
	{
		$groups = $this->getGroupsHiarachy();

		foreach ($groups as $groupModel)
		{
			$elementModels = $groupModel->getPublishedElements();

			foreach ($elementModels as $elementModel)
			{
				$elementModel->jsLayoutInterfaces();
			}
		}
	}`

**Comment by trob** [comment]
I did a PR and merged it. 
BTW: merged PR can be reverted (I didn't try but there's a button)

**Comment by skurvish** [comment]
Aha? The replacement code was too smart. Glad you got it working.

**Comment by trob** [comment]
I found one more > issue in libraries\fabrik\fabrik\Helpers\Uploader.php
class Uploader extends \CMSObject must be
class Uploader extends CMSObject

Maybe you can run your search script...

**Comment by skurvish** [comment]
Fixed. It was the only file with this issue.

**Comment by joomlahenk** [comment]
I found some files that are missing use Joomla\CMS\Factory; (admin/controllers/connection,......)

**Comment by skurvish** [comment]
Will look at this today. Am mired down in the filter options at the moment.

**Comment by joomlahenk** [comment]
Found some more issues with this: class FormFieldHelpLink extends FormField must be: class JFormFieldHelpLink extends FormField and there a lot more like this.

**Comment by skurvish** [comment]
Submitted pr for the Factory. Yes, the substitution script I used did make some incorrect substitutions. Let me know as you find them and I will fix.

**Comment by skurvish** [comment]
There was only 1 instance of the JFormFieldHelpLink. I committed the change to the Factory PR.

If you find any others let me know, I wrote a small script to find all the cases once I know the class name.

**Comment by joomlahenk** [comment]
OK, I think we got al of these now. If any left then it does not harm as J! still support many of the old classes. But it's required for J!5
