### ISSUE TITLE
Which files does the build process include: libraries/... or component/com_fabrik/...

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#115]
I did my modifications only in the libraries/src/Document and  libraries/fabrik/fabrik files (the ones which are used for running Fabrik).

So they are NOT in component/com_fabrik/Document and component/com_fabrik/fabrik.

**Comment by skurvish** [comment]
Those are the correct locations. It seems that the Helper director in components/com_fabrik/fabrik/fabrik should not be there in the repo. If you look at the master branch it is not there. Somehow it creeped into the henk40 branch when the first commit was done. I think we should be removing this folder from the repo so I am going to creat a PR which does that. We can work out the copy/move issues seperately.
