### ISSUE TITLE
Test PDF in form and other.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#118]
I updated Documents to work in list only. I am not able to test in form and others. Maybe more needs to be updated to have all PDF work. If anyone can test please let me know.

**Comment by trob** [comment]
PDF doesn't work in list anymore on my site.
Does it on your site? and did you delete/rename all Fabrik files in scr/Document before testing?

**Comment by joomlahenk** [comment]
Is working on my site. We have no src/Document. All Document is now in libraries/fabrik.

**Comment by trob** [comment]
![grafik](https://user-images.githubusercontent.com/1045355/179842413-150cb528-f592-44ab-97fd-d5be3cdfeb23.png)
This is definitively not the recent one but the one which is run.

**Comment by joomlahenk** [comment]
OK, this should have been comitted. Guess I just forgot this one. Merged right now.

**Comment by trob** [comment]
Pdf: It doesn't run pdfDocument's render()

**Comment by joomlahenk** [comment]
Yes, it should. Searching in J!3, but I can't find where it's called from yet.

**Comment by joomlahenk** [comment]
That also what I found. $this->doc should be Fabrik\Document\PdfDocument, but it's Joomla\CMS\Document\RawDocument.
Indeed I tried to do a new PdfDocument instead and that only helps to prevent an error from setName.

**Comment by joomlahenk** [comment]
Well, I get a little further on this one: the function that sets the classname for the pdf is in src/Document/Factory.php. This is the same function as in J!3 scr/Document/Document.php. In J!4 this function is not changed, so it still uses the old classname convention. In this case we need to name our class JDocumentPdf. So to make it easy I added an alias in ../helpers/legacy/aliases.php. And voila our class PdfDocument is used now instead of DocumentRaw.

Now I have another issue and it gets more complicated... The render buffer seems not to get populated.

Anyway I needed to undo the changes I made in ../views/list/view.pdf.php. 
I will merge the updated view.pdf.php & aliases.php. This means PDF is not working yet and you will get the same error as I get. I am still working on it. Maybe you can take a look and have some suggestions?

**Comment by joomlahenk** [comment]
I have PDF working now. Needed to add some more alias. Document is now completely in fabrik/fabrik library and working.
This could have been done in Fabrik 3.10 also. See src/Document/Document
Joomla requires specific classnames for 'external' library classes. See src/Document/Factory

PDF should work for all list/form/detail/etc. now. Please test.

**Comment by trob** [comment]
Great :) 👍 
I will have a look at mPDF
