### ISSUE TITLE
Menu and tab items dissapear when they are clicked

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#121]
This is for all in the backend. This was working perfect before.

**Comment by skurvish** [comment]
Yes, I have a feeling this is related to the change I made for closing the popup modals. I will be investigating.

**Comment by skurvish** [comment]
I have my db all set to nulls but still see the problem.

**Comment by skurvish** [comment]
Yes, it is definitely the change to mootools-ext.js. I can fix it by adding a class to the tabs but I am not sure that is the best way to go about it. Let me look a little more.

**Comment by skurvish** [comment]
I have tweaked my previous change. Seems to be working pending any further issues popping up. PR #123

**Comment by joomlahenk** [comment]
Solved here. Just it doesn't come back like before.
