### ISSUE TITLE
jdate/date element: you can't have both enabled

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#128]
In F3 you can't use them in the same form, in F4 you can't even have them both enabled.

If trying to add an element it throws (already before the admin element form is opened) `Fatal error: Cannot use Joomla\CMS\Date\Date as Date because the name is already in use in ...plugins\fabrik_element\date\date.php on line 23` .

The same with timer element (which has a require_once date.php).

So:
Should date/timer be kept at all?
If yes, how to fix this?

**Comment by skurvish** [comment]
Have you updated your local repo lately? The date plugin had 2 use statements for Date, one has been removed recently.I have both plugins enabled on my test site.

**Comment by skurvish** [comment]
I am also considering where we want to drop the date plugin altogether and make using jdate a requirement of upgrading. Any thoughts?

**Comment by trob** [comment]
`we want to drop the date plugin altogether and make using jdate a requirement `
Hmm, for several reasons I don't like jdate very much: there are some bugs (e.g. advanced search) and restrictions (no "Allow date" possibilities). So if we can get rid of the error I would keep date (and so timer), maybe as "deprecated"

`The date plugin had 2 use statements for Date,` ah, yes, I fixed it now. But it has still the error message
Fatal error: Cannot declare class FabDate, because the name is already in use in ...plugins\fabrik_element\jdate\jdate.php on line 2828 as soon as both plugins are enabled.

**Comment by skurvish** [comment]
Something wrong on your end then as I have both plugins enabled. Might you have a form with both elements on it as that will not work.

**Comment by skurvish** [comment]
p.s. do you have skype or whatsapp available to you so we can chat directly and outside of the repo? My skypeid is live:achartier_5. I will have to look up my whatsapp id if that is what you have.

**Comment by joomlahenk** [comment]
Date has some more functions then jdate, but I don't know if they all work. For now enabling date end trying to add a new element causes a fatal error on my site (most recent GH update). Are we going to do al the effort to make it work or just skip it?

**Comment by joomlahenk** [comment]
@trob: "Cannot declare class FabDate, because the name is already in use" Maybe if you add a different namespace for both?

**Comment by trob** [comment]
Yes, I think i've tried this and it was working ( just tested again, it is working, I changed all FabDate to FaboldDate in date.php )

Did you try to have them both without modifications and then open a new ?

**Comment by joomlahenk** [comment]
I use the most recent GH and I have no issue now. I have both jdate and date as elements of the same list.

**Comment by skurvish** [comment]
Can we close this then?

**Comment by trob** [comment]
Yes. jdate and olddate won't do in the same form (and some display issues with old date) but you can use them both.
I'll open a new issue
