### ISSUE TITLE
Elements filter options - form

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#131]
Only the form filter:
A selection will filter correctly but won't enable the "Filter Options" Clear button and won't show the selection din the dropdown (you can click the Search icon to clear the filter, but only in this case - confusing).

BTW: is there a trick to keep the Filter Options open? I really would like to filter my elements and see the selected filters without having to open the Filter Options every time.

**Comment by skurvish** [comment]
I see, it seems the value in the form filter dropdown is being cleared for some reason and as a result the clear button is disabled. The other filters work fine.

No idea why the filter bar is being hidden once the filter is applied. Probably something simple.

**Comment by trob** [comment]
I see how it should look (it does so on J! pages e.g. articles):
If a filter is selected the  "Filters div" should have a class js-stools-container-filters-visible

**Comment by skurvish** [comment]
So there seems to be some problem with setting the filters in the state. I will dig deeper.

**Comment by skurvish** [comment]
I have the search bar sticky open when search criteria is selected. I am having trouble at the moment getting the search selection to stay showing for forms but am working on it. I also inserted the No Matching Results message. Hopefully have this cleaned up by tomorrow some time.

**Comment by skurvish** [comment]
Fixed with PR #191
