### ISSUE TITLE
put Lizt.php into Googlemap viz plugin

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#139]
it's the only place where it is used, see https://github.com/joomlahenk/fabrik/pull/138

**Comment by joomlahenk** [comment]
Lizt contained just one function. I added the function to ../models/googlemap.php and removed Lizt

**Comment by trob** [comment]
https://github.com/joomlahenk/fabrik/commit/14117369675fc085943d5d7ae48420cfbd572062
