### ISSUE TITLE
mysql and php8.1

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#14]
Mysql under php8.1 is much more stringent when it comes to defaults for columns. I am creating an update sql file for version 4.0 that will add these defaults. In the mean time if you run into this issue here are the defaults I have so far:

ALTER TABLE `#__fabrik_groups` ALTER modified SET DEFAULT `0000-00-00 00:00:00`
ALTER TABLE `#__fabrik_groups` ALTER modified_by SET DEFAULT 0
ALTER TABLE `#__fabrik_groups` ALTER checked_out SET DEFAULT 0
ALTER TABLE `#__fabrik_groups` ALTER checked_out_time SET DEFAULT `0000-00-00 00:00:00`

ALTER TABLE `#__fabrik_lists` ALTER form_id SET DEFAULT 0
ALTER TABLE `#__fabrik_lists` ALTER modified SET DEFAULT `0000-00-00 00:00:00`
ALTER TABLE `#__fabrik_lists` ALTER modified_by SET DEFAULT 0
ALTER TABLE `#__fabrik_lists` ALTER checked_out SET DEFAULT 0
ALTER TABLE `#__fabrik_lists` ALTER checked_out_time SET DEFAULT `0000-00-00 00:00:00`
ALTER TABLE `#__fabrik_lists` ALTER hits SET DEFAULT 0

ALTER TABLE `#__fabrik_forms` ALTER modified SET DEFAULT `0000-00-00 00:00:00`
ALTER TABLE `#__fabrik_forms` ALTER modified_by SET DEFAULT 0
ALTER TABLE `#__fabrik_forms` ALTER checked_out SET DEFAULT 0
ALTER TABLE `#__fabrik_forms` ALTER checked_out_time SET DEFAULT `0000-00-00 00:00:00`
ALTER TABLE `#__fabrik_forms` ALTER reset_button_label SET DEFAULT ""

ALTER TABLE `#__fabrik_elements` ALTER modified SET DEFAULT `0000-00-00 00:00:00`
ALTER TABLE `#__fabrik_elements` ALTER modified_by SET DEFAULT 0
ALTER TABLE `#__fabrik_elements` ALTER checked_out SET DEFAULT 0
ALTER TABLE `#__fabrik_elements` ALTER checked_out_time SET DEFAULT `0000-00-00 00:00:00`

I am sure we will find more as we move along.

**Comment by joomlahenk** [comment]
Ah, good to know. I don't switch to PHP 8.1 yet, but once we have a working fabrik 4.x version I will. I would set date-time defaults to 1970-01-01:00:00:00 though.

**Comment by skurvish** [comment]
Not sure I would set those defaults for things like checkout time etc as this could be misleading.

**Comment by skurvish** [comment]
I have updated the install sql file with the appropriate defaults. Will check in with a bunch of my other stuff.

**Comment by skurvish** [comment]
file updated and checked in with the J4class PR.

**Comment by trob** [comment]
I just run into _elements.ordering (repeat group element creation)
I think we should add defaults to **all** columns - in install and update sql

**Comment by skurvish** [comment]
Agreed.

**Comment by trob** [comment]
You can't SET DEFAULT NULL on columns with NOT NULL (which sounds logical).
It seems to be accepted in a CREATE TABLE but not in ALTER TABLE.
You said somewhere DATETIME has to be NULL?
Then the update sql must reset the column to be nullable like
ALTER TABLE `#__fabrik_groups` CHANGE modified modified DATETIME NULL DEFAULT NULL;
for such datetime columns.
And it needs ; at line end.

But with these modifications the update it's working :)

Who is doing the SQL's?

**Comment by joomlahenk** [comment]
Mysql updated and working.
Still have to make mysql-update run after upgrade. This does not happen now, because Joomla does not see this as an update.
Working on it

**Comment by joomlahenk** [comment]
Solved with commit "Working upgrade/install/update/uninstall"
