### ISSUE TITLE
Add library to pkg_fabrik.xml

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#143]
The fabrik library files upgrade/install/update/uninstall now seperately. They are no longer in components and the install script does not need to move any files or folders.
Package library must be added to pkg_fabrik.xml.
<file id="library" type="library">library.zip</file>

**Comment by joomlahenk** [comment]
Package library must be added to pkg_fabrik.xml.
file id="library" type="library">library.zip</file

**Comment by joomlahenk** [comment]
Also add in the build process

**Comment by skurvish** [comment]
Complete with PR #162
