### ISSUE TITLE
Add list of unsupported plugins to wiki

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#144]
Some plugins are deprecated. Some are rarely or never used. Are we going to do as much plugins as possible or do we make a selection? Maybe update a rarely used plugin on request?

**Comment by trob** [comment]
` Maybe update a rarely used plugin on request?` Yup.

May depend also on this `transferring the control over the Fabrik repository and wiki to 'the community’.`
But I have no idea how this should go on.

**Comment by joomlahenk** [comment]
But we can add a list of plugins WE are not going to do

**Comment by joomlahenk** [comment]
List is added to the wiki
