### ISSUE TITLE
Add CSS for size of input boxes input-* 

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#150]
In J!3 we had input-mini, input-small, etc for the size of inputboxes. Do we change all to col-md-* or do we add them in fabrik css, so they still can be used ?

**Comment by skurvish** [comment]
This is going to take some work. With BS5 we need to place the sizing on the control div but fabrik currently places it on the input field. Plus will need to map the input-xxx to BS5 col classes. I am on it.

**Comment by joomlahenk** [comment]
It's meant to support applications that use input-xxx. I beleave in J!3 the size of these is defined in pixels, col-md-'s are not.

**Comment by skurvish** [comment]
input-xxx was a BS2 class and won't be needed for F4. We will have to map them to col- classes on the fly as many applications will have the input-xxx defined in the elements.

**Comment by skurvish** [comment]
I have this mostly done. Just a few things to clean up. Should be able to check it in tomorrow.

**Comment by joomlahenk** [comment]
Take the most recent files from GH, as I have made some changes also. I removed input-xxx but did not add col-classes, because it sometimes makes it worse. F.i col-md-1 is not quite equal to input-min. Maybe it's better to only remove input-xxx and change the size later in CSS.

**Comment by skurvish** [comment]
The input-xxx classes are now mapped to col-md classes in increments of 2. These should work for most applications.
