### ISSUE TITLE
J! send password

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#153]
Despite J! user options 'Send Password'=no Joomla is sending the password in the "New user details" email.
Can you confirm this?

**Comment by trob** [comment]
Create a new user, Joomla will send the email.
It's not related to Fabrik, I run into it while testing the juser plugin (which has still its own issues)

**Comment by joomlahenk** [comment]
I have email sending enabled, but PHP and Sendmail don't work. So I need to setup SMTP.

**Comment by trob** [comment]
I think it's a bug in Joomla. "send no password" option is stored correctly (juser form plugin can use it).
J!4 has introduced "mail templates", types com_users. abc and com_users. abc_w_pw are in the database but they seem to fetch the wrong type.
That's also where they modified the COM_USERS_EMAIL_abc language strings from sprintf format "... %s..." to custon placeholders like "... {NAME}..." but don't provide a public function for replacing
