### ISSUE TITLE
Caching error on Lists -> view data if calc element is used.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#156]
I have a list with a calc element. When I want to view the list in the backend, I get:
Too few arguments to function FabrikFEModelList::columnData(), 1 passed in /var/www/html/j4fabrik/libraries/src/Cache/Controller/CallbackController.php on line 51 and at least 2 expected
If I unpublish the calc element the data is displayed.

As far as I can see it has nothing to do with the calc element, only that if you use it the cache seems to be used.

**Comment by joomlahenk** [comment]
OK, just fixed that. It's a miracle that this was working in J!3, but then the J!3 code for the cache controller was rather clumsy.
I fixed it in site/models/list.php, but there may also be an issue with element.php

**Comment by trob** [comment]
`It's a miracle that this was working in J!3`
Maybe it was not ;) I can remember strange caching issues with ajaxfied lists...
