### ISSUE TITLE
Issue with tooltips on plugins

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#157]
For all plugins in all property forms and also validation and javascript:
Tooltips are displayed on the canvas instead in a box. This is repeated on every focus of the item label.

**Comment by trob** [comment]
Yes, it seems my layout override doesn't take it all but only in the "main" parts.
administrator\components\com_fabrik\layouts\joomla\form\renderlabel.php

Meanwhile I found that Joomla shows the descriptions now below the fields but I didn't find how to enable this.
You can also have a button "Toggle inline help" in forms additionally to the "Help" button but I don't know how to and there may be still issues
https://issues.joomla.org/tracker/joomla-cms/37772

I'll have a look, but not today and not tomorrow

**Comment by joomlahenk** [comment]
I would label this high priority, because it really messes up the plugin settings (sub)page

**Comment by trob** [comment]
Solved for inline descriptions with https://github.com/joomlahenk/fabrik/pull/194

**Comment by joomlahenk** [comment]
I tested #194, but had to revert that.
So it's not solved yet.

**Comment by joomlahenk** [comment]
Plugin tooltips are done in administrator/components/com_fabrik/views/namespace.js (yeh, that's a very logic name for it).
If I remove:
`		if (typeof(jQuery) !== 'undefined') {
			jQuery('.hasTooltip').tooltip({'html': true, 'container': 'body'});
			jQuery(document).popover({selector: '.hasPopover', trigger: 'hover'});
`
then te tooltips are working. However we have a white box with black text, that's something for later to solve.
jQuery was used to show the tooltips in a plugin. I guess it conflicts with tooltips for BS5.

Merged it and set this issue to low priority.

**Comment by joomlahenk** [comment]
Solved with PR #221.
The icons may be overdone, but that's just a matter of taste.
