### ISSUE TITLE
Incorrect integer value: '' for column...

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#16]
After setting default in the fabrik tables, I get several "Incorrect integer value: '' for column" errors.
Because a default is set now. all columns that are going to be saved in the db must comply to the default type.

I get: Incorrect integer value: '' for column `j4fabrik`.`chx1p_fabrik_forms`.`id` at row 1
So that means that somewhere in the code the 'id' was set as column to store in the #_fabrik_forms` table. This should never have been set.
Could not find where this is done yet.

I expect we will get more of these errors.

**Comment by trob** [comment]
I think to set a default for an autoincrement PK column doesn't make sense

**Comment by joomlahenk** [comment]
True, but it seems that somewhere in the code they want to store ' ' or null in 'id'.
Unable to find where this done.
I get this issue when I want to copy a list. Then only a group and elements are stored, not a list and form.

**Comment by trob** [comment]
ok, yes, it's the same without setting a default on fabrik_lists.id

**Comment by trob** [comment]
https://github.com/joomlahenk/fabrik/compare/henk40...trob-patch-2
