### ISSUE TITLE
Ajax edit/view link not longer working, pagination broken

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#164]
after the last merges

**Comment by joomlahenk** [comment]
Maybe something with the paramsoverride ? All other merges from Alex are for .xml files. Don't think they have something to do with it.
I changed ../models/list.php yesterday, but that must be done to have cache working.
I don't have a possibility to test ajax yet.
Do you get a error or debug info?

**Comment by trob** [comment]
No, not paramsoverride, it's https://github.com/joomlahenk/fabrik/pull/160 (Update layouts as per the BS3 overrides...)
e.g. there are modifications in fabrik_edit/view/delete_button ommiting several attributes, amont others is_ajax
and modifications in fabrik_pagination_links (which was working with BS5 before)

**Comment by skurvish** [comment]
I will have a look later today. I have a pressing issue to fix on my production site.

**Comment by skurvish** [comment]
@trob I see the 2 ajax items, but I do not see anything in pagination that should mess it up. The layout changes I made are the ones that were part of the BS3 overrides and are working on my production site.

I will insert the 2 ajax items but I will need more help in understanding what is wrong with pagination.

**Comment by skurvish** [comment]
Ajax edit/view updated with PR #166

**Comment by skurvish** [comment]
@trob is this still an issue?

**Comment by skurvish** [comment]
OK, I see the problem. This was easy enough to fix. But the formatting is pretty ugly so I will see about fixing it.

**Comment by trob** [comment]
The pagination was working before https://github.com/joomlahenk/fabrik/pull/160 (including BS5)

**Comment by skurvish** [comment]
Pagination is now working. The formatting of the pagination links is off though. I do not see anything different in that respect to the code prior to #160

**Comment by skurvish** [comment]
I am still working on this. Hope to have it all resolved today.

**Comment by skurvish** [comment]
Pagination is fixed with PR #185.

@trob are the ajax links still broken? If so please advise how I can test them. Otherwise let's close this.

**Comment by trob** [comment]
Ajax links are ok since isajax option re-added
