### ISSUE TITLE
List and form setup: plugins

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#169]
Plugin selection is missing "Please select" so it's showing the first plugin but without any plugin parameter

Minor issue: While trying to add a first plugin (click "Add", with browser console open) I get
![grafik](https://user-images.githubusercontent.com/1045355/181902687-9e22c12c-2a85-4ef2-989b-0ec1c422fd33.png)
It doesn't hurt, with clicking Resume it's going on, but do you have an idea?

**Comment by joomlahenk** [comment]
Maybe they don't want -bs- and remove it, but it's required for BS5. Is this in pluginmanager.js ?

**Comment by skurvish** [comment]
Fixed with PR #179
