### ISSUE TITLE
menu item->fabrik list->options: elements selection and prefilter not working

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#172]
Not fixed ! I installed fabrik4 and I have params.php in admin/templates/atum/html/layouts/joomla/edit, but the modal does not close like before.

**Comment by skurvish** [comment]
I will have a look, not until tomorrow though.

**Comment by skurvish** [comment]
Can you advise specifically where you are seeing this?

**Comment by joomlahenk** [comment]
fabrik->lists->new/edit->details->filters->elements select
fabrik->lists->new/edit->details->layout->responsive CSS select
fabrik->lists->new/edit->publishing->CSV->elements select
fabrik->lists->new/edit->publishing->OAI->element mapping select
menu item->fabrik list options COM_MENUS_LIST_ELEMENTS_MODAL_FIELDSET_LABEL
menu item->fabrik list options COM_MENUS_PREFILTERS_MODAL_FIELDSET_LABEL

**Comment by joomlahenk** [comment]
Also in the installer script line 393: maybe use file::move instead ? Now we end-up in having the params.php in 2 locations

**Comment by trob** [comment]
It's working fine in my existing site. So it is only after a new installation on a new site?

**Comment by joomlahenk** [comment]
Yes, I did a new installation on a new site. How did you get it working?

**Comment by trob** [comment]
Ah, just tried with Fabrik debug =no (instead of Debug JS) and can see also issues in the existing site (tested with publishing CSV).
So it seems not all js files are minified.
It may be also files from me, I did no minifying.

**Comment by trob** [comment]
For the list menu: I don't have the params.php and I don't see anything but the language strings in menu item->fabrik list options.
For having also GitHub updates working all files should be at their final positions - although I see the problem here because of putting it in the admin template.
What do I have to move exactly to where manually?
administrator\components\com_fabrik\layouts\joomla\edit\params.php to ??

**Comment by joomlahenk** [comment]
The installer copies it to: administrator\components\templates\atum\html\layouts\joomla\edit\params.php
But I am not sure if that is correct, because it does not work.

**Comment by trob** [comment]
With the file at this position it is working on my site (list options showing up again + Show in list and Pre-filters Selects working).
Small issue: below it's showing the empty COM_MENUS_LIST_ELEMENTS_MODAL_FIELDSET_LABEL etc fieldsets/legends

**Comment by joomlahenk** [comment]
fabrik->lists->new/edit->details->filters->elements select is showing, but if I press close it does not close. I didn't try to enter a filter.
It's possible that your browser uses the js in it's cache. In chrome you need to go to the triple point menu->help programs->delete browser data->select cached images and files->delete and then restart the browser

**Comment by trob** [comment]
As I said: 
On my site it's working with allow FabrikDebug=Debug JS (i.e. running non-minified Fabrik files ), issues with FabrikDebug=no

BTW: Chrome with dev console open -> you can hard reload by holding the reload icon and select "Cache leeren und vollständig aktualisieren" (in German), it's the 3rd option (the one without short key).

**Comment by trob** [comment]
It's mootools-ext.js which is not minified.
I just copied mootools-ext.js from media/com_fabrik /js/ to /js/dist and it is ok now.

**Comment by skurvish** [comment]
I have some other js files to minimize so will check them in tomorrow. As for move versus copy there is no point moving it as it would just be replaced on a github update. Furthermore in the event a user changes the admin template we can provide instructions on what to copy where. Hard to do if the original was moved.

**Comment by skurvish** [comment]
Yes, and it was the mootools-ext.js file that had the fix for the close problem. I thought I had minified it and checked it in but perhaps I did not.

**Comment by trob** [comment]
How do you minify? With an online tool or locally?

**Comment by skurvish** [comment]
Run "grunt js" that will minify all the js files. Best process is commit all your changes so you have nothing in the branch that has changed. Run "grunt js" and then commit the specific js files you changed. The do a "git checkout ." to clear out the other js files that were minified and that do not need committing.

I also suggest if you wish to do an install you build the project using grunt and install the package.

**Comment by joomlahenk** [comment]
I minified mootools-ext.js and the modals close now indeed. But I still have:
menu item->fabrik list options COM_MENUS_LIST_ELEMENTS_MODAL_FIELDSET_LABEL
menu item->fabrik list options COM_MENUS_PREFILTERS_MODAL_FIELDSET_LABEL

**Comment by joomlahenk** [comment]
I have 47 js files in media/com_fabrik/js and only 38 in in media/com_fabrik/js/dist. So maybe more need to be minified?
Or are some files called from media/com_fabrik/js instead? I wouldn't be surprised.

**Comment by joomlahenk** [comment]
OK, js files to move to  media/com_fabrik/js/dist:
mootools-core.js
mootools-more.js
calendar.js
calendar-setup.js

Rename in media/com_fabrik/js:
mootools-core-uncompressed.js -> mootools-core.js
mootools-more-uncompressed.js -> mootools-more.js
calendar-uncompressed.js -> calendar.js
calendar-setup-uncompressed.js -> calendar-setup.js

But then also change the path to these js files in the code where they are used

**Comment by joomlahenk** [comment]
Merged updated mootools-ext.js in media/com_fabrik/js/dist

**Comment by joomlahenk** [comment]
Merged correct location of .js files: mootools and calendar are now in media/com_fabrik/js/dist

**Comment by joomlahenk** [comment]
OK, the modals show-in-list and pre-filter are working, but at the end of the form I still have:
COM_MENUS_LIST_ELEMENTS_MODAL_FIELDSET_LABEL
COM_MENUS_PREFILTERS_MODAL_FIELDSET_LABEL

These should be deleted somewhere.

**Comment by skurvish** [comment]
Ah, I never looked that far down. I am sure I can figure out how to get rid of them. Leave it with me.

**Comment by skurvish** [comment]
OK, needed another tweak to the params.php override. Seems to be working properly now with PR #178
