### ISSUE TITLE
JS files to minify

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#173]
Trob's missing minified files: what is the best way?

administrator/components/com_fabrik/models/fields/listfields.js

media/com_fabrik/js/list.js   ->minify /dist
media/com_fabrik/js/window.js  ->minify /dist

**Comment by joomlahenk** [comment]
listfields-min.js is also in administrator/components/com_fabrik/models/fields/listfields.js
media/com_fabrik/js/list.js is readable text, media/com_fabrik/js/dist/list.js is the minified version of it

they just liked to make it confusing and complicated
also: what you expect to be in .js can also be in .php and visa versa

**Comment by trob** [comment]
media/com_fabrik/js/mootools-ext.js   ->minify to js/dist

**Comment by joomlahenk** [comment]
Just merged. All minified mootools are now in media/com_fabrik/js/dist

**Comment by skurvish** [comment]
Are there still files that need minified? It is easy for me to do and check in if I have a list.

**Comment by trob** [comment]
As far as I can see in the code the non-minified files are newer. So 

administrator/components/com_fabrik/models/fields/listfields.js  -> listfield-min.js

media/com_fabrik/js/list.js ->minify js/dist/list.js
media/com_fabrik/js/window.js ->minify js/dist/window.js

**Comment by skurvish** [comment]
OK, Will minify and PR first thing tomorrow.
