### ISSUE TITLE
Date Columns Defaults for user lists.

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#175]
Like the Fabrik tables, the tables for lists will need to be updated to allow NULL and to set the default value to NULL.

This could be accomplished during the installation process by going through all the existing lists and updating the DB tables.

Do we need an update script that processes all of these things? We may find other things that need updating as we go along.

**Comment by joomlahenk** [comment]
I am not sure yet if that will cause an issue, have to experiment with that.
But yes, we can compare the db version in #__schemas. If we do it preflight this will still be 3.10. We don't do it for >= 4.0
The fabrik 'customer' db's (db_table_name) are in the #__fabrik_list table, but they can also be db views. So for views you will get a db error if you want to update.

**Comment by skurvish** [comment]
Is there a way to determine if the list points to a view or an actual table? I have not used views in the past, good thing we all have different experiences as I probably would not have caught this.

**Comment by joomlahenk** [comment]
To check if we are dealing with a db view, I think the only thing we can do is to catch the db error.
Also: fabrik does detect when you create a list from a view, so maybe we can copy that.
But I am still not sure this is going to be an issue, or did you encounter it?
Fabrik does not require strickt for the database.
I have to test this.

**Comment by skurvish** [comment]
On one of my lists I have a number of Date elements. When I try and save the form I am getting MSQL errors for an invalid default value.

**Comment by trob** [comment]
`Is there a way to determine if the list points to a view or an actual table?` Yes, it's in the list's params (..."isview":""} )

**Comment by trob** [comment]
I think we should not do modifications on user tables automatically during install. There may be tables coming from/used by 3rd party software which should not be touched etc.
I would rather provide some scripts which the user can run manually - on his own risk.

**Comment by skurvish** [comment]
You make a good point. Perhaps we can provide instructions along with a form php plugin file that does the work for them. So a checkbox list of lists and then when they hit save it makes the changes? Or, we simply provide them with a php script that will make the change and let them muddle their way through it?

I expect there are many who would not have the skill set to do it on their own so any help we can provide would be beneficial, provided of course we don't place ourselves in any sort of liability situation. Lots of disclaimers of no liability.

**Comment by joomlahenk** [comment]
Still I am not convinced yet, that this issue will occur. Or did you encounter it?

**Comment by skurvish** [comment]
Yes I did with one of my lists.

**Comment by joomlahenk** [comment]
OK, convinced now. I will try it for one of my applications also.
In case the db defaults are wrong, I think you get an error as soon as you try to go to a list.
We could add a 'tool' on the fabrik home menu that generates that checkbox list of lists.

**Comment by skurvish** [comment]
The error shows up when you try and save a date/jdate element on a form if not data is created for the element on the form.

I think it best as per @trob we can provide a php form script to make the changes, and a php checkbox populate script to create the checkbox list. The users can create their own form and checkbox element on their system and execute it as they see fit. No warranty form us, use at own risk, etc. etc....

**Comment by skurvish** [comment]
As people start to do upgrade testing I think we are going to see more of this. So I am moving this up toward the top of the issue list so we can monitor.

**Comment by skurvish** [comment]
Based on my limited testing on a J3-J4 upgrade this does not seem to be a problem so I am closing this.
