### ISSUE TITLE
Additional BS Changes Required

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#176]
As I was finishing up the input size changes I discovered that the select lists no longer have the down arrow. This is because there needs to be a class of "form-select" on the select field. I am going to see if other field types need similar things.

**Comment by joomlahenk** [comment]
Yes, I changed all to have form-select if it's a select. Others need to be form-control. I changed much, did you undo that?

**Comment by skurvish** [comment]
No, I didn't undo your change. I just noticed it needed to be done in my repo so I noted it here. I had not checked again since your recent updates. If it is all done then less work for me, thanks!

**Comment by skurvish** [comment]
However, having said that, I don't see the arrows on my forms.

**Comment by joomlahenk** [comment]
I have the arrows (form-select) where they must be on my forms. Did you update from GH? Did you refresh your browser?
For chrome refresh is not enough, you have to delete images and files to get your updated CSS and JS.

**Comment by skurvish** [comment]
I did all that and am not seeing the down arrows. The form-select class is not on the select. It is once I add the changes I PR'ed.

**Comment by trob** [comment]
You mean in the admin forms? Ok here, too. (Arrow showing, form-select there)

**Comment by skurvish** [comment]
No, I am talking about forms on the front end.

**Comment by joomlahenk** [comment]
OK, I also thought you meant the backend. Yes, the frontend still needs some work. Backend has more priority, at least for me.

**Comment by skurvish** [comment]
OK can you please merge this so we can move forward.

**Comment by joomlahenk** [comment]
Do you means the BS5 changes in the backend?

**Comment by skurvish** [comment]
These are front end layout changes.

**Comment by skurvish** [comment]
OK, now I have lost all my down arrows in my dropdowns on the front end with your changes to my changes.

**Comment by skurvish** [comment]
And the formatting bootstrap classes are not being applied.

**Comment by joomlahenk** [comment]
Sorry. Had a merging issue. Just repaired. Hopefully all works now?

**Comment by skurvish** [comment]
So far it all looks OK. I closed the PR. If I find anything else I will open a new one. Closing this.
