### ISSUE TITLE
 Cassiopeia site with Fabrik list: layout broken

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#180]
with https://github.com/joomlahenk/fabrik/pull/167

**Comment by skurvish** [comment]
Can you be more specific? My Cassiopia list looks fine (other than the pagination bits)

**Comment by trob** [comment]
![grafik](https://user-images.githubusercontent.com/1045355/182039376-7d53cec9-649c-40cb-9582-e483244fc3a3.png)

Obviously fabrikFilterContainer and fabrikDataContainer are outside the fabrikForm (and even outside the site-grid)

![grafik](https://user-images.githubusercontent.com/1045355/182039468-14893208-2512-4fce-9b23-29b5bd5c9570.png)

**Comment by trob** [comment]
Fixed with https://github.com/joomlahenk/fabrik/pull/183
