### ISSUE TITLE
We need a priority list

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#181]
We have made a lot of progress on getting this working on J4. I don't have a sense though as to how close or how far away we are.

i think we need some sort of issue prioritization system, or at least a wiki with a priority list that we can add/subtract from.

Any thoughts?

**Comment by trob** [comment]
Maybe we can use GitHub's "Projects" (I never used it). But as fas as I can see Henk has to open it here (I can't see an "Add project" as in "my" organisation.

**Comment by joomlahenk** [comment]
I looked at the GitHub's project, but for me it takes too much time to set it up and understand how that works. Let's keep it simple. We can use the wiki.

**Comment by skurvish** [comment]
We could use a simple google sheets. Maybe I will see if I can find one already set up that we can borrow.

**Comment by skurvish** [comment]
I have created some tags for this: High Priority, Medium Priority, Low Priority & Nice to Have

If we assign the appropriate level to the issues it will make it easier to determine what should be looked at next.

When you decide to take an issue please assign it to yourself so we don't duplicate effort and merge conflicts.

Closing thie issue as complete.
