### ISSUE TITLE
Remark to Correct locations for .js files

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#182]
https://github.com/joomlahenk/fabrik/commit/5d1e8eb3da946e3044e4c878c4629d5e13ddb063

I think the xy-uncompressed files are no (original) Fabrik files but the original 3rd party files and never were run. 

So better keep their names and don't use them to create their minified versions, not sure if they are up to date (resp. I know that  mootools-uncompressed is not because at least the changes for googlemaps were made only in the compressed version)

**Comment by joomlahenk** [comment]
They have no use if they don't represent the compressed versions. I can unminify the compressed versions and keep those or remove the "uncompressed".

**Comment by trob** [comment]
`I can unminify the compressed versions and keep those` This sounds good. Then we can do the "usual" way if more modifications are necessary: modify the uncompressed, then minify.

**Comment by joomlahenk** [comment]
Just merged
