### ISSUE TITLE
BS5 update needed for list filter in the BACKEND

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#188]
To display a list in the BACKEND: Lists->view-data
The top buttons, filters and 'display #' are not usable and need BS5

**Comment by joomlahenk** [comment]
Template setting makes no difference. See image
![lists-view-data](https://user-images.githubusercontent.com/40104328/182567509-67e78113-7909-4557-beea-4ab85d826743.jpg)
e

**Comment by joomlahenk** [comment]
For the filter selector: Should show 'All'. If I add form-select in chrome elements it's ok, but I can't find where to set this in the code. (Probably in a not so logical location in a not so logical .php or .js or .xml).
Only display has a form-select, but then the label is too small. The button above are of a different size and too close together.

**Comment by trob** [comment]
The display issues are the same in frontend, it's in the bootstrap template resp. in the layouts (so no BACKEND issue)
e.g. the filter (container) layout is in components\com_fabrik\layouts\list
I didn't test with dropdown filters until now.

I did some BS5 styling some time ago but meahwhile it's overridden by new merges.

**Comment by joomlahenk** [comment]
Yes, the 'view-data' in the backend behaves the same as in the frontend. We need to test both.
I think we need to leave this for Alex, as he did all changes to default_buttons.php.
I tried some of your previous changes, but they don't work anymore.

We need to do more testing, specially the list filters and searches. Then also grouping.

**Comment by skurvish** [comment]
I am working on this.

**Comment by skurvish** [comment]
How do you get the list filters working normally? I cannot seem to get them to work on my production F3 version.

I have the search stuff layout working. The search itself is not working so well so still working on that.

**Comment by trob** [comment]
What do you mean with search not working?
"Normal" list filters as well as 'search all' is working on my site (J!3 and J!4).

**Comment by skurvish** [comment]
I have added some styling for some of this in the PR I did for the modals. When I enter a search term and hit enter the results are not filtered. I need to look further.

I don't see how to set up normal filters and get the dropdowns for them to show on F3 or F4.

**Comment by skurvish** [comment]
@trob @joomlahenk Can somebody test this and see if it is now working?

**Comment by trob** [comment]
I'm not at home at the moment

**Comment by skurvish** [comment]
No rush, whenever you can.

**Comment by joomlahenk** [comment]
in BACKEND list->view-data Filter dropdown is not BS5, see image. 
Also: the 'month' filter is sorting the months on alphabet, not on month
![lists-view-filter_dropdown](https://user-images.githubusercontent.com/40104328/183755519-c5fa58ea-7a21-4c79-a4f8-adb846636cae.jpg)
.

**Comment by joomlahenk** [comment]
in BACKEND list->view-data Filter dropdown is not BS5, see image. Filter is now set "under headings
![lists-view-filter_und_head](https://user-images.githubusercontent.com/40104328/183756358-a50062b1-f15c-4d87-a7f0-1c9810602d0c.jpg)
"

**Comment by joomlahenk** [comment]
in BACKEND list->view-data Filter range is not BS5, see image
![lists-view-filter_range](https://user-images.githubusercontent.com/40104328/183757112-43fd9611-f477-4826-aa3e-8b2973d075e1.jpg)
.

**Comment by joomlahenk** [comment]
in BACKEND list->view-data Filter multi-select is not BS5, see imag
![lists-view-filter_multi_sel](https://user-images.githubusercontent.com/40104328/183757637-1252aaac-8272-4395-a939-f7a22620ede3.jpg)
e

**Comment by skurvish** [comment]
Henk, I have no idea how you are setting up these filters. On my site I never use filters so you are going to have to help me out. Can you do a mysqldump of all your fabrik tables and send it to me so I can import and test these?

**Comment by joomlahenk** [comment]
Well fabrik is full of filters, this is just one of it. So there are more to come-up. I have send you an email how to set it up.

**Comment by skurvish** [comment]
OK, I finally figured out filters. Something I have never used.

I have a first cut on these. Please try them and report any other strangeness.

As for the months sorting this is a calc element yes? Not sure how you would go about sorting these for the filter. Did they sort properly on J3?

**Comment by joomlahenk** [comment]
About sorting: you are correct, that does not work like this, also not in J!3

**Comment by joomlahenk** [comment]
That's already a lot better.
One issue still: the dropdown box always shows 7 items, but it should show 'All' only or the one selected.
This is how it work on J!3

**Comment by joomlahenk** [comment]
All working ok now
