### ISSUE TITLE
Add new record => Class "Factory" not found

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#189]
In the BACKEND: Lists->view-data->+add
Get this error if I want to add a new record. Guess use Joomla\CMS\Factory; is not in some file.
Searched for that file, but couldn't find it.

**Comment by skurvish** [comment]
I am not getting this on my site. Try it again and if it still happens turn on Joomla Debug. It should point you to the file that is the problem.

**Comment by trob** [comment]
I don't get a Factory error. 
But only in case of ajaxfied links (makes sense: it's in partial) and only in the backend I get
Warning: Array to string conversion in C:\xampp8\htdocs\j4h40\libraries\fabrik\fabrik\Document\Renderer\Partial\HeadRenderer.php on line 248
No time to investigate at the momen.
on list Add

**Comment by joomlahenk** [comment]
Solved it. The cause was in a calc. I used Factory, changed to JFactory, then it worked.
Note: JFactory is still allowed and most fabrik users will use it.
