### ISSUE TITLE
Filter pop-up needs BS5

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#190]
In list settings, I set the filter to pop-up, then in the BACKEND: Lists->view-data->filter.
I do get the pop-up (modal), but that needs BS5 and it does not close on X only if you click somewhere else.

**Comment by joomlahenk** [comment]
OK, that solves the close.

**Comment by skurvish** [comment]
Closing.

**Comment by joomlahenk** [comment]
Only the 'close' is solved not BS5

**Comment by skurvish** [comment]
That BS5 issue is covered in issue #158 we don't need it a separate issue for it.
