### ISSUE TITLE
Put all plugins in the wiki, also "to be tested"/"not working yet"

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#193]
We can use it like a checklist. Default is "to be tested", then if it has proved to work change to "working".
Maybe also add a priority, as which plugins should work as a minimum for a "test release".

I really like these priority labels, good job!

**Comment by trob** [comment]
Then we can also add "not supported in F4"

**Comment by joomlahenk** [comment]
I added a new plugin page in the wiki. These are all the plugins in the plugins folder.
