### ISSUE TITLE
"Showon" doesn't do (but never has)

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#195]
Conditionally showing fields in admin forms (the only one I found used in Fabrik is in plugins\fabrik_list\email\forms\fields.xml) doesn't do, but as far as I can see it never has done)

**Comment by joomlahenk** [comment]
Maybe need to add:
	$wa = Factory::getApplication()->getDocument()->getWebAssetManager();
	$wa->useScript('showon');
