### ISSUE TITLE
Update frontend styling for Cassiopeia

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#20]
We can create a list, add a plugin then create a list menu item and have a list diplayed on the frontend.
However we need to update the styling.

**Comment by joomlahenk** [comment]
Much info about styling Cassiopeia: https://slides.woluweb.be/cassiopeia/cassiopeia.html

**Comment by skurvish** [comment]
I think this styling is fixed now. Can one of you please confirm? It looks fine on my system with both Cassiopeia and Helix Ultimate.
