### ISSUE TITLE
Size of JDate & Data inputbox too small, unable to set. Also wrong default of ' '

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#203]
The size of the input/display box is far too small, cannot read datetime. I could not set it to a bigger size.
If I don't fill in a valid datetime, the default ' ' is used which gives a fatal error. The default must be NULL, not ' ', but I could not find where this is set. Can be somewhere in .php or .js or both.

**Comment by skurvish** [comment]
Interestingly I have just been looking at this. What I have found is that Fabrik correctly creates the form element with a null value, however, what is happening is that when the form is posted the value of the field (when nothing is selected by the user) is coming in as an empty string, not null. An empty string is not a valid value for a datetime or timestamp column.

I am looking to see how we can resolve this.

I also discovered that for some reason a number of my lists, forms etc have null in the created and modified columns. Not sure how that happened and it is that way on my production site. Now of course mysql is erroring when processing these fields. Still look.

As for the size I have not had that issue. I have a number of forms with date elements and they are all rendering fine. I tried on Cassiopeia and Helix Ultimate.

**Comment by skurvish** [comment]
Can I ask you both to check your fabrik tables, forms, lists, group, elements and see if any of the created dates at empty or "0000-00-00 00:00:00". I wonder if there was an issue with Fabrik at some time in the past where these values were not being set correctly.

**Comment by joomlahenk** [comment]
As far as I can see from 2016...2021 they are all 0000-00-00 00:00:00 and the db default is also 0000-00-00 00:00:00
If you only use the frontend, you may not discover size and rendering issues because this is using a different template.
The backend has to function also. Some updates we need to do may also have an implication on the frontend.

B.t.w. 0000-00-00 00:00:00 is used in the following files:
libraries\fabrik\fabrik\Helpers\Worker.php
plugins\fabrik_cron\gcalsync\gcalsync.php
plugins\fabrik_cron\php\scripts\fabsubs.php
plugins\fabrik_element\birthday\birthday.php
plugins\fabrik_element\date\date.js
plugins\fabrik_element\date\date.php
plugins\fabrik_element\date\date-min.js
plugins\fabrik_element\jdate\jdate.js
plugins\fabrik_element\jdate\jdate.php
plugins\fabrik_element\jdate\jdate-min.js
plugins\fabrik_form\subscriptions\sql\install.mysql.uft8.sql
plugins\fabrik_form\subscriptions\sql\install.mysql.uft8.sql~

I think that we cannot simply replace those by NULL. 
Some may just check for 0000-00-00 00:00:00 and change to NULL (or ' ')

Most other elements also try to store ' ' if no value entered, thus creating a fatal error.

**Comment by skurvish** [comment]
The only issue with an empty string versus null is for DATETIME and TIMESTAMP sql columns. PR #208 fixes this for date and jdate elements. I will have a look at the others in the above list.

**Comment by skurvish** [comment]
Henk, can you advise if the element size is still too small and if so exactly where? My date and jdate elements are size properly.

**Comment by joomlahenk** [comment]
Size of jdate box is still too small. See also #209. If I remove col-md-* from <div fabrikElement, it is ok.
Date element is not BS5 yet. Time button is invisible.

I also checked if I use most recent  GH update and that's ok. Nice tool for that: WinMerge
Just create a list with jdate or date (not both) and make sure it's not hidden
I still only use the BACKEND: So list->view-data and then add/edit a record.

Null date (no date entered) is working OK now.

**Comment by joomlahenk** [comment]
Partly solved. See solution @ #209, but date element still needs BS5

**Comment by skurvish** [comment]
Fixed with PR #237
