### ISSUE TITLE
Defaults of all elements are set to NULL

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#204]
Defaults of all elements in the database are set to NULL. This is OK for date & datetime, but not for int, text & varchar. An fatal error occurs if default is used i.e. no value entered.

**Comment by skurvish** [comment]
I am not seeing this. When is it happening?

**Comment by joomlahenk** [comment]
Look in phpMyAdmin for the newly created list. I have entered several different elements in the list, so if you look at the structure in the database (using phpMyAdmin), they all have NULL defaults.
Also most elements try to store ' ' as default if no value was entered, which gives a fatal error. In some elements I am able to find where this default is set, but in most it's very hard to find. Can be in anywhere in some .php or .js or both

I am still testing in the BACKEND and I try to enter some data in a list containing several different elements. So list->view-data and then add or edit record.
Also have lots of BS5 issues in the elements.

**Comment by skurvish** [comment]
Make a list of the BS5 issues and how to recreate them. I can take a stab at fixing them.

**Comment by joomlahenk** [comment]
Will take a very long time before I checked _every_ plugin, so I can do a few at a time. I prefer to do that by creating an issue for the ones I am unable to fix in a reasonable time. I also keep the plugins overview in the wiki up to date with that.

To recreate is always the same for element plugins: I am still testing in the BACKEND and I try to enter some data in a list containing several different elements. So list->view-data and then add or edit record. You will get the (BACKEND) form with the elements in the list, then you will see the BS5 issues. You can check with inspect (at least in chrome) what fabrik has created in html and css.

I will do all other plugins later.

I do every test in the BACKEND so far. The frontend is for later when the backend is ok.

**Comment by trob** [comment]
I also don't see an issue with default NULL (as long as the columns are nullable - and they are).
I can store empty field (varchar), textarea (text) and dbjoin (int) without issue.

PHP8.1,

**Comment by skurvish** [comment]
May be php8.1 and if it is we do need to resolve it to work

**Comment by joomlahenk** [comment]
@trob Correct, you can store an empty field (varchar), textarea (text), because the default is ' ' which is ok for varchar and text. A dbjoin (int) does not store ' ', because you must set an other list to join with so it will store a valid id(int). Please try a simple field element and set it to decimal. Or try to store an empty jdate or date, there are many more.
I am on php8.0, but I will try 8.1 as well.

**Comment by joomlahenk** [comment]
Maybe we can add instructions that users always must set a valid default value for an element
