### ISSUE TITLE
Delete tables on uninstall

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#205]
Did we decide we wanted to leave the fabrik tables intact on uninstall? At present they are being deleted, but not all of them.

If we want to delete them then we should add the other tables.

The uninstall as NOT deleting the users list tables which I am pretty sure we do not want to do.

**Comment by joomlahenk** [comment]
Which tables are not uninstalled? As far as I know, J! deletes the same tables that were installed during uninstall.
So tables that were not installed will stay. This can be the tables that were there from fabrik 3.10, but are not in fabrik 4.0. This can be the fabrik_package table, but I added this one to delete in the sql update, so it should not be there.
Other tables can come from plugins installed in 3.10, but not installed in 4.0. J! is not aware of those and will not uninstall them.
I didn't test yet what happens during install / upgrade / uninstall of plugins, though.

**Comment by joomlahenk** [comment]
I would rate this issue low priority, because it does not prevent fabrik4 from working with.

**Comment by skurvish** [comment]
I am running on a vanilla J4 that never saw Fabrik before. When I uninstall fabrik the following tables are left: 

#__fabrik_comments
#__fabrik_notification
#__fabrik_notification_event
#__fabrik_notification_event_sent
#__fabrik_ratings
and 7 number of tables for subs

These all get created by a basic install and are not deleted during uninstall.

**Comment by joomlahenk** [comment]
These are all from plugins. The plugins are part of the fabrik4 package install, I guess? Or did you install them separately?
Maybe the sql install part of the plugin is not correct yet.
Try deleting mysql	<file charset="utf8" driver="mysql">sql/install.mysql.uft8.sql</file>

What about #__fabrik_consent: is it deleted? Or did you not install it? This one has no uninstall sql
Same for #__fabrik_log and a lot more.

Possible cause can be that sql update is missing in plugins. Unlike J!3, J!4 uses this to check the database version.
Maybe we need to add that, see fabrik component.

**Comment by skurvish** [comment]
I don't remember installing any of those. I will do some further investigations.

**Comment by skurvish** [comment]
Found the issue. My fault. For testing I can copied all of the production fabrik tables to my J4 test database so I would have lots of lists/forms/groups/elements etc to test with. The tables referenced above came from my production system and were not created by the fabrik install.

My bad. Closing this.
