### ISSUE TITLE
Delete folders on uninstall

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#206]
The admin & site component folders, the library folder and the module folders are automatically deleted by the J! installer when the package is uninstalled. The plugin folders for each plugin is also deleted. What remains are the higher level folders for the plugins such as fabrk_form, fabrik_list etc. 

The fabrik uninstall script removes the media/com_fabrik folder which I am not sure is required as the installed should remove this. The uninstall also removes the plugins/fabrik_element folder.

So the question is, should we higher level plugin folders as well in the uninstall script?

Should we even care? Normally it is not necessary to uninstall fabrik unless it was installed for testing purposes. If it is installed for production purposes it probably should not be uninstalled.

One of the other issues with uninstall is that all user created scripts in places like plugins/fabrik_forms/php/scripts and the various places javascript is placed as well as layout overrides.

I am of the opinion that if we are going to delete stuff we should delete it all.

Your comments welcome.

**Comment by joomlahenk** [comment]
Yes, I know that happens on uninstall. We can delete empty folders, but I found it not so necessary. I also got warnings if I deleted an empty folder.

**Comment by skurvish** [comment]
I think we should delete the plugin high level folders. There is no reason to keep them.

**Comment by joomlahenk** [comment]
OK, I will delete them in the uninstall postflight and see what happens. I used to get warnings.

**Comment by joomlahenk** [comment]
Just did an uninstall: Surprise, plugin high level folder is deleted by J!. So I think we don't need to change anything.
All I did is an install and then an uninstall. There were many element plugins in the install package, but no other plugins.
We get many warnings, but that seems to be done on purpose by J!. => Change error level reporting (I have that on maximum now)
