### ISSUE TITLE
Strange effects with BS5 col-md-* in element plugins

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#209]
I am testing plugins. Most of them must be updated for BS5. For the ones I tested so far I often need to remove col-md-6 from class="fabrikElement col-md-6" to be able to make the input box bigger. So I think it should not be there at all. I am not able to find where this is set.
Another strange thing is <div col-md-12"> this should be <div class="col-md-12"> and with that I can change the size of some boxes (set it to col-md-6 f.i.), but I am unable to find in the code.

**Comment by skurvish** [comment]
I think part of the problem is that the div's are not set up in containers and rows. This is easily fixed. I will get to it.

**Comment by joomlahenk** [comment]
class="fabrikElement col-md-6" is the cause that boxes are too small. If I remove col-md-6 some are ok, not all: dropdown is still too small. The bootstrap class setting for dropdown does not work.
There are a lot col-md-* that don't do anything.

**Comment by skurvish** [comment]
Henk, can you please point me to a specific example? Otherwise I am just wasting time searching around.

**Comment by joomlahenk** [comment]
See #203. <div fabrikElement> should not have col-md-* . Example is dropdown element. The col-md-* is the selected bootstrap class setting, but it does not belong in <div fabrikElement>
In this way, the selected bootstrap class setting is applied on the fabrikElement _content_, not on the selection box.

**Comment by joomlahenk** [comment]
(once again)
See #203.

div fabrikElement /div should not have col-md-* . Example is dropdown element. The col-md-* is the selected bootstrap class setting, but it does not belong in

In this way, the selected bootstrap class setting is applied on the fabrikElement content, not on the selection box.

**Comment by trob** [comment]
dropdown col-md-6 default is set in fields.xml

I think there should be as little as possible framework specific stuff outside of overrideable layout files and templates.

**Comment by skurvish** [comment]
I am working on all of the plugin BS5 stuff at this time. I learned a few things about BS5 that I did not know so am going through everything and rewriting what needs to be rewritten. I am finished with Field and textarea. Partially finished with checkboxes/radios and am next onto dropdowns and database joins (pretty much the same as dropdown).

Hang in there.

**Comment by joomlahenk** [comment]
I solved this. There were typo's with adding $element->bsClass (space omitted, wrong quotes, etc.)
I updated, tested and merged.
The strange <div col-md-12"> was in components\com_fabrik\views\form\tmpl\bootstrap\default_group_labels_side.php
Also caused by typo's, but I removed this div. This is the only place a div is added, not in any of the other files.
