### ISSUE TITLE
New list database setting keeps spinning

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#21]
Lists->new->data tab data database table keeps spinning.

**Comment by trob** [comment]
I assume it's looking for a PK default (should show "-").
But it doesn't seem to hurt.

**Comment by skurvish** [comment]
I think this is related to #32

**Comment by joomlahenk** [comment]
I am working on the #32 right now and yes the spinning stops after a db table is entered. But in J!3 it never spins, so it has a different cause. (some JS magic I guess)

**Comment by trob** [comment]
It's also showing the spinner in dbjoin "Data", although the dropdowns are populated and the element is saved.

So some JS not hiding it?
In J!3 the ajax-loader.gif is also always "there" but with display:none

**Comment by joomlahenk** [comment]
Solved
