### ISSUE TITLE
The admin/update folder should be empty

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#211]
I cleared the admin/update folder a long time ago. Now since 2022-08-09 it's filled again with all fabrik31 files.
Is there a reason for this or is it just by accident, so we remove it again?

**Comment by skurvish** [comment]
No, this folder must exist with all those files or the grunt build process fails. Please leave it be. I noted this when I added this folder back in and PR'ed it.

**Comment by joomlahenk** [comment]
OK, but can you move it to a folder that will not be part of the fabrik package? We don't need it for fabrik, only for the grunt build process.

**Comment by skurvish** [comment]
This directory is not included in the package installation zip when created by grunt.

**Comment by joomlahenk** [comment]
It is located in the admin folder, so I thought it's part of com_fabrik. But you are right, it's also not there in J!3
