### ISSUE TITLE
PHP 8.1 issue

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#212]
Most recent GH, fabrik4 installed on virgin J!4.1.5
PHP 8.1 

fabrik->lists->new
Deprecated: mysqli::real_escape_string(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/joomla4/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php on line 388

Create list

fabrik->elements
Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/joomla4/libraries/src/MVC/Model/ListModel.php on line 586

Change to PHP 8.0

No deprecate warnings

**Comment by skurvish** [comment]
I fixed the first one with PR #215 . Not sure how to fix the second. Not gonna waste that much time on it right now.

**Comment by joomlahenk** [comment]
OK, the second is a J! issue, maybe solved in upcoming 4.2
