### ISSUE TITLE
One more PHP8.1 deprecation

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#216]
Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/j4fabrik/components/com_fabrik/models/list.php on line 1303

OK, I will switch to PHP8.0 now. This causes too much trouble.

**Comment by skurvish** [comment]
I see no reason for you to switch back to php8.0. These deprecated warnings can be safely ignored while you are testing and they can be noted and fixed as we go along. Unless you are getting dozens of them making your work difficult I would like you to stay with PHP8.1 so we can clean these up.

J! itself issues tons of these deprecated warnings so hopefully they will fix them up as well.

**Comment by joomlahenk** [comment]
I can not work on fabrik4 with a screen full of warnings. Maybe some time later I switch to PHP8.1 once in a while.

**Comment by trob** [comment]
In J! GlobalConfig you can switch the error reporting between Maximum and System default (+ Simple and None)
Set your System Default (e.g. in php.ini) to
error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT

Then you'll get still warnings and notices but not the deprecated warnings.

**Comment by joomlahenk** [comment]
Yes, I know I can set error reporting in globalconfig, but I want to see all fabrik warnings so I want to keep that on max.
I already set error_reporting "E_ALL & ~E_DEPRECATED", but I will try E_ALL & ~E_DEPRECATED & ~E_STRICT. Maybe that helps?

**Comment by trob** [comment]
~E_DEPRECATED should not switch off notices and warnings

https://www.php.net/manual/en/errorfunc.constants.php

**Comment by joomlahenk** [comment]
OK, then I stay with PHP8.0

**Comment by trob** [comment]
?? With E_ALL & ~E_DEPRECATED you should see all notices and warnings.

**Comment by joomlahenk** [comment]
OK, remove that line and try again.

**Comment by joomlahenk** [comment]
I set: E_ALL ^ E_DEPRECATED, so now I don't get deprecate warnings, but still all other errors/warnings.
So I can switch to 8.1
However, the deprecations need to solved some time.

**Comment by skurvish** [comment]
Fixed with PR #241
