### ISSUE TITLE
Improve loading of scripts

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#22]
We need to load scripts in all views,  jQuery, FabrikHelperHTML::formvalidation(); and JHTML::_('script','system/multiselect.js', ['relative' => true]);
Better we use one helper file for all and / or use the WebAssetManager to load scripts instead

**Comment by trob** [comment]
Any idea how we get the tooltips back?

 J!4 displays (some of) the old tooltips below the input fields (see e.g. breadcrumb module) but this is no solution for Fabrik's heavy "Help tooltips" in the backend forms.

Also the element validation and tips tooltips are missing.

JS is not my field ;)

**Comment by joomlahenk** [comment]
Didn't have time to look at that. But also for me: JS is not my hobby (too much ([{:"@'#$_;}]) )

**Comment by joomlahenk** [comment]
I create a new issue for the missing tooltips

**Comment by skurvish** [comment]
This issue should be about converting the code over to the webAssetManager. Not sure how easy that is going to be as JS is inserted all over the place in Fabrik.

**Comment by skurvish** [comment]
Also Fabrik is using requirejs to manage dependencies. This may actually make it easier because we can take the dependancy rules from the requirejs stuff to build the webassetmanager json file.
