### ISSUE TITLE
Wiki Status of plugins (new)

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#223]
What does "in Fabrik 4" mean
already included in the installer?
should be included but may not be ready?
?

**Comment by joomlahenk** [comment]
Means we update/support this plugin in fabrik 4.0. If you have a better/more clear term please add.

**Comment by joomlahenk** [comment]
I see you removed the old page, I couldn't find how to do that. You added a line on the upgrade page. There is also a page about things to do prior to the upgrade. Should we add that to the upgrade page?

You updated the state of plugins. How do you test these? Frontend or backend? I test in backend only and working also means that input boxes are viewable/editable. This is not always the case if BS5 is not set correct yet. So it may be working in frontend, but I can't use it in backend.
Maybe we need to add an extra column?

**Comment by trob** [comment]
`I see you removed the old page,` I didn't remove anything, what do you mean?
`You updated the state of plugins.` in "elements" I only updated googlemaps and usergroup, both are working in front- and backend.

You marked nearly all list plugins with Fabrik4=Yes.
e.g. inline edit, which is already deprecated in Fabrik3?

BS5: I'm bit lost with all your changes. 
I think the generic (form) templates should set as little as possible. Label positions and then the input default 100% (not things like col-md-6 etc). 
The user can style with element format selections, group layout (group columns), options per row (checkboxes etc), custom CSS which should not be broken by to much pre-settings.
Maybe there are still settings in template_css.php or fabrik.css which will not play well with J!4 and/or BS5.

**Comment by joomlahenk** [comment]
OK, I'm getting a little blind sometimes I guess. I see the old page. I would like to remove it though.

Please mark with 'No' if a plugin is deprecated and add deprecated in remark. I simply made a list of plugins that are in GH and I was not aware of all J!3 deprecations and the ones that don't work in J!3. 
We need to remove deprecated ones from GH. I can also prevent plugins to be installed and remove them before upgrade if they are. 
It would be great if we can make and keep this list up-to-date.

The BS5 changes are intended for backend, the user is not suppose to change those. The input boxes in the forms are not default 100% in the backend. Indeed some may not require BS5 and the ugly old ones could be used sometimes, but there are also some that really need BS5 styling.

**Comment by trob** [comment]
Let's clear the wording.

"Backend" means only the Fabrik admin forms (i.e. list/form/group/element/viz etc settings)? Yes, these are not supposed to be changed by the admins.

But the list/form/details Fabrik templates for viewing/editing the user data, layout of list filters etc. are things which can be modified by the admins, no matter if used in the frontend or in the backend.  So it should be possible to adapt all layout stuff (even if you don't use a BS5 Joomla template) with layout overrides, custom CSS, custom templates etc.

**Comment by joomlahenk** [comment]
Is this the same in the backend for fabrik->lists->view-data ? Or didn't you look at view-data in the backend. I think backend should be BS5, frontend is user template / CSS

**Comment by joomlahenk** [comment]
Yes, I think I have to revert all col-md-* changes for list->view-data. We only need the form-control and form-select, inputbox does not work in BS5. Most col-md-* changes don't work also or give more problems. All input-* were just replaced by col-md-* with no testing. Perhaps we just need to add CSS for .inputbox.input-medium and so on. I will try what can be done in that way.

**Comment by joomlahenk** [comment]
Repaired some files with typo's, col-md-* are working now. Added to have default col-md-6 if not specified. Also added format settings to some plugins.

So I can update the wiki with some working plugins. Continue testing more plugins.....
