### ISSUE TITLE
Empty plugin folders fabrik-element and fabrik-list not removed on uninstall

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#224]
../plugins/fabrik-element is not removed because it contains file index.html 
../plugins/fabrik-list not removed because it contains files index.html & .gitignore
They are there in GH repository. So if you copy-paste all plugins, you will have those and the folders are not removed.
No idea why these files must be there, can they be removed?

**Comment by trob** [comment]
index.html is usually there to prevent folder/file display. I assume this can be handled in the install/uninstall and/or xml files.

I think the .gitignore can be removed.

**Comment by joomlahenk** [comment]
Yes, but index.html should not be in those folders. It's not in the other plugin folders.

**Comment by trob** [comment]
index.html is in all plugin folders and handled in the plugin's xml files.

I assume the ones in the "parent" folders fabrik_element and fabrik_list can be removed. But when/where are they created?

**Comment by joomlahenk** [comment]
I have no idea when/where they were created. Maybe Alex has?

**Comment by joomlahenk** [comment]
I removed these files from GH. See what happens.
