### ISSUE TITLE
Move override files params.php & list.php to 'override' folder.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#225]
After upgrade J!3 -> J!4 and fabrik 4.0 install:
Override files params.php & list.php are not removed from administrator/components/com_fabrik/layouts.
As I understand in the install script they should have been removed after copy to ../templates/atum, but they are not.
Maybe you can move instead of copy?

In administrator/components/com_fabrik/layouts/joomla/form there is a file renderlabel.php. This file must stay as it is used by fabrik.
Is there a reason to put it in the ../joomla/form folder? Can this also be in administrator/components/com_fabrik/layouts ?

renderlabel.php is indeed a layout type file, but params.php & list.php are not; they are override files.
Can we put them in a different folder like: administrator/components/com_fabrik/overrides ?
We can then remove this folder after upgrade.

It's very confusing to have these files together in same layouts folder.

**Comment by skurvish** [comment]
I have no problem moving the 2 template overrides but they need to be copied and not deleted. During the installation they are placed in the then current admin template. If the user changes the admin template they need to have instructions on how to copy these template overrides to the new template.

I can move them to an overrides folder if you wish.

**Comment by joomlahenk** [comment]
OK, please move them to 'overrides'.

**Comment by skurvish** [comment]
Fixed with PR #235
