### ISSUE TITLE
Please test: Fabrik upgrade install script updated. 

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#226]
I updated the install script:
Users no longer need to delete old sql update files and add 3.10.sql.
Fabrik extension and plugins are no longer enabled after upgrade, install and update (except fabrik library).
Removed /components/com_fabrik/com_fabrik_skeleton and /components/com_fabrik/jhelpers
Removed old J!3 overrides in /components/com_fabrik/classes

I tested several times with success, but you never knows....

**Comment by skurvish** [comment]
Any particular reason you are not enabling the plugins? I think you need to at least enable the fabrik system plugin or you cannot access the fabrik admin interface.

**Comment by skurvish** [comment]
I tested this yesterday and without the system plugin being enabled you cannot access the fabrik admin.

Again, what was the reason for not enabling any plugins? Presumably any installation after the first will want existing enabled plugins to be enabled. Forcing the admin to go through and manually enabling the plugins they want seems a bit onerous.

**Comment by joomlahenk** [comment]
Reason: On upgrade the user has disabled all fabrik or the upgrade will crash. So after upgrade and fabrik install all should still be disabled. The install instruction says that the user has to enable at least com_fabrik, system, etc... Depending on how many plugins we are going to add in the package, there may be a lot of plugins that will never be used and need not be enabled.
Of course we can choose to enable all, but then that must include com_fabrik also (it was not). I just found it better this way and give the user all control.

**Comment by trob** [comment]
Some points:
I would prefer a Fabrik4-core package (similar to Fabrik3), only the essential plugins (but these enabled on install).

`there may be a lot of plugins that will never be used and need not be enabled` So why to install them at all? It's only producing unused files and folders, disk space and maybe security issues (it doesn't matter if a plugin is enabled or not if it contains "bad" code). Updates must be done on every unused plugin also (->security)...

It's then up to the user to install and manage additional plugins/libraries etc.

**Comment by skurvish** [comment]
I agree. In fact the way the grunt package builder is designed it builds a package with the same plugins as for F3. We may need to reduce that if some plugins are not working.

Note, if user updates from github then they get all plugins. We may wish to drop some plugins from the repo if we know we are not going to ever support them.

**Comment by joomlahenk** [comment]
The new status of plugin page I made on the wiki is just for that. You can mark plugins to be required, popular, optional or whatever. My guess is then to have the required and popular ones in the standard install package.
