### ISSUE TITLE
Filter options -> filters: only status filters are working

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#25]
The form filter in groups and the filters in elements don't work.

**Comment by trob** [comment]
It's in administrator\components\com_fabrik\forms\filter_elements.xml etc.
Filters are populated and working with
`		<field
			name="form"
			type="formlist"
			label="COM_FABRIK_SELECT_FORM"
			onchange="this.form.submit();"
			>
			<option value="">COM_FABRIK_SELECT_FORM</option>
		</field>

		<field
			name="group"
			type="grouplist"`
(then running administrator\components\com_fabrik\models\fields\grouplist.php etc.)
But for pluginlist.php are some settings missing (you can force populating element plugins with `$group    = 'fabrik_element';//(string) $this->element['plugin'];`) and form selection won't restrict groups
So I assume the original type="list" did it, but I don't know where to find it.

**Comment by joomlahenk** [comment]
Working perfect now.
