### ISSUE TITLE
Validation plugin areuniquevalues settings max to the right

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#250]
The settings form for the areuniquevalues validation plugin is max to the right. Unable to use. Could not find where this is set. All other validation plugins are ok.

**Comment by skurvish** [comment]
I will have a look at it quickly. I need to do some work on my production site tomorrow morning so may not get this done before I go.

**Comment by trob** [comment]
I see what is happening: there's some additional 
<b>...</b>after the legend, which has display:inline; as default
If you delete it (or set it to display:block;) the rest is ok.

But where is this text coming from?
![grafik](https://user-images.githubusercontent.com/1045355/186445361-df97b835-5b23-42cf-955c-75e0d96c6bd0.png)

**Comment by trob** [comment]
Ok, obviously it's the HTML <br/> in the legend text.
It's the same issue with other plugins if you add HTML there.
So I assume the legend text needs some sanitation

**Comment by trob** [comment]
It's not HTML in general but only the `<br>`

**Comment by joomlahenk** [comment]
Great discovery, is working now. I overlooked that one, didn't expect it to be there. B.t.w. It's there in the fabrik3.10 and working ok. They want to have 2 separate lines of text. I will change all other language files also.

**Comment by trob** [comment]
Solved at the moment with https://github.com/joomlahenk/fabrik/pull/253 etc.

Maybe we can add some defensive code for putting text in <legend>
(HTML like <b> is working there, is <br> forbidden inside <legend>?)

**Comment by joomlahenk** [comment]
The issue does not appear again, so I think we solved it for now. At least we now know how to repair this may the issue happens again.
