### ISSUE TITLE
CCD layout

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#251]
Found and interesting anomaly for CCDs. Fabrik created a row layout for the selections of the CCD and populates the CCD with these elements via ajax once the watch element changes. The anomaly is that it only creates one layout so if one CCD is rendered as a dropdown, all other CCDs on the form are rendered the same way. You cannot have one CCD as a dropdown and another as checkboxes for example.

I have not tested this in J3 but it looks to me that this is the way it worked there.

Do we see this as a problem?

**Comment by trob** [comment]
You mean a multiselect CDD in both cases?

**Comment by skurvish** [comment]
OK, so on further inspection the CCDs are not all rendered as the same type. Each type is rendered separately, however, the colsPerRow and bootstrap_class are only used from the first CCD of a particular type on the form. So if you have 2 CCDs of type checkbox, both of them will use the same number of colsPerRow and the same bootstrap_class. For dropdowns they will all use the same bootstrap_class.

I don't see an issue with the dropdowns, most users I think would want them all the same size, however, there may be cases where having them all the same size eats up a lot of real estate on the page.

So for now I am leaving it as is, but open to further comment from you both.

**Comment by skurvish** [comment]
> You mean a multiselect CDD in both cases?
Not necessarily. Any CCD layout.

**Comment by joomlahenk** [comment]
Great work, I think this took some hours. This one was a pretty complicated element plugin, others are hopefully less complicated. Still just a few element plugins to go.
Small issue left though. If I leave CCD empty I get: 1366 Incorrect integer value: '' for column .....`ccd_nm` at row 1
The ccd_nm column is an integer, so the default should be 0 (in this case)

**Comment by skurvish** [comment]
Where are you finding this column? I don't see it in the element.

**Comment by joomlahenk** [comment]
This is a column I create in a table. This is how CCD works and how I set it up to do; it does store a value in a table. 
So you don't need to search for this column. It is just when you have correctly created a CCD, in the form you normally select a value, but in this case I did not.

**Comment by skurvish** [comment]
So this is not something I need to do then? If not then let's close this issue.

**Comment by joomlahenk** [comment]
Well it's the same issue we had with many other element plugins and changed the default value s for those.
But you can leave it: if it occurs, then the user needs to add a validation plugin to prevent an empty value.
