### ISSUE TITLE
Plugins with SQL installed in package don't uninstall tables

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#254]
If a plugin is in the install package and that plugin installed a table(s) using SQL, then J!4 does not uninstall the created table(s).
The created table(s) will only be uninstalled if the plugin was installed separately (not being part of a package).
You need PMA to drop these tables (if you want to). If not the same table(s) including content will be used on re-install.

Or can we find a way to have J!4 to uninstall those tables anyway ?

**Comment by trob** [comment]
I think those tables shouldn't be uninstalled (= deleted) at all, at least not in general.

E.g. the #_fabrik_comments tables contains user data (the comments) "belonging" to the user lists, same with tags etc.
