### ISSUE TITLE
Issue in J!4.2.2 when loading admin/classes/FormField.php to allow for repeatable elements

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#259]
In the fabrik system plugin fabrik.php:97 administrator/components/com_fabrik/classes/FormField.php is loaded.
classes/FormField.php causes an issue in J!4.2.2: Call to undefined method Joomla\CMS\Form\Field\MenuField::getDatabase()
This is because they changed Factory::getDbo() to $this->getDatabase.
We may need to change the way to implement the override classes/FormField.php.
If I comment-out fabrik.php:97, then FormField.php is not loaded solving the issue in J!4.2.2.

**Comment by joomlahenk** [comment]
OK, found what was causing the issue with FormField. All J!4.2.2 changes need to be in classes/FormField.
I updated FormField for J!4.2.2, solving the issue. I will add version update again for this one before merging, because not all of us are on J!4.2.2.

**Comment by trob** [comment]
I think this is why Fabrik3 has all these /classes/xy folders, for each J! version some extra stuff...

**Comment by joomlahenk** [comment]
Yeh, just fixed it and merged. We're having these /classes/xyz folders again. See admin/classes and plugins/system/fabrik/fabrik.php:69

**Comment by trob** [comment]
The disadvantage of such "fixed" folders per version is that you need a new Fabrik version for each Joomla version even if FormFields hasn't changed.
But I don't have a clever idea at the moment.

**Comment by joomlahenk** [comment]
Don't need to do that for each version, only if it changes. I can make it load the 4.2.2. FormField for version >= 4.2.2 for now. If we need a different FormField for a  later version, we can change / add a condition for that. 
The problem is that they will never inform if FormField has changed. We need to monitor the J! PR's. Let's wait and see what will change in J!4.2.3 and following.

**Comment by joomlahenk** [comment]
@skurvish : that would be a nice feature we may implement later. For now it's working like in fabrik3.10
