### ISSUE TITLE
Standard joomla files deleted on uninstall of fabrik4

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#260]
Standard joomla folder ..\administrator\templates\atum\html\layouts\chromes and ..\administrator\templates\atum\html\layouts\status.php are deleted on fabrik uninstall.
templateOverride uninstall deletes folder ..\administrator\templates\atum\html, but should delete ..\administrator\templates\atum\html\layouts\joomla

**Comment by skurvish** [comment]
The uninstall only deletes these if they are empty. It can be easily changed to not delete them if that is preferred.

**Comment by joomlahenk** [comment]
No, that's not what I mean. It should delete files that were installed only, not any others. the folder ..\administrator\templates\atum\html\layouts\joomla is not empty, this is where the installed files are that should be deleted on uninstall. This folder is created on install.

**Comment by joomlahenk** [comment]
In order to make the overrides work I already updated on line 386 and 390 in pathParts 'overrides' changed to 'layouts'
Then on line 437 $pathParts = Array ( [0] => edit [1] => joomla [2] => layouts [3] => html ). This is causing deleting:
0 = /var/www/html/joomla422/administrator/templates/atum/html/layouts/joomla/edit
1 = /var/www/html/joomla422/administrator/templates/atum/html/layouts/joomla
2 = /var/www/html/joomla422/administrator/templates/atum/html/layouts
3 = /var/www/html/joomla422/administrator/templates/atum/html
Also deleting always occurs even if I put a test file in on of the folders (folder is not empty)

For now, I will comment-out the deletion of these folders.

**Comment by skurvish** [comment]
That is odd, I definitely tested this with other files present and the folders were not deleted. I will review on my return.

**Comment by skurvish** [comment]
Fixed with PR #278 

Note, this might delete the html directory but that is not a huge issue. It would have to be empty to get deleted. If it is deleted any knowledgeable site admin would know to create it if they needed to add a template override, which rarely happens with admin templates.

Closing this issue.
