### ISSUE TITLE
Save, edit link and unlink does not work in related elements

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#261]
Console error on opening related element:
Cannot read properties of null (reading 'setStyle')
minified: mootools-core.js:144
readable: mootools-core.js:3178

Console error on save related element:
Cannot read properties of undefined (reading 'canSaveForm')
http://192.168.178.23:8091/joomla4/administrator/index.php?option=com_fabrik&view=element&layout=edit&id=56

**Comment by trob** [comment]
I think the element admin form is missing "Fabrik structure".
Fabrik3 has a HTML id="elementFormTable" which is set to opacity:0 and which is missing in Fabrik4
![image](https://user-images.githubusercontent.com/1045355/189182862-5536c55c-6c10-4dc5-b1c7-e964881a8cb9.png)

**Comment by trob** [comment]
https://github.com/joomlahenk/fabrik/pull/263
