### ISSUE TITLE
Call to undefined method PlgFabrik_FormAutofill::get()

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#262]
Trying to use form plugin autofill.

Call stack (first 3)
1	()					                                JROOT/components/com_fabrik/models/plugin-form.php:478
2	PlgFabrik_Form->formJavascriptClass()	        JROOT/plugins/fabrik_form/autofill/autofill.php:95
3	PlgFabrik_FormAutofill->onAfterJSLoad()	JROOT/components/com_fabrik/models/pluginmanager.php:691

**Comment by trob** [comment]
Try to revert [Cheesegrit's ](https://github.com/joomlahenk/fabrik/pull/217)
https://fabrikar.com/forums/index.php?threads/has-anybody-noticed-issue-with-autofill-plugin-on-new-records.53409/

My "it's working on my site" was without this new commit. It is NOT working, not sure if Hugh missed to put something into GitHub.

**Comment by joomlahenk** [comment]
I just tried that, but doesn't help for this issue. 
If I change PlgFabrik_FormAutofill::get() into PlgFabrik_FormAutofill::getName(), I can make it work but I don't know if that has other implications.

**Comment by trob** [comment]
`getName()` returns 'PlgFabrik_FormAutofill' but it's looking for 'autofill' (to create the script path).
I think it must be $this->_name 
Then it's loading autofill.js - then running into 'parseerror'.
I have to go now, looking at this later (if you don't)
