### ISSUE TITLE
autofill form plugin: Confirmation alert keeps popping-up

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#265]
Doesn't save 'Autofill confirmation'  setting.
Confirmation altert is showing up twice.

**Comment by trob** [comment]
Settings issue was because of FArrayHelper::getValue() was setting all 0 to NULL (I didn't run the latest GitHub :( ).

Lookup  in autofill.js is running twice (triggered by ??) but this is only "visible" if confirmation is on.

**Comment by joomlahenk** [comment]
Is working OK with confirmation off, but with confirmation on it keeps asking for confirmation.

**Comment by joomlahenk** [comment]
I will try again

**Comment by trob** [comment]
Yup, the Cheesegrits commits are not related to this.

**Comment by joomlahenk** [comment]
Just tested in J!3 and I have the same issue. Do we try to repair this or do we remove the confirmation option?

**Comment by trob** [comment]
Maybe some php8 issue then. I'll have a look, too.

In my form the alert closes if you click OK twice, then the autofill is running as expected.

**Comment by joomlahenk** [comment]
I have tested this on J!3 with PHP 7.4. The alert closes yes, but opens again if I want to change the input. So I am not able change.
Maybe I have a different use of it: The Field to observe is the same as Trigger and is a databasejoin element. I don't use the confirmation, but I used this setup for testing.
If you tested this OK in J!4, then let's close this issue.

**Comment by trob** [comment]
`The Field to observe is the same as Trigger`; With this setup I also get an endless alert (in F3) but I don't think this setup makes sense.

**Comment by joomlahenk** [comment]
OK, I think we can close this then.
