### ISSUE TITLE
ajax 'method': 'onXY'

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#266]
In autofill.js
'method': 'ajax_getAutoFill' has to be changed to 'onajax_getAutoFill' to get it working.

But there are more plugins using
'method': 'XY' for calling function onXY()
e.g. in cascadingdropdown\filter.js or image\image.js

Where is 'on' added in Fabrik3?

**Comment by joomlahenk** [comment]
Guess they changed it for fabrik 3.10, because joomla requires all events to start with 'on'. I will check if there are more form plugins like that.

**Comment by joomlahenk** [comment]
Yes, we have more with onXY issue. We need to test and update following:
Form plugins: comment (deleteComment, updateComment, addComment, getEmail), notification (ToggleNotification), paginate (XRecord).
List plugins: caneditrow, canviewrow, order (ajaxReorder). 
caneditrow and canviewrow have exact the same js, which is not correct I think. onCanEditRow is used in js, but onCanEdit is in php.

**Comment by trob** [comment]
What confuses me is that in Fabrik3
autofill.js has `'method' : 'ajax_getAutoFill',`
autofill.php has `public function onajax_getAutoFill()`
and it's working.
So I assume somewhere (pluginmanager?) it's adding the `on` in Fabrik3 and this vanished in Fabrik4?

I don't know how many onXY functions we have and where they are called...

**Comment by joomlahenk** [comment]
Strange indeed. Can be that J!3.10 solves that, because the 'on' is deprecated and J!4 now requires it?
We have many onXY functions everywhere. I found more then previously: in element plugins and visualization.
This cost some time, is there an easy way to test all? Can we just change all to 'on' in all relevant js?

**Comment by joomlahenk** [comment]
Only could find in pluginmanager line 598 function runPlugins: $tmethod = 'onForm' . FabrikString::ltrimword($method, 'on'); 
Don't think this does it, because then we would not have the issue in autofill.

**Comment by trob** [comment]
I think the 'on' should be added here
administrator\components\com_fabrik\controllers\plugin.php  line65 (in public function pluginAjax())
so 
- why not for the autofill?
- and is it doing in the other cases?
No time to investigate futher on today.

**Comment by skurvish** [comment]
Don't confuse the naming of js methods with J! plugin triggers. Most of the js methods are mootools functions and should probably be left alone. If memory serves all J! trigger functions need the 'on' prefix but I could be wrong.

**Comment by joomlahenk** [comment]
@trob : I tested to put a print_f and exit before administrator\components\com_fabrik\controllers\plugin.php line65, but it does not get there although autofill is working. Not in J!3 and not in J!4

**Comment by trob** [comment]
as I've seen in components\com_fabrik\controllers\plugin.phpis the same stuffVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: joomlahenk ***@***.***> Datum: 10.09.22  16:30  (GMT+01:00) An: joomlahenk/fabrik ***@***.***> Cc: troester ***@***.***>, Mention ***@***.***> Betreff: Re: [joomlahenk/fabrik] ajax 'method': 'onXY' (Issue #266) 
@trob : I tested to put a print_f and exit before administrator\components\com_fabrik\controllers\plugin.php line65, but it does not get there although autofill is working. Not in J!3 and not in J!4

**Comment by joomlahenk** [comment]
The 'on' added in administrator\components\com_fabrik\controllers\plugin.php is for element, not for form: $group  = $input->get('g', 'element'); In the js file g = form

**Comment by joomlahenk** [comment]
In ..\controllers\plugin.php pluginManager is called first: $pluginManager->loadPlugIn($plugin, $group);
And then in pluginManager ../fabrik_form/autofill/autofill.php is called
$file = JPATH_PLUGINS . '/fabrik_' . $group . '/' . $className . '/' . $className . '.php';

**Comment by trob** [comment]
`The 'on' added in administrator\components\com_fabrik\controllers\plugin.php is for element, not for form:`element is default only.

I just found the autofill 'on' issue:
while adding 'on' it's also doing ucfirst($method) but in autofill.php it's
onajax_getAutoFill()

So with 
method 'ajax_getAutoFill'
and
function onAjax_getAutoFill
it's doing also for the autofill plugin.

So I think we can close this 'on' issue, controllers are working as they should.

In general I assume the correct way is calling the correct method directly in the ajax call. I assume these 'on' addings are only workarounds to handle already existing calls.

I still don't know why this is doing in Fabrik3, is php7.4 case insensitive for function names and php8 is not?

**Comment by trob** [comment]
I tested with J!3/Fabrik3 on php8. Obviously it's not php8 (functions/methods still case insensitive) so I assume it's J!'s Factory::getApplication()->triggerEvent($method);

**Comment by joomlahenk** [comment]
OK to close the issue
