### ISSUE TITLE
Overloading no longer work in J!4.2.2. Please test.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#267]
List filters were working in J!4.1.5, but no longer works in J!4.2.2. I also get:
Notice: Indirect modification of overloaded property FabrikFEModelList::$_whereSQL has no effect in .../components/com_fabrik/models/list.php on line 3579

Changed all $this->_whereSQL into $whereSQL and added property public $whereSQL = array();
Now list filters work again, but I am not sure if this is a final solution. May cause other issues?

**Comment by joomlahenk** [comment]
Encountered another overload issue:
Notice: Indirect modification of overloaded property FabrikFEModelPluginmanager::$dataModels has no effect in /var/www/html/j4test/components/com_fabrik/models/pluginmanager.php on line 717

To solve this, I added a new property in pluginmanager.php: 	public $dataModels = array();

Seems that overloading no longer works in J!4.2.2. (is bad practice anyway). Do we have(get) more of those?

**Comment by skurvish** [comment]
Your definition of the property seems like the correct approach. The alternative is to test if the property exists and if not set it equal to an empty array, then add the array element to it. i think defining the property is the better solution. As you say, overloading like this is sloppy practice.

**Comment by skurvish** [comment]
Can we close this as we have defined the proper way to solve it should it come up again?

**Comment by joomlahenk** [comment]
OK to close this one, but there may be more overload issues popping-up some time.
