### ISSUE TITLE
'Default error' @ List copy plugin

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#268]
List copy plugin is working, but when setting Default on Copy for element to yes we get 'default error': 1366 Incorrect decimal value: '' for column ... at row 1

**Comment by trob** [comment]
`when setting Default on Copy for element to yes` Where?

**Comment by trob** [comment]
Seems to be ok for field elements.
Which element do you use?

**Comment by joomlahenk** [comment]
I will check again

**Comment by joomlahenk** [comment]
Indeed, now working for field element (format as text)
