### ISSUE TITLE
Lockrow List & Element plugin: user is unable to unlock 

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#269]
TTL Working, but user is unable to unlock. Tested on J!4.1.5 with lock access on 'public' & allow user unlock = yes.
List shows lock when editing, unlockes after TTL. Does not show a key (like J!3 does). Allow re-edit not tested yet.

**Comment by trob** [comment]
It doesn't do at all on my site. The element is showing the open lock in list view but I don't get a `This record is being locked for your use. Nobody else...` message if editing and the record is not locked.
Lasted GitHub, J!4.2.3

**Comment by joomlahenk** [comment]
Did you open it for edit, leave that open (don't save) and open it again?

**Comment by skurvish** [comment]
Should be fixed with PR #339 but please test as I have never used the lockrow functionality before today.

**Comment by skurvish** [comment]
Re open if there is still a problem.
