### ISSUE TITLE
Please update to J!4.2

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#270]
We need to update to J!4.2. I checked for J!4.2 and updates were needed (#267 and #259)
I also implemented (and merged) new features that may not work or cause an issue in J!4.1.5: 
- column select on lists, forms, groups, elements, visualizations, connections, crons 
- toggle inline help for config options

Some time in April 2023 we will get J!4.3

**Comment by skurvish** [comment]
I updates to J!4.2.3 this morning without issue, but I have not tested any fabrik functions on it.

**Comment by trob** [comment]
Just updated to J!4.2.3 + F4 latest GitHub.
At least DomPDF and mPDF on list and form are running without error.
