### ISSUE TITLE
List plugin update_col needs update to BS5

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#271]
Working, but needs BS5 update (PHP-eval & email not tested yet). form-select must be form-select-sm, but I could not found where this is set. (not in update_col.php, update_col.js, fabrik-list-update_col-form.php, fields.xml, fabrikmodalrepeat.php, fabrikmodalrepeat.js)

**Comment by trob** [comment]
as far as I remember update-col is using list filters or advanced filter ( which is creating issues if e.g  a field is set as dropdown filter you won't get a field for input in update col)

**Comment by joomlahenk** [comment]
Found where this is done:
For the update select modal I can not change form-select to form-select-sm in admin\models\fields\listfields.php:141, because that also changes all other fields, we still need to find a solution for that. 
In ..\update_col\forms\fields.xml I succesfully changed the value (to) field and the eval field.
For the User selectable elements select modal I added form-select-sm in admin\models\fields\listfields.php:139, but I am not sure if that also changes any other fields. I checked some (not all) other plugins and I didn't see any issues.

**Comment by joomlahenk** [comment]
For the update select modal I can not change form-select to form-select-sm. I expected to solve this by adding size=-9999, so the override ..\joomla\form\field\list.php change that into form-select-sm, but that does not work.

**Comment by skurvish** [comment]
@joomlahenk if you can walk me through how to set this up to test I will take a shot at trying to fix it.

**Comment by joomlahenk** [comment]
@skurvish : I just set-up a simple list with some filled-in field elements, then add the update_col plugin to the list.
In the plugin settings you will see some select fields that will shoe a modal to fill-in.

**Comment by joomlahenk** [comment]
@skurvish : 
![update_col](https://user-images.githubusercontent.com/40104328/193466943-d41f5742-8ef4-4f9a-b72c-e87ba0e77a75.jpg)

**Comment by skurvish** [comment]
I see the problem. Will have a go at it. Probably tomorrow.

**Comment by skurvish** [comment]
Fixed with PR #291

**Comment by joomlahenk** [comment]
OK, Working now.
