### ISSUE TITLE
All fabrik parts show as "No Compatibility Information"

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#274]
When attempting to do a J! update the extension pre-checker shows all components/plugins/etc as having "No Compatibility Information" and are hence flagged.

The reason for this is that the updateserver file is located on the fabrikar site and has not been updated for J4. For the time being we can create a new update server file and host it in the github repo. I think this can be done using grunt as I think grunt creates the updateserver file and uploads it to fabrikar.com.

I will have to look into this further.

**Comment by joomlahenk** [comment]
Yeh, would be great if you can get this working. They actually wrote some doc about this, see https://docs.joomla.org/Special:MyLanguage/Deploying_an_Update_Server
How would you test this? Create a fabrik4.1 version? Do we want to update from fabrik3.10 to fabrik4.0 (tricky)?

**Comment by skurvish** [comment]
There are a few issues to resolve. First issue is that the fabrikar site url is stored in the #__updateservers table and this will need to change. We might have to do this in the install script. Then we need a place to store the package files so that the update xml file can point to them. I am hopeful something will come out of the discussion with MAT and we can keep the fabrikar domain name and host these somewhere.

I am still looking at grunt. I can see where these are built but I will need to do some testing.

**Comment by skurvish** [comment]
OK, so it looks like the grunt will do what we need. However, the upload site url is hard coded to fabrikar.com. I can create an override for now and maybe use by business hosting site to upload the updated packages and the xml files so the J! updater can query compatibility. I will give this a try and see how it works.

**Comment by skurvish** [comment]
OK, under administrator/components/com_fabrik/update we have a folder called fabrik31. This folder contains all of the update instruction xml files for all of the pieces of fabrik. During the build process these files are copied to the output directory and modified for the new version of fabrik. These files are the copied back to the update/fabrik31 directory and also uploaded the the update server so that J! can check compatibility.

I am going to create a new folder called fabrik4x and for the moment leave it empty. When the build process first runs it will create new update xml files for all of the bits specifically for J4.

Then I think we can dispense with the fabrik31 directory altogether in the repo as this version of fabrik will only ever run on J4+.

Anyone see any issue with this let me know.

**Comment by joomlahenk** [comment]
I don't see any issue with that. Does that mean that J! then sees fabrik 4 as 'compatible', or do you need to do some more ?

**Comment by joomlahenk** [comment]
Great if you can make that working. In case we have more testers/users, they would be able to do an update so we can maintain versions.

Would that then also include the install zip file?.
Most users still need to do the upgrade and have to use the install zip for that. In that case they may end-up with some plugins that are not supported anymore. Those may/should still be marked incompatible.
Or do we decide to update the install script to uninstall those during upgrade?

**Comment by skurvish** [comment]
The install zip I think we can set up as a release on Github here.

i think for the immediate testing phase, rather than make multiple releases, testers should update from github to get the most recent versions. @trob I believe you stated you were able to do that. Do you think you could provide an update script or instructions for the wiki? I assume the wget would have to point to this repo.

As for now we will be doing beta release and it should only be installed on test systems, I think we can set the install script to unpublish all plugins that are not installed with the package. In the post-flight function the install manifest should be available so it should be easy enough to query the plugin manager to get all fabrik related plugins and un-publish all those that are not in the manifest file. We should advise our testers that this is going to happen so they won't be surprised.

**Comment by skurvish** [comment]
The update server issue has now been resolved with PR #277 

We still need to resolve the plugin publishing issues but let's move that discussion to a separate topic as this original issue is now resolved.

**Comment by skurvish** [comment]
Just as a followup, I did change one of the plugins to another version and the update system identified it as an available update so it all appears to be working.
