### ISSUE TITLE
Please test: Updated install script

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#275]
In this update, I added the removal of many 'old' fabrik 3.x files. After an upgrade all no longer used files and folders were still there, occupying a lot of space.
I also (re-)added enabling component and plugins after upgrade or install. For now only required plugins are enabled. Updated wiki for that.

**Comment by skurvish** [comment]
Install works fine on J4.2.3. Some plugins enabled by script. I have not tested any actual Fabrik operations but I am going to close this as complete.
