### ISSUE TITLE
Library issue after update PR #280

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#281]
After update with PR #280, I get:
Failed opening required '/var/www/html/j4fabrik/libraries/fabrik/vendor/composer/platform_check.php' (include_path='.:/usr/share/php')

..\vendor\autoload.php has not been updated.
Maybe composer update must be run? I am not able to run this.

**Comment by skurvish** [comment]
That file is new. Did you do create a new fabrik install and install it after updating to this PR version? That may be why the file doesn't exist. When I create a new package the file is in it and it installs correctly.

**Comment by skurvish** [comment]
Let me look closer. I see in my git repo that the file might be in a gitignore. Will figure it out.

**Comment by skurvish** [comment]
Added missing files in PR #283

**Comment by joomlahenk** [comment]
OK working now, but now it also forces PHP 8.1
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.24. in /var/www/html/j4fabrik/libraries/fabrik/vendor/composer/platform_check.php on line 24
OK if we are we sure that all users / testers of fabrik4 are able to set PHP 8.1.
I still get PHP deprecation warnings from joomla and from fabrik, so could we also go for PHP 8.0 ?

**Comment by joomlahenk** [comment]
Testing PDF: Class "Masterminds\HTML5" not found
<html>
<body>


1 | () | JROOT/libraries/fabrik/vendor/dompdf/dompdf/src/Dompdf.php:477
-- | -- | --
2 | Dompdf\Dompdf->loadHtml() | JROOT/libraries/fabrik/vendor/dompdf/dompdf/src/Dompdf.php:394
3 | Dompdf\Dompdf->load_html() | JROOT/libraries/fabrik/fabrik/Document/PdfDocument.php:280
4 | Fabrik\Document\PdfDocument->render() | JROOT/libraries/src/Application/CMSApplication.php:1017


</body>
</html>

**Comment by skurvish** [comment]
Not sure how easy it will be to downgrade to 8.0 in composer. Whey don't we see if we can fix your deprecated warnings. PHP 8.2 is coming out shortly and 8.3 is not that far behind.

**Comment by skurvish** [comment]
Mastermind is a library that is also git ignored. I had never heard of it but I can add it back in.

**Comment by skurvish** [comment]
Restored masterminds pr #285

**Comment by joomlahenk** [comment]
Library ok for now. b.t.w. Did not help for my PDF issue.
PHP 8.1 is ok, but we may need to mention this in instructions: set Error Reporting on Simple or None.
This is also required for Joomla, because they still have PHP8.1 deprecations

**Comment by skurvish** [comment]
We should do a PHP version check in the install script.

**Comment by joomlahenk** [comment]
And exclude all users with PHP <8.1 ?

**Comment by skurvish** [comment]
Well some of the libraries require it so why not require it overall?

**Comment by skurvish** [comment]
Can we close this then? The PHP check is discussed in another issue.
