### ISSUE TITLE
MPDF does not work => fatal error

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#292]
With the latest github installed if MPDF is selected in the fabrik config:
Fatal error: Declaration of Psr\Log\NullLogger::log($level, Stringable|string $message, array $context = []) must be compatible with Psr\Log\LoggerInterface::log($level, $message, array $context = []) in /var/www/html/joomla4upd/libraries/fabrik/vendor/psr/log/src/NullLogger.php on line 26

**Comment by skurvish** [comment]
Fixed for now with PR #295

**Comment by joomlahenk** [comment]
Working great now! Only strange: MPDF does open PDF in the browser. DOMPDF does not, it downloads PDF.
