### ISSUE TITLE
PHP 8.1 deprecations: Passing null to parameter

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#293]
I get several PHP 8.1 deprecations even with error reporting on system default. They appear only if I open the lists view for the first time:
Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 24
Deprecated: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 96
Deprecated: mb_substr(): Passing null to parameter #1 ($string) of type string is deprecated in libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 94

Now these look J! issues, but thay are not. It's because we use the StringHelper functions and pass a NULL parameter
StringHelper calls functions in the libraries/vendor/joomla/string/src/phputf8/ folder.

I think, in general we should not pass a NULL in any function or we will get deprecation warnings.

This will be hard to fix, because there are many.....

**Comment by skurvish** [comment]
I fixed these in PR #294 There may be more, we will just need to fix them as we come across them. Closing this for now.
