### ISSUE TITLE
Email exists validation not working

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#300]
Tested with: Fail validation when email exists and User Element empty. Does not generate warning if an email is entered that's not in the users table, any value is accepted. If I set Fail validation when email does not exists, then nothing is accepted. I did not try to set a User Element

**Comment by trob** [comment]
It's ok on my site (GH version). Tested exists and not exists and with userelement.

Do you have additionally the juser plugin enabled? In this case don't set validations on password and email, it's done by the form plugin (and may conflict with element validations).

**Comment by skurvish** [comment]
validation works on normal form but on an ajax form the spinner is not getting disabled and hence you don't see the form results. I will see if I can determine why.

**Comment by trob** [comment]
It's ok for me with/without ajax form and with/without ajax validation in front- and backend.
