### ISSUE TITLE
Some datetime deprecations

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#308]
I have list with just internalid, jdate and field element. Looks like Joomla deprecations, but I think fabrik calls these.
We have to solve this some time.

Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/html/joomla4upd/libraries/src/Date/Date.php on line 124

Deprecated: Function strftime() is deprecated in /var/www/html/joomla4upd/libraries/src/HTML/HTMLHelper.php on line 1076

**Comment by skurvish** [comment]
strftime is definitely deprecated and as it is in the Joomla source it needs to be fixed by them.

Need to determine what file in fabrik called the DateTime in the first one.

**Comment by joomlahenk** [comment]
You are right, strftime must be fixed by Joomla. I found the issue on their GitHub.

I tried to track where datetime is called from, but could not find.

**Comment by skurvish** [comment]
Can you tell me what you were doing at the time? The problem with these deprecated notices is that we don't see where in Fabrik the call stack started. if I can replicate it, by understanding how you got there, I can use phpstorm to find the problem.

**Comment by joomlahenk** [comment]
I have a list with only internalid and jdate. I get the warning when trying to add a new record.
All settings on default.
In the console I get:
Fabrik form::addElements: Cannot add element "test___jdate_nm" of type "FbDateTime" because: window[e[0]] is not a constructor

**Comment by skurvish** [comment]
Should be fixed with PR #340
