### ISSUE TITLE
List checkbox not visible in frontend

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#309]
List checkbox visible in backend only, not in frontend. Visibility on/off only working in backend.
Checkbox position left/right working, but then also edit, view and other buttons move left/right (so not only checkbox)

**Comment by skurvish** [comment]
Henk, do you have a picture of this? How to replicate?

**Comment by trob** [comment]
`Checkbox position left/right working, but then also edit, view and other buttons move left/right (so not only checkbox)` That's the normal behaviour.

Checkbox Beginning/End and 'Hide checkbox' are working on my site in frontend.

Are you logged-in in frontend? You'll only get a checkbox if there's something to check: list plugins or you must have delete access.

The only thing not working is "Render buttons" = Dropdown

**Comment by trob** [comment]
`The only thing not working is "Render buttons" = Dropdown`
Just found: this was done intentionally, list.php actionMethod() returns hardcoded 'inline' so ignoring any "Dropdown" setting.

**Comment by joomlahenk** [comment]
@trob You are correct, I set access to delete for public and now it works. Close this one.
