### ISSUE TITLE
calc field result not properly displayed

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#313]
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J4 / F4
When a calc field is displayed in a list, after updating of one of the elements in the calculation in the list's form, the result is briefly shown and then reverts to the old result. Refreshing the page does not help. Only after displaying a different page, and then go back, the new result is permanently shown. F3 has this bug too.

**Comment by joomlahenk** [comment]
Indeed, I can reproduce the issue. I don't have that on my local site running on J!3, PHP8.1.

**Comment by trob** [comment]
I had this in F3, too, in some cases. Some sort of caching...
Is your list ajaxfied?

**Comment by EricdeWaal** [comment]
Yes I use AJAX whenever possible

**Comment by skurvish** [comment]
Fixed in PR #330

**Comment by joomlahenk** [comment]
Is fixed, but only with error reporting on simple. If on system default I get (the correct value, 100, is at the end):

<br /><b>Deprecated</b>:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in <b>/var/www/html/j4test/libraries/fabrik/fabrik/Helpers/Worker.php</b> on line <b>911</b><br /><br /><b>Deprecated</b>:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in <b>/var/www/html/j4test/libraries/fabrik/fabrik/Helpers/Worker.php</b> on line <b>912</b><br /><br /><b>Deprecated</b>:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in <b>/var/www/html/j4test/libraries/fabrik/fabrik/Helpers/Worker.php</b> on line <b>911</b><br /><br /><b>Deprecated</b>:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in <b>/var/www/html/j4test/libraries/fabrik/fabrik/Helpers/Worker.php</b> on line <b>912</b><br /><br /><b>Deprecated</b>:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in <b>/var/www/html/j4test/libraries/fabrik/fabrik/Helpers/Worker.php</b> on line <b>973</b><br />100

**Comment by joomlahenk** [comment]
All these deprecation warnings including the value is displayed as a result in the calc box and only in the backend, not in frontend (with error reporting on system default)

**Comment by skurvish** [comment]
Hmmm, sorry did not test back end. Will give it a look.

**Comment by skurvish** [comment]
Try this PR #333

**Comment by joomlahenk** [comment]
OK, is fixed now
