### ISSUE TITLE
Non-modal form issues

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#315]
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J4 / F4
- you cannot go back to the list after a validation error, even if the error is corrected and the form did save (Record added/updated)
- AJAX validation messages are not really shown (just a flash)

**Comment by trob** [comment]
What do you mean with "Cannot go back": Back button, browser back? Frontend/Backend? All is working on my site.

AJAX validation message: confirmed (I can't even see a flash). It should open a popup.

**Comment by EricdeWaal** [comment]
> What do you mean with "Cannot go back": Back button, browser back? Frontend/Backend? All is working on my site.
> 
> AJAX validation message: confirmed (I can't even see a flash). It should open a popup.

Sorry, I should have expressed myself better. Steps to reproduce:
- open a form from a list by clicking a link
- violate validation (e.g. try to save the record when a "notEmpty field" is empty), record os not saved and a warning is displayed
- correct the error and save
Normally, after saving, the form closes and you go back to the list. In the above case hover, this does not happen. The form stays open.

**Comment by trob** [comment]
;-)
Ok, then it's only the AJAX validation messages.

**Comment by EricdeWaal** [comment]
Closing for now, hope it does not come back!
