### ISSUE TITLE
incorrect feedback on cron scheduled task test run

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#316]
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J4 / F4
In a cron / PHP ("schedule") I put some simple PHP code in the field to update a field in a table. 
That works at the set intervals. 
But in the test run the message says: "0 records updated" while it DID do the update.

And a minor issue: as long as I edit the task, a spinner is visible near the "List" dropdown.

**Comment by trob** [comment]
Identical behaviour to Fabrik3.
You must set the variable $processed in your php code.
