### ISSUE TITLE
some text area issues

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#317]
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J4 / F4
- despite the setting, html tabs like <b> are always stripped out
- no number for Characters left is shown, just the label

**Comment by joomlahenk** [comment]
html tags are not stripped out on my site. I entered `hi, I am  <small>Henk</small>`

![textarea_html](https://user-images.githubusercontent.com/40104328/195638768-50f0d2c0-df19-4a91-8f69-f28fb026ac33.jpg)

Number of chars is displayed, but is small and hardly visible. 
In components\com_fabrik\views\form\tmpl\bootstrap\template_css.php ( between } and "; ) You can add:
.badge {
    color: var(--body-color);
    font-size: 1rem;
}
The file template_css.php will be updated in the next version

**Comment by trob** [comment]
`html tabs like are always stripped out` HTML is working. Check your settings in J! GlobalConfig/Text Filters (As default J! will strip out all HTML for Public and Registered)

**Comment by EricdeWaal** [comment]
> html tags are not stripped out on my site. I entered `hi, I am <small>Henk</small>`
> 
> ![textarea_html](https://user-images.githubusercontent.com/40104328/195638768-50f0d2c0-df19-4a91-8f69-f28fb026ac33.jpg)
> 
> Number of chars is displayed, but is small and hardly visible. In components\com_fabrik\views\form\tmpl\bootstrap\template_css.php ( between } and "; ) You can add: .badge { color: var(--body-color); font-size: 1rem; } The file template_css.php will be updated in the next version

Stupid of me, I should have seen the number of characters is there, on my screen it's white text, but usual size

**Comment by EricdeWaal** [comment]
> `html tabs like are always stripped out` HTML is working. Check your settings in J! GlobalConfig/Text Filters (As default J! will strip out all HTML for Public and Registered)

Indeed when I set GlobalConfig/Text Filters to "no filtering" it works. I had assumed that this was an override of the global settings. Should it not be, actually? now it is a bit confusing

**Comment by trob** [comment]
>  was an override of the global settings
No, J! Text Filters alwyas have priority, this is the same in J!3 and also while editing J! content.

**Comment by EricdeWaal** [comment]
closing issue
