### ISSUE TITLE
missing parts in version: testing_pkg_fabrik_4.0alpha1

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#318]
According to the Alpha Tester Instructions page the following should be included, 
I see them in the zip file but but they were not installed on my system:
elements: cascadingdropdown, colourpicker, display, fileupload, googlemap, image, link, radiobutton
validation: isemail, isgreaterorlessthan

**Comment by skurvish** [comment]
I have updated the install package to install these. I have not updated the download package. For now you can unpack the package zip file and install the missing one manually. Sorry for the extra work.

I will update the wiki with these instructions.

**Comment by skurvish** [comment]
Wiki updated and closing.
