### ISSUE TITLE
Update listfields styling

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#32]
type listfields are used in the settings pages and are now show as a very small selectionbox with no data
see lists->new data, tab data primary-key

**Comment by skurvish** [comment]
The primary key dropdown would be populated once you choose an existing database table. Probably some onchange event is not firing.

**Comment by joomlahenk** [comment]
OK, that's working. Only styling is an issue now. I will change the issue title.

**Comment by skurvish** [comment]
I think you have 2 choices, and @trob can probably tell you better, but if you did not start another branch for your changes then simply commit them and push the changes to your repo. Generally though when you start a new project/fix/etc, create a new branch off of your main branch (henk40). Make your changes to that branch. Once you are happy with them commit them and then push your branch. 

Then in the online repo you can create a PR by comparing your new branch to the master branch (henk40) and if all is good you can create the PR. Then decide if it needs to be reviewed or not. if not then just merge it.

**Comment by joomlahenk** [comment]
OK, this is solved. However there are some more input boxes that need re-styling.
