### ISSUE TITLE
Some more Deprecations: Passing null to parameter

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#322]
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/html/j4test/libraries/fabrik/fabrik/Helpers/Worker.php on line 911 and on more lines

**Comment by skurvish** [comment]
Henk, need some context as to when this is happening as we need to find the caller. If I can find who is calling the string function in the Worker I can fix it.

**Comment by joomlahenk** [comment]
You're right. It occurs when using a calc element with `$a = intval('{test___field_nm}');
return $a/2;`.

**Comment by skurvish** [comment]
Fixed with PR #330

**Comment by joomlahenk** [comment]
Is not fixed on my site. See also #313

**Comment by joomlahenk** [comment]
I changed to medium priority, because I get a screen full of these warnings with error reporting on system default.

**Comment by skurvish** [comment]
Please retest with latest PR.

**Comment by joomlahenk** [comment]
OK, fixed now
