### ISSUE TITLE
AJAX validation messages

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#325]
Showing only an alert icon (and HTML text on hover).
Needs to be converted to BS5 tooltip/popover and BS5 red/green border.

**Comment by joomlahenk** [comment]
Is this the same behavior as in #314 ?

**Comment by trob** [comment]
I think so, it's the same code
![grafik](https://user-images.githubusercontent.com/1045355/195843240-a4421b32-b212-4e7b-a6f5-02292eae893e.png)

But I really would prefer to have the validation messages inline below the field (as in non-modal forms), there have been discussions in F3.
What do you think?

BTW: Tooltips on labels are not working in ajaxfied forms, I think this was doing at some point before...

**Comment by joomlahenk** [comment]
Yes, I prefer the validation message on the same location in modal and non-modal forms. I see in J!3 in a modal it's in the validation tool-tip and in a non-modal it's below the field.
In J!4 in a modal no validation message is displayed. However, I can see the text to display below the field in the HTML code and I see no CSS setting that prevents it to display. So something in JS prevents it maybe?

![validation_message](https://user-images.githubusercontent.com/40104328/195852192-509d4a0e-a5ac-425a-b4d7-49ed69a5c628.jpg)

The validation tool-tip is displayed on hover over the eye, but then HTML tags are stripped.

**Comment by trob** [comment]
See https://github.com/joomlahenk/fabrik/pull/329

**Comment by joomlahenk** [comment]
OK, solved on my site.
