### ISSUE TITLE
Fabrik update does not work.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#328]
Since the Fabrik Admin Form Module & Fabrik Admin Visualization Module are updated and a new version is added. These modules now appear in the joomla extension update. Which was expected, but they cannot be downloaded.

![module_updates](https://user-images.githubusercontent.com/40104328/195844393-aa8ed068-2d81-4520-ae0b-8fc5ea9893a4.jpg)

**Comment by skurvish** [comment]
I have not uploaded the actual zips to the server. For the time being I will just keep the full install package.
