### ISSUE TITLE
Delete button in modal form does not work in backend

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#331]
See als #314 item 3.
After using the Delete button, the form does not close still showing the record. After closing manually, the list is not updated automatically and still shows the record.

**Comment by trob** [comment]
Hmm, it's working on my site with
List: ajaxfy=No or Yes, ajax links=yes
I get 2 alerts ("are you sure..." and then "COM_FABRIK_FORM_SAVED") then the popup form is closing automatically + list is updated.

**Comment by joomlahenk** [comment]
Yes, I get the same response in the FRONTEND. Delete is not working in a modal in the BACKEND. I get this in the console:

mootools-core.js:164          POST http://192.168.178.23:8091/j4test/administrator/index.php?option=com_fabrik&task=list.view&listid=1 404 (Not Found)
send @ mootools-core.js:164
e.extend.$owner @ mootools-core.js:38
send @ mootools-more.js:248
(anoniem) @ form.js:3
check @ form-submit.js:3
e.extend.$owner @ mootools-core.js:38
(anoniem) @ mootools-core.js:21
setInterval (asynchroon)
periodical @ mootools-core.js:22
submit @ form-submit.js:3
e.extend.$owner @ mootools-core.js:38
doSubmit @ form.js:3
e.extend.$owner @ mootools-core.js:38
(anoniem) @ form.js:3
m @ mootools-core.js:119
utils.js:3 error in returned json undefined undefined 
utils.js:3 [object XMLHttpRequest]

**Comment by trob** [comment]
Strange.
On my test site (GitHub) I don't get a modal form at all in the backend.

I just did a vanilla J!4 + F4 (download zip) install.

There I get the popup form but with
Warning: Array to string conversion in C:\xampp8\htdocs\j4f4install\libraries\fabrik\fabrik\Document\Renderer\Partial\HeadRenderer.php on line 248
and I see the behaviour (popup stays open, record not deleted in list), no matter if list is ajaxfied or not.

But in the network response you can find
An error has occurred.
404 View not found [name, type, prefix]: fabrikadmin, raw, fabrikadminView

Edit is ok in the backend.
Edit and delete ok in the frontend.

**Comment by joomlahenk** [comment]
As far as I can see: fabrikadminView does indeed not exist. We do have fabrikadminViewList, fabrikadminViewForm, etc. Or maybe this should be fabrikView ? 
I could not find where this is called from

**Comment by trob** [comment]
It's the same in F3.

**Comment by joomlahenk** [comment]
OK, this issue is solved if we prevent a modal form in the backend, as in J!3. 
Only "COM_FABRIK_FORM_SAVED" may need to be looked at.

**Comment by joomlahenk** [comment]
Created new issue to solve this, see issue 389
