### ISSUE TITLE
jdate element datepicker pop-up is not shown in a modal

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#332]
See also #314 item 4.
The jdate element datepicker pop-up is not shown in a modal on the frontend

**Comment by trob** [comment]
It doesn't load the calendar (on form load), so nothing to open.
There should be a
<div class="js-calendar"....
Maybe because of
Fabrik form::addElements: Cannot add element "atest2___bis_jdate" of type "FbDateTime" because: window[el[0]] is not a constructor

**Comment by joomlahenk** [comment]
Still not fixed after PR #361

**Comment by skurvish** [comment]
PR #361 had noting to do with the calendar popup. It had to do with correcting the console error.

**Comment by joomlahenk** [comment]
@skurvish: OK, I thought it might.

**Comment by joomlahenk** [comment]
@skurvish: to open a modal in the frontend: in backend goto edit or new list => details =>tab Links => Ajaxify links = yes
To edit or new record the form should display in a modal on the frontend (not on the backend). For jdate the datapicker is not displayed when in a modal.

**Comment by skurvish** [comment]
Looks like a number of elements are not rendering properly on the ajax modal in the front end

**Comment by joomlahenk** [comment]
The date element date and time picker pop-up's are shown in a modal on the frontend

**Comment by skurvish** [comment]
Should be fixed in PR #409 

Note, there may be other elements that will require similar changes. if you find any let me know.

**Comment by joomlahenk** [comment]
Reverted PR#409. jdate did not work in modal anymore (did you test this?)

**Comment by skurvish** [comment]
Yes this was tested and @trob has verified it works. Please revert your revert and if you are having problems I will look at them.

**Comment by joomlahenk** [comment]
Tried with PR#409 merged once again, but I can't get a modal to work if jdate is used:
I always start a test by making sure the browser cache is cleared, so no old js and css are used.
I have a list with only elements: id, field (integer), calc on ajax (=field/2) and jdate (default to current date = yes)
For the list: ajaxify links = yes
Result in backend (in modal):
add record => calc does not work, date is on todays date, datetime pop-up not working, goback not working, save not working, delete not working and the I have a crash displayed {"msg":"Record added\/updated","url":"index.php?option=com_fabrik&task=list.view&listid=1","baseRedirect":true,"rowid":"12","suppressMsg":false}
Same result in frontend.
The form was working before PR#409.

**Comment by skurvish** [comment]
OK, please leave as is while I test on my machine.

**Comment by skurvish** [comment]
It is working correctly for me on the front end. I do see some issues on the back end. Looking at that now.

**Comment by skurvish** [comment]
OK, jdate and yes/no should display correctly now with or without modal. I have also fixed the read-only rendering. If anything is still not working please let me know with full details on how to replicate.

I am not happy with the modal display in general, it does not seem to be handling the label positions in the detail view properly. I hope to be able to look at that tomorrow.

**Comment by joomlahenk** [comment]
Still not working here. What do I need to do to get it working like you have ???

**Comment by trob** [comment]
@joomlahenk: 
Can you merge the last PR so that we all have an identical GH version and not some copy/paste code which may be different?

**Comment by skurvish** [comment]
Yes, I am keen to see if it works or not for @trob if it does it will be interesting to discover what is different as other users may have the same problem.

**Comment by joomlahenk** [comment]
Now I have 2 sites each in it's own browser (chrome incognito mode) Each have the same list with only internalid and jdate.
1: One site has the 'old' jdate.php where the form with jdate is working (accept calendar pop-up).
2: The other site has the 'new' jdate.php with the update with the latest PR's where the form is not working.
The difference I see: On the first site (1) jdate-min.js is loaded, on the second site jdate-min.js is NOT loaded.
So the issue may be that jdate-min.js is not loaded. You may not discover this if the browser you use has cached jdate-min.js.

**Comment by skurvish** [comment]
In your browser on the failing site, on the network tab is this file showing as being fetched and did it fetch OK? Clear the network tab before you open the modal. If it did not fetch OK what path is it trying to find it? Perhaps @trob latst PR with JUri::root might fix it?

**Comment by joomlahenk** [comment]
I get following on the network tab on opening the modal form in the frontend:
Working J!3 site:
![j3-site](https://user-images.githubusercontent.com/40104328/197747353-efe4a32a-3ad9-4e04-9d4a-62a4c2673104.jpg)
Working J!4 site:
![not-failing-site](https://user-images.githubusercontent.com/40104328/197747536-2f8b27db-8719-4445-87b3-de2e8746cba1.jpg)
Failing J!4 site:
![failing-site](https://user-images.githubusercontent.com/40104328/197747642-1f8bc8c8-34d4-44ba-aa01-45ab1ccdfc6c.jpg)
I get a bunch off console errors on the failing site too.

**Comment by skurvish** [comment]
If you hover your mouse over one of the items in red, what is the url it is pointing to?

**Comment by skurvish** [comment]
And are those files present?

You might consider merging @trob 2 PRs as they make sure the root path is correct for the specific J! install.

**Comment by joomlahenk** [comment]
Yes these are standard Joomla and are present. Like I already told: I use the 'new' jdate.php with the update with the latest PR's, meaning PR#409 INCLUDING @trop's PR's. This file is 87795 bytes.

![jdate php](https://user-images.githubusercontent.com/40104328/197752367-e9c9965a-f887-455c-8d5d-2f7f9324e40e.jpg)

**Comment by skurvish** [comment]
OK, but the files are being requested but are not being fetched. This looks to be a problem with either the URL being used for the fetch or perhaps a permissions issue on the particular site. These work correctly for @trob and I so I have to assume it is something on your site. It would be good to figure this out as others might have the problem.

? are there other files being fetched from the same directory /media/system/js that are fetching correctly?

**Comment by skurvish** [comment]
Also, the code above is not the code in @trob PR, there should be a JUri::root ahead of the '/media/system...' for $jsloc and $cssloc

please check you copied the most current files.

**Comment by skurvish** [comment]
I don't see the 2 PRs from @trob being merged. You should do that and restest.

**Comment by skurvish** [comment]
They are the only 2 PRs showing on the Pull Request tab of the repo. They are 419 and 420

**Comment by skurvish** [comment]
Why are you closing these PRs?? I give up, fix this yourself.

**Comment by joomlahenk** [comment]
No not yet. Only 420 deals with jdate. I asked (again) to split 420 into PR for jdate and PR for yesno.
I will change jdate.php on my site as in PR 420 to see what that brings.
Seems we are switching /media/system/js/fields/ to media/system/js/fields/ back again

**Comment by joomlahenk** [comment]
Yes the jdate.php as in PR 420 is working ok now. Please create a separate PR to ONLY add this file.
Merged PR 419 Now I can start testing yesno plugin.

**Comment by joomlahenk** [comment]
I will merge this file now myself, no need to create a new PR.
