### ISSUE TITLE
googlemaps element issues

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#335]
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J 4.2.3, PHP 8.1.11

1. Geocoding "Enable Geocode" should be a dropdown with 3 options: No, Yes, Use elements

2. Geocoding does not work. 
Select a field for formatted address, or use individual fields for Street, City, Country etc.
Select "Trigger geocode with" either "Button" or "As you type".
The location marker is never positioned to the set address.
(I believe it was already broken in J3 some time ago, worked previously)

**Comment by skurvish** [comment]
If it was broken in J3 then we likely won't place a high priority on fixing it.

**Comment by trob** [comment]
Dropdown options should be fixed with https://github.com/joomlahenk/fabrik/pull/341

Geocoding is working.
Do you have a valid Google API key set in Fabrik Options? I think since ??? you must  have geocoding enabled in your Google API account + you must provide a valid credit card etc.

**Comment by trob** [comment]
Tested with Geocode Yes/use elements, Trigger=Button and 'as you type', all is ok.
I'll close this. You can always re-open.

**Comment by EricdeWaal** [comment]
Now in version Alpha 2 it works. And yes, I have an API key (made in 2019, that must have been the start of that Google requirement). I added my testing domains to the key, and it worked because the map was not blurred or greyed out anymore.
But geocoding only started to work in Alpha 2.
