### ISSUE TITLE
link element: open in mediabox does not work

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#338]
Version: testing_pkg_fabrik_4.0alpha1 tested on plain J 4.2.3, PHP 8.1.11

It opens in a new tab instead.

**Comment by joomlahenk** [comment]
What do you mean by "open in mediabox" ? I don't see a mediabox setting.

**Comment by EricdeWaal** [comment]
The settinf is in Options > Link target. If you select Media box, it opens in a new tab

**Comment by skurvish** [comment]
Eric, do you have a picture of what it should look like?

**Comment by trob** [comment]
Enable "Mediabox"(or something != Slimbox) in Fabrik Options/JavaScript.

I don't know what JS is loaded exactly, but it seems we should at least remove the Slimbox option.

**Comment by trob** [comment]
[getLightboxAttributes](https://github.com/joomlahenk/fabrik/pull/376)

**Comment by EricdeWaal** [comment]
> Enable "Mediabox"(or something != Slimbox) in Fabrik Options/JavaScript.
> 
> It seems the default Slimbox2 is no working (components\com_fabrik\libs\slimbox2\js\slimbox2.js says '... 2007-2013...'), I assume it needs an update.
> 
> libraries\fabrik\fabrik\Helpers\Html.php::slimbox() only uses Slimbox (if selected in Fabrik Options) or Mediabox (in all other cases), so the additional options Rockbox and Lightcase don't make sense.

Mediabox works. Indeed Slimbox2 is quite old and seems not to be maintained anymore, it's latest version is v2.05 (2013-05-07).
I suggest to remove Slimbox2 completely and add a line in the upgrade script to change user setting2 to Mediabox.
