### ISSUE TITLE
Fatal error trying to add a new element

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#342]
Just trying to add a new element. This happens since latest GH update: 
Failed opening required '/var/www/html/j4test/plugins/fabrik_element/radiobutton/radiobutton.php' (include_path='.:/usr/share/php')
I have no radiobutton element in the list.

**Comment by trob** [comment]
It's ok on my site.
Do you have ....plugins/fabrik_element/radiobutton/radiobutton.php ?
What happens if you disable the plugin?

**Comment by joomlahenk** [comment]
I don't know what happened. I do an uninstall and then a reinstall => all ok.
Then I do a copy from GH, so I get all plugins. Discover to install all plugins and enable all => all ok
So I close this.
