### ISSUE TITLE
Fabrik alpha2 install error

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#344]
Package Install: There was an error installing an extension: plg_fabrik_element_ccolourpicker_4.0alpha2.zip

**Comment by skurvish** [comment]
spelling error. I will fix.

**Comment by joomlahenk** [comment]
Typo ?
plg_fabrik_element_**c**colourpicker should be plg_fabrik_element_colourpicker I think

**Comment by skurvish** [comment]
Fixed with PR #345 I should have the updated package uploaded shortly.

**Comment by skurvish** [comment]
Uploaded and ready. Please check, if OK please close this issue.

Sorry about that, it is a pain for me to test the install as I have to unlink my repo from my J! installation.

**Comment by raramuridesign** [comment]
I got an error trying to install Alpha 2 over Alpha 1. 
- uninstall alpha 1
- install alpha 2

I would need to show the error again, on next package.

**Comment by skurvish** [comment]
@joomlahenk did you see this issue?

**Comment by joomlahenk** [comment]
@raramuridesign: Not clear what error you mean. colourpicker typo ? Did you get the very latest alpha 2 ? Maybe you download  alpha 2 again (it's updated now) and retry.
You will get many uninstall warnings, this is a Joomla issue.
@skurvish: I did exactly the same and have no error

**Comment by skurvish** [comment]
Thanks @joomlahenk Maybe Eric can try it?

**Comment by trob** [comment]
@raramuridesign 
You should never uninstall an existing Fabrik version, you will lose all your Fabrik work in this case.

I just installed the downloaded 4.0alpha2 (downloades 15:15 UTC) over alpha1 without any error.
So closing this issue.

Joomla is even showing alpha2 as avaiable updates (but these are not working)

**Comment by skurvish** [comment]
Yes, but I have not set up the update zips files as of yet. Best to work with complete packages. I will look at setting up the alpha packages as updates.

**Comment by raramuridesign** [comment]
My first install was with Alpha 1 then I installed Alpha 2 over 1. This is when I got an error.
But I ignored it and simply removed the install. I was not concerned with loosing data, since this is only testing at this point.
Hope this clarifies.
