### ISSUE TITLE
[alpha2] admin - Add access control to Tools TAB on HOME

### ISSUE THREAD

**Issue by raramuridesign** [joomlahenk/fabrik#347]
#346 referencing this pull request, if we can add access control to super admins for the tools tab.

**Comment by skurvish** [comment]
Mathew, would you mind assigning yourself to these issues if you plan to work on fixing them? That way none of the rest of us will duplicate your effort. Just click on the Assignees - assign yourself over on the righthand site. Thanks.

**Comment by joomlahenk** [comment]
@raramuridesign: I Reverted #346, because the logo was not displayed. You need to use HTMLHelper::image.
I kept the change for the COM_FABRIK_HOME_TOOLS_TEXT.
Question: What do you mean with "Add access control to Tools" ? Did you mean to change access rights ?

**Comment by raramuridesign** [comment]
The tools tab has functionality that is available to any admin user. 
I suggest that this is only available to Super Admin. ie the entire tools tab and the content.

re #346 I will revisit this.

**Comment by joomlahenk** [comment]
Maybe to implement some time later.

**Comment by skurvish** [comment]
I can see how this might be desirable. Allowing any person with admin rights to reset Fabrik is dangerous. Although given that it has never happened or reported previously probably not a huge risk.

**Comment by trob** [comment]
Strange that this never happens. It IS a huge risk - I just reset my test F4 because I did a right-cklick on the link.
In this case you even don't get the JS confirm box, It's just deleting all.

I have it solved (a big red warning for super admins, no access for all others), need to create a PR later.

**Comment by trob** [comment]
PR https://github.com/joomlahenk/fabrik/pull/516

**Comment by raramuridesign** [comment]
@trob Excellent, this is fantastic.
