### ISSUE TITLE
Provide Upgrade Instructions for J3 -> J4

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#35]
We can use this issue to track what needs to happen.

First thing is the Fabrik System Plugin needs to be disabled prior to upgrading to J4.

**Comment by skurvish** [comment]
Also user custom code should be updated to use the non-fabrik specific classnames. This is a project users can do any time before upgrade.

**Comment by joomlahenk** [comment]
A lot of classnames still work, see the /libraries/classmap.php 
For other classes that changed, see https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

**Comment by trob** [comment]
No!!
You will loose also all your scripts, custom template etc.
And it's not necessary at all, you can install over an existing Fabrik3 installation

**Comment by skurvish** [comment]
`
>   update from GitHub (to get all other plugins)
`
What github would they update from? This will take some work and testing.

**Comment by joomlahenk** [comment]
@trob: Did you try that? I needed to uninstall fabrik, because else Joomla 4.x is messed-up. Your solution looks complicated.
Most users are not used to GitHub. I think I have rather simple instructions anyone should be able to do. I tested several times.

**Comment by trob** [comment]
I did test, yes.

Update from GitHub: This GitHub (analogue to the Fabrik GitHub update)

For https://github.com/joomlahenk/fabrik/wiki/Building-an-install-package  you need to download the GitHub files, too.
And do the build (which requires grunt etc)
It seems to me more complicated then to provide a core Fabrik4 package and then let the user  just copy the GitHub files over the installation.

**Comment by joomlahenk** [comment]
Solved with commit "Working upgrade/install/update/uninstall"
Instructions are now:

1. In J!3: goto administrator/components/com_fabrik/sql/updates/mysql and remove all *.sql files then add an empty sql file with the name 3.10.sql So now you should have only the empty file 3.10.sql in that folder
2. In J!3 goto extensions -> manage -> search for fabrik -> (make sure you selected 'All' in the limit box on the right) disable all
3. Upgrade to J!4. The compatability check will not find fabrik issues.
4. Install fabrik4
5. In J!4 goto extensions -> manage -> search for fabrik ->
enable at least: fabrik-admin, fabrik-package, fabrik-library, fabrik-system and plugins field, internal-id, jdate
