### ISSUE TITLE
[alpha2] admin - group by on list not working

### ISSUE THREAD

**Issue by raramuridesign** [joomlahenk/fabrik#350]
Goto any list
Select group by, choose anything
This redirects back to Joomla Admin

It looks like the groupby is missing an equals and ampersands from the URL builds

```
index.php?optioncom_fabriktasklist.viewlistid1&group_by=apps_contact___name
```

should be

```
index.php?option=com_fabrik&task=list.view&listid=1&group_by=apps_contact___name
```

**Comment by trob** [comment]
Should be fixed with https://github.com/joomlahenk/fabrik/pull/358
