### ISSUE TITLE
[alpha2] admin list view - cannot empty database

### ISSUE THREAD

**Issue by raramuridesign** [joomlahenk/fabrik#351]
Screenshot will clarify

![image](https://user-images.githubusercontent.com/902376/196041131-8288276c-f163-46cc-934f-4e65e27aa1a0.png)

**Comment by trob** [comment]
Ok, it's working like "Add", opening a new form.

**Comment by raramuridesign** [comment]
@trob Not sure I understand the comment. Is this icon not meant to empty the database in its entirety?

**Comment by trob** [comment]
Sorry, I only described the wrong behaviour (so somebody may have an idea how to fix it).

**Comment by skurvish** [comment]
Yes, empty should clear all the records in the selected list.

**Comment by trob** [comment]
Solved with https://github.com/joomlahenk/fabrik/pull/365
