### ISSUE TITLE
F4 J! update not working

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#352]
J! is showing the available F4 alpha2 extensions
![grafik](https://user-images.githubusercontent.com/1045355/196041098-99c03f58-4650-41b1-a98e-d4a90a9b60c0.png)

but the update is not working
![grafik](https://user-images.githubusercontent.com/1045355/196041151-bd8be999-cfb5-44ae-85b6-e52cea0e793f.png)

**Comment by skurvish** [comment]
This is because the packages have not been uploaded to the server. I will see about getting the full package to allow update. Too early for updating single elements.

**Comment by skurvish** [comment]
I have copied the package install to the downloads folder. J! should now find the package update to alpha2.

I am going to pint the wiki to this location rather than the dist location.

**Comment by joomlahenk** [comment]
Duplicate. See #328

**Comment by trob** [comment]
Ok, so closing this one.
