### ISSUE TITLE
[ALPHA2] List in module works now, but still gives warnings

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#357]
Warning: Undefined array key "order_by" in /usr/www/users/prachta/fabrik/modules/mod_fabrik_list/mod_fabrik_list.php on line 136

Warning: Undefined array key "order_dir" in /usr/www/users/prachta/fabrik/modules/mod_fabrik_list/mod_fabrik_list.php on line 137

Warning: Undefined array key "filter-conditions" in /usr/www/users/prachta/fabrik/modules/mod_fabrik_list/mod_fabrik_list.php on line 155

**Comment by skurvish** [comment]
@EricdeWaal can you try this change please?

Change lines 136 and 137 to:
`$orderBy = array_key_exists('order_by', $ordering) ? (array) $ordering['order_by'] : [];
$orderDir = array_key_exists('order_dir', $ordering) ? (array) $ordering['order_dir'] : [];`

and 155 to:
`$conditions = array_key_exists('filter-conditions', $prefilters) ? (array) $prefilters['filter-conditions'] : [];`

And let us know if those warnings go away. Thanks.

**Comment by EricdeWaal** [comment]
@skurvish Yes, that works!

**Comment by skurvish** [comment]
Fixed with PR #359
