### ISSUE TITLE
Modal form sticks to the left

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#367]
Latest GH update:
Open a modal (ajax) form (to add a new record) it opens with maximum width. Then on the backend the modal is fixed to the left. I can size the form from the right, top and bottom. I cannot move the modal. Same thing on the frontend except there I can size from the left.

![modalform-stick](https://user-images.githubusercontent.com/40104328/196173155-8111b5ce-14e5-4ac4-9b42-32885eb0e31b.jpg)

**Comment by trob** [comment]
This is not related to the latest GH, it was so long before (or always in F4).

The modals need some enhancement:
Add forms are to wide, edit/view to small, all are not draggable.

I don't see this warning at the moment but I've seen it before.

**Comment by joomlahenk** [comment]
OK, if I set the modal width, height and offsets it is displayed ok. Still is not draggable.
Maybe we need to set default width, height and offsets ?

**Comment by joomlahenk** [comment]
Issue is solved if we prevent a modal form in the backend as in J!3

**Comment by joomlahenk** [comment]
See issue 398
