### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#37]
So far I have been leaving the merging decisions to @joomlahenk as it is his repo. Is that how you wish it to remain? Or should the 3 of us just go ahead and merge at will. This of course may break some other things or cause merge conflicts in other stuff we are working on, but I think it is more important to get the changes in sooner than later so multiple people are not chasing the same problems.

@joomlahenk @trob your thoughts?

**Comment by trob** [comment]
Do you know how to revert a merge?

**Comment by skurvish** [comment]
My understanding is that a merge cannot be undone. You must simply make another commit that reverts the changes. Is there another way?

**Comment by joomlahenk** [comment]
Let's not make ik more complicated. I got some merging issues already. I will check and merge as soon as I can.
