### ISSUE TITLE
Fabrik4 installation

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#370]
Hi I tried to install F4 package on J!4.2 php8.1 using package installer https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0alpha2.zip via Joomla extension installer.
When I go to publish the fabrik system plugin I get the following error
**An error has occurred.
0 PLG_FABRIK_SYSTEM_AUTOLOAD_MISSING**
I cant visit any admin page afterwards and i have to rename the plugin/system/fabrik dir to allow access to joomla

**Comment by joomlahenk** [comment]
You need to have a 'virgin' installed Joomla 4.2.3 and PHP8.1

First download pkg_fabrik_4.0alpha2.zip.
Then in Joomla goto: system -> install extensions -> upload package file -> browse for file -> open
Fabrik will be installed, this takes some time.
When the installation is completed, you can go to the components menu and select fabrik and then lists to create a new list.
You should not need to enable the system plugin, only the plugins you want to test.

**Comment by trob** [comment]
Not sure what is going on on your site.
I just tried, the Fabrik system plugin is installed published and Fabrik is working.

BTW: If there are issues with the Fabrik system plugin you can disable it manually directly in the J! DB #__extensions

**Comment by skurvish** [comment]
Sounds to me like the library did not install.

**Comment by joomlahenk** [comment]
I did the install once again as described above and have no issue. library installs and is enabled.

**Comment by trob** [comment]
@ontargetWeb : Please try a new download and installation, maybe something is corrupted.

**Comment by ontargetWeb** [comment]
Hi I think the issue was in my php.ini settings although I had max upload etc set to 100M
I got it working on localhost Xampp so I matched the php.ini settings on the live server.
This allowed the package to be uploaded successfully.
The settings that worked were
max_execution_time 120
max_input_time 60
memory_limit 512M
