### ISSUE TITLE
com_fabrik config settings not in #__extension after installation

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#372]
Although in Fabrik Option/Elements DATE and DATETIME are set to jdate.

**Comment by skurvish** [comment]
How did this work in F3?

**Comment by trob** [comment]
Found it: After the installation in #__extensions com_fabrik params are empty. 

It's only filled if you do a' Save' on Fabrik Options (which I had obviously done on my F3 and F4 GitHub test sites at some point).

So in administrator\components\com_fabrik\models\list.php it won't get any config setting and takes the coded defaults - which is still 'date' for DATETIME etc.

I fixed the default, https://github.com/joomlahenk/fabrik/pull/375

but I assume the configuration settings should make it into #__extensions during the installation?

**Comment by skurvish** [comment]
I believe that is how it was in F3 as well. There are many extensions that require you to open and save the configuration before using them.

**Comment by trob** [comment]
Yup,  just tested with Akeeba, it's the same empty params.
Maybe it's only inserted if <config> is included in the plugin.xml and not in an extra config.xml?
Anyway, closing this.

Just keep in mind to keep the config defaults the same as defaults in code.
