### ISSUE TITLE
Remove some unused files ?

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#38]
Just to save some space and make it more clear what files are used: 
In all ../views/tmpl folders we have default.php files that are never used (as far as I could track). Can we remove those and then rename all bootstrap to default ?
Does the same apply for *raw files ?

**Comment by trob** [comment]
I would keep bootstrap. 
I assume they are taken as default, not sure what you have to change additionally if you rename them.

And I think we should change as little as possible, there can be always custom code, overrides etc. relying on existing files, names, functions etc. (We are just struggeling with this kind of not backward compatible stuff...)

**Comment by joomlahenk** [comment]
OK, agree
