### ISSUE TITLE
Tabs disappear when clicking on a different tab.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#381]
See also issue #349. After latest GH update now tabs disappear when clicking on a different tab. This is now not only for the sidebar, but for all tabs.

**Comment by joomlahenk** [comment]
Had to revert PR #379 to solve this

**Comment by skurvish** [comment]
OK, I noticed this as well. I will investigate.

**Comment by skurvish** [comment]
Well that's really annoying isn't it.

**Comment by ontargetWeb** [comment]
I'm getting the same problem - its a CSS issue (same as #391  i believe. When you click on the tab it changes style ="display:none" in the tab / button li
See screenshots
<img width="1000" alt="Screenshot 2022-10-19 at 17 55 36" src="https://user-images.githubusercontent.com/26169616/196756259-8c3c1897-aa9e-4a75-a864-ae6177318bff.png">
<img width="1000" alt="Screenshot 2022-10-19 at 17 56 10" src="https://user-images.githubusercontent.com/26169616/196756276-6a2de4c8-66fb-4e7d-972a-652b59ddf6b2.png">

**Comment by joomlahenk** [comment]
I merged PR #379 again to have the issue back and then changed the id's like in PR #395 => no issue is not solved by changing the id's. So I reverted PR #379 again.
It's however a good practice to change the id's, but then I would change them into a more unique fabrik id to be sure the id will not be used by any other JS then fabrik. Like "Fab_NavData". There are also more files where id="myTab" is used. I will change all into Fab_Nav...

**Comment by joomlahenk** [comment]
I also discovered that PR #379 is causing issue #391

**Comment by trob** [comment]
Ah, yes. Seems I missed exactly this GH version while looking at the missing tabs. Vanishing tabs and vanishing full_element names etc. are replicatible if I reset it to this version - and ok with the latest GH.

**Comment by skurvish** [comment]
Not quite OK, if you click on a tab before Fabrik is fully loaded another tab disappears. That was what I was trying to fix in the first place. The MyTab ID was left over from an attempt to use the J4 BS5 tabs interface. My bad on this one.

The other tab IDs were put in place to be able to monitor them if they disappeared and then show them again.

There was a time when certain places in Fabrik that if you tried to do something before all of the Fabrik stuff was loaded you got a message asking you to wait. I have been unable to find this anywhere. I have been playing with some stopPropogation and preventDefault on click events but they don't seem to do anything. I will keep looking because we do need to solve this original problem.

**Comment by joomlahenk** [comment]
OK. I can't make tabs disappear by clicking on a different tab on my (local) site right now. However my site is loading quite fast, so it may be an issue if you have a slow loading site. I can't test that.

**Comment by ontargetWeb** [comment]
Hi bravo! I can confirm the latest GH has fixed the the issue for me - i am on a live server not local

**Comment by skurvish** [comment]
Did you try it once the tabs start to display but before everything is loaded? Click on one of the non-first tabs during this period and the first one in the row disappears.

**Comment by ontargetWeb** [comment]
The tabs load pretty quickly so i dont get a chance to click. Prior to last GH update they would always disappear on clicking but now they are solid. I will try to load some js validations as they can sometimes slow the tab load speed

https://user-images.githubusercontent.com/26169616/196952039-943e368e-3c34-4f15-8b76-ad800600d0ae.mov

**Comment by trob** [comment]
Yup, I can see it, too.
The F3 "still loading"s are here
![grafik](https://user-images.githubusercontent.com/1045355/196969564-9e650615-1f57-4eb5-ba76-3a07e15abb9b.png)

**Comment by skurvish** [comment]
OK, those prevent the user from trying to save/cancel before Fabrik has fully loaded. I have submitted PR #399 that should resolve the runaway menu items.

**Comment by ontargetWeb** [comment]
> Try it on a new list. Particularly the horizontal tabs. Click on Filters as soon as it is displayed. The Text tab will disappear (at least on my site).

Hi I cant replicate this - all the tabs are now working fine on lists, elements, forms

**Comment by ontargetWeb** [comment]
> Try it on a new list. Particularly the horizontal tabs. Click on Filters as soon as it is displayed. The Text tab will disappear (at least on my site).

Yes I can replicate this, immediately clicking on filters tab makes the first tab"text" disappear

**Comment by ontargetWeb** [comment]
> OK, those prevent the user from trying to save/cancel before Fabrik has fully loaded. I have submitted PR #399 that should resolve the runaway menu items.

I have updated the 3 files as per commit #399  but I can still recreate the issue "immediately clicking on filters tab makes the first tab"text" disappear"

https://user-images.githubusercontent.com/26169616/197150180-d9b537ac-f243-461e-a573-b1a8a3065e7d.mov

**Comment by skurvish** [comment]
Did you clear your cache? Any time you change a javascript file you should clear your cache.

**Comment by trob** [comment]
Use additionally PR https://github.com/joomlahenk/fabrik/pull/401

**Comment by skurvish** [comment]
You are correct @trob my bad, must have been a result of my muddled head due to the cold I am fighting. Good catch.

**Comment by trob** [comment]
> a result of my muddled head

That's what I thought ;-)
I have the feeling that isDebug() is always true (I didn't get the /dist/file to load) but anyway, it's working very well.

**Comment by skurvish** [comment]
@ontargetWeb can you update with PR #401 and test and let us know if all is good? Thanks.

**Comment by ontargetWeb** [comment]
> @ontargetWeb can you update with PR #401 and test and let us know if all is good? Thanks.

@skurvish Working great now 👍
