### ISSUE TITLE
Make languages installable seperate

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#39]
All possible languages are now installed consuming a lot of space. I think we only need English as default and make all other installable.

**Comment by joomlahenk** [comment]
A quick fix could be: just keep it like it is now (install all languages) and have a tool to remove some later. The tool can be on the home menu item. Have a multiselect list and select the ones to keep, remove all other.

**Comment by trob** [comment]
Yes, this is a possibility. It will reduce backup sizes or general disk space.

But you will get the files back with each update and have to remove them again...
