### ISSUE TITLE
Elements in "full element name" column disappear on hover

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#391]
In j! Fabrik list backend hovering on any element in the "full element name" column causes them to disappear - similar to the tabs issue described.

**Comment by trob** [comment]
alpha2 or GitHub version? I can't replicate with GitHub.

**Comment by ontargetWeb** [comment]
I used the alpha2 package installer then used GitHub to load all the plugins etc

**Comment by ontargetWeb** [comment]
https://user-images.githubusercontent.com/26169616/196748791-93e43587-209e-433f-8e4c-412a1d412469.mov

**Comment by ontargetWeb** [comment]
No its vanilla J4, I overwrote the alpha2 package with the GitHub directories and files. The only 3rd party is a yootheme pro template. I disabled it to see if that made a difference but no change. 
I'm getting the same issue in Chrome, Safari and FF. I checked chrome developers and turned on console log - no errors but strangely the issue goes away when the developer tools are being used.

**Comment by ontargetWeb** [comment]
Its a css issue after hovering over the "Full element name" col i get a style=display:none; see screen shot
<img width="1000" alt="Screenshot 2022-10-19 at 17 51 56" src="https://user-images.githubusercontent.com/26169616/196755074-6c922687-a463-4efc-9dc8-f4b03b4ae4b1.png">
<img width="1000" alt="Screenshot 2022-10-19 at 17 51 02" src="https://user-images.githubusercontent.com/26169616/196755078-12605ab1-3b1d-402e-ae9d-a286ee5280c3.png">

**Comment by joomlahenk** [comment]
I can't replicate too. Did you clear the browser cache ? Looks something with tooltips. Did you try the same on the validation column ? Do you have cache enabled ? Joomla version = 4.2.3 ?
Not a css issue: style="display: none" is the result you see. Probably some JS is creating this.

**Comment by ontargetWeb** [comment]
Did you clear the browser cache ? **Yes**
Looks something with tooltips. **No Tooltips activated on any element**
 Did you try the same on the validation column ? **Validation Column also disappears ON HOVER**
 you have cache enabled ? **NO** 
 Joomla version = 4.2.3 ? **YES**
Not a css issue: style="display: none" is the result you see. 
Probably some JS is creating this. **Yes i agree, I will try to investigate further**

**Comment by trob** [comment]
> yootheme pro template. I disabled it to see if that made a difference but no change.
Does it load a framework? So to disable the template may not be enough?
In your browser console "Sources" you can see all JS and CSS files which are loaded.

**Comment by ontargetWeb** [comment]
Couldnt see any other files being loaded. I uninstalled YTP template but the issue is the same. I'm going backup the db and replace all the fabrik files again from the gitHub repo to see if that fixes it

**Comment by trob** [comment]
What are your Fabrik Options/Debuggin settings?

**Comment by joomlahenk** [comment]
The issue is caused by PR #379. This is now reverted. You need to do a GH update.
