### ISSUE TITLE
Deprecation in content type preview form

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#394]
Now this is even working with error reporting on max., I see this deprecation.
Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in
..../libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 114

I may be wrong, but I thought we repaired this in an different form.

**Comment by joomlahenk** [comment]
BTW I don't see the value of this content type preview. Only selection may be needed.

**Comment by trob** [comment]
You see which elements you'll get, I think this is usefull.
Maybe it's enough (or even better) to show the label and the plugin. All further details like validations, access settings etc. aren't visible anyway.
But 'just make it work' ;-), so I would leave it for now as it is.

**Comment by skurvish** [comment]
Fixed in PR #410
