### ISSUE TITLE
Prevent a modal form in the backend, as in J!3.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#398]
In J!4 a modal form is displayed in the backend if Ajaxify links is set to yes. The modal is has issues and should not be displayed in the backend, only in the frontend, as in J!3.

**Comment by trob** [comment]
Not sure what you mean. If F3 ajaxfied links are opening in a popup in the backend, too.

**Comment by joomlahenk** [comment]
OK, I was mistaken. But it still would solve some issues and I don't see the value of having a modal on the backend.
If it's relative easy to prevent a modal in the backend, I would go for it, else we need to solve issues with the modal.

**Comment by joomlahenk** [comment]
See issues #367 and #331. I mean the form modal. The form that opens when you want to add/edit a record. You get a modal form if you set Ajaxify links in the list settings. This is not the same as the modal we use for the configuration.

**Comment by joomlahenk** [comment]
OK, forget about it. Issues may be discovered by other testers later on or not.
