### ISSUE TITLE
Remove one helper library

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#40]
Fabrik has 2 identical helper libraries which is unnecessary. They are:
libraries/fabrik/fabrik/Helpers
components/com_fabrik/fabrik/fabrik/Helpers

As they are identical we do not need both of them. The autoloader should be able to pick up the correct one.

Something ToDo at some point.

**Comment by joomlahenk** [comment]
See #27

**Comment by joomlahenk** [comment]
see #27, so close this one
