### ISSUE TITLE
Form details view needs BS5 layouts

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#403]
Never checked this.

**Comment by joomlahenk** [comment]
I also never checked details forms, guess we should

**Comment by skurvish** [comment]
Working on it now

**Comment by skurvish** [comment]
Should be mostly fixed in PR #407

**Comment by joomlahenk** [comment]
Is looking ok on my site(s). 
Only issue left now is that only the goback button is on the details view. All buttons are on form edit and should not be on the details view (as in J!3). The goback button does not work however and need not be displayed.
See issue #400

**Comment by trob** [comment]
See https://github.com/joomlahenk/fabrik/issues/423 
GoBack is working and useful in standard details view.
In modal forms or details it's acting/should act like Close (so it may be in both or in none of them).
