### ISSUE TITLE
Load calc value in another calc

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#405]
Not sure if this is a Fabrik 4 issue but I cant seem to get data from one calc element and load it into another.
e.g 
table_calc1 = return "Hello world";
table_calc2 = return '{table_calc1}';

calc2 doesnt return anything (with ajax turned on)

**Comment by joomlahenk** [comment]
Not sure if this can be done this way.
Did you try the same in J!3 ?

**Comment by ontargetWeb** [comment]
You are correct - doesn't seem to work in j3! either

**Comment by trob** [comment]
You can't. It's not determined which calc is calculated first.
