### ISSUE TITLE
Some missing parts that hold back upgrade test

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#406]
I want to do a quick upgrade test of a not overcomplicated F3/J3 site. I'm really curious what that would bring.
If it is too early please let me know and I will not report issues.

What I'm missing in the Alpha 2 release is the **form plugin juser** (should be OK according to the wiki). That is really required for this site.
It would also help if the **validations emailexists and specialchars** could be added, but not absolutely required.

Do you see possibilities to add those in the Alpha 3 release?

**Comment by skurvish** [comment]
We are hoping to get the emailexists validation done, it is partially working. Just needs to bubble up to the top of the workload list. juser has been tested and is working so I will make sure it is included in alpha3. I don't think anyone has looked at specialchars yet.

Feel free to try the upgrade. Report issues as you find them. Upgrade issues won't take a priority yet though. Make sure you assign the installation/upgrade label to any of these as you create them.

**Comment by skurvish** [comment]
@EricdeWaal  Actually, as far as I can see the user plugin is included in alpha2. Note, it is not juser it is just user, always has been. Can you please check and confirm?

**Comment by skurvish** [comment]
@EricdeWaal Ooops. never mind, it is the element user plugin that is included. I will include the form juser plugin in alpha3.

**Comment by skurvish** [comment]
If you wish to start using the form juser plugin I am attaching it here.file:///home/joomla/git-workspaces/fabrik/fabrik_build/output/pkg_fabrik_sink/packages/plg_fabrik_form_juser_4.0alpha2.zip

**Comment by EricdeWaal** [comment]
Thanks. I'll let you know of the F3 > F4 upgrade worked!

**Comment by skurvish** [comment]
@EricdeWaal Have you tried the upgrade test yet? I am interested in any issue you uncover with datetime columns in Fabrik or your user list tables.

**Comment by EricdeWaal** [comment]
Hi, currently I am on a short holiday,  but will definitely test on Saturday!

⁣Met vriendelijke groet,

Eric G.J. de Waal
Websitebron (www.websitebron.nl/)
Tel: 078-765 0000 / 06-52723366KvK nummer: 57848416BTW nummer: NL001351696B64
​

Op 27 okt. 2022 15:52, om 15:52, skurvish ***@***.***> schreef:
***@***.*** Have you tried the upgrade test yet? I am interested in any

**Comment by skurvish** [comment]
@EricdeWaal any update on this?

**Comment by EricdeWaal** [comment]
I just tested the juser form plugin on my alpha3 updated site and it works perfectly. 
I could not test the validations emailexists and specialchars as they are not in alpha3.

**Comment by skurvish** [comment]
OK. closing this for now.
