### ISSUE TITLE
Create label for new list

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#413]
Not a real issue, but if I create a new list, enter some text in the list label field and press 'Enter' , a dialog appears, telling me, this is not possible in advanced search..
![grafik](https://user-images.githubusercontent.com/18248764/197569246-ddc2e2f9-6118-42e8-8909-f7aba937de28.png)
Or do I have some missunderstanding?

**Comment by trob** [comment]
That's the same as in F3 and not 'critical', so at the moment nothing which has priority for fixing.

**Comment by wezetel** [comment]
Totally agree! That's why I have written it is not a real issue..

**Comment by trob** [comment]
Thanks anyway for testing and reporting.

**Comment by skurvish** [comment]
Closing, we can investigate F3 issues maybe at some future point, a search of closed issues with F3 label will find them.
