### ISSUE TITLE
Plugin Status on Update F3-F4

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#414]
As some people are now contemplating doing some upgrade testing I think it would be in our best interest to have the package installer check for any plugins the user has installed that we are not supporting yet (or ever). Unsupported or untested plugins can cause havoc and generate multiple issues in places other than in the plugin itself. This would quite likely cause untold hours of unnecessary troubleshooting.

I propose we check during the upgrade if any of these plugins are installed and if so generate a big red warning about them or even not install/upgrade if they are installed. This should not be that difficult as the package xml is available to the package installation script and it lists all the plugins that are going to be installed.

Any thoughts?

**Comment by joomlahenk** [comment]
In com_fabrik.manifest.class.php this was also done in the function update. Maybe we make this function working for the plugins we don't want to be installed and remove them. Additionally we can do a check in pkg_fabrik.manifest.class.php, give a warning and let the user choose to continue install removing the plugins, or exit the install.
The user may need to find an alternative for a certain plugin first.

**Comment by skurvish** [comment]
It also occurs to me that there may be elements of plugins types we do not support, and potentially validation plugins. It is easy enough to find elements of unsupported types, less easy to find validation plugins used inside user created elements.

**Comment by raramuridesign** [comment]
Is it not possible to do a precheck of whats installed on a new page (F3)
vs
what can be installed with F4?
This could be a simple file to upload onto the server to check...

Then it could show what is supported and not supproted.

**Comment by skurvish** [comment]
Yes, it is possible to check, at least for the installed plugins. This is done in the preflight function of the installation manifest file. It could also be possible to check for unsupported validation plugins and disable them. Which also means we would need to check for unsupported form and list plugins.

A fair amount of work though.

**Comment by trob** [comment]
> Unsupported or untested plugins...

If we decide that a plugin is definitively unsuported in F4, ok.

But I think one goal of the alpha testers is to test not only stuff that's already tested.
It should be possible to install additional plugins via GitHub and test.

Are ALL "Ok" plugins included in the alpha zip (I don't think so, eg. time is marked ok but somebody is asking for it, I can't find it at the moment)? 
Or only core plugins as in F3?

But it should always be clearly marked (some more labels?) if an issue is related to a non-alpha plugin, to a F3->F4 upgrade test, if the code base is latest alpha version or the recent GitHub version etc.

**Comment by raramuridesign** [comment]
@skurvish @trob Is this still being maintained.
https://github.com/joomlahenk/fabrik/wiki/Status-of-plugins

Perhaps this should be the area we point users to - so they are aware of what is working on what is not working.
Perhaps adding ETA's when to be completed etc or discontinued
Thoughts?

**Comment by skurvish** [comment]
At present all plugins that have been tested as working are (or should be) included in the alpha packages. At some point this will need to be pared down to a manageable number so that those who are on restricted hosters can install it. Many hosters limit the max upload size and do not allow users to change it. Once the package is installed the installation can be updated from github or by downloading a specific plugin (once these get uploaded to the update site.

**Comment by joomlahenk** [comment]
Can we use the joomla pre-update check for that ? We need an update site anyway. This would be the most ideal solution I think.
User can see what plugins will not be supported and need to be removed first before they do an upgrade. If you do an upgrade to J!4 and then on install fabrik you find a plugin no longer supported, there is no easy way back.

**Comment by skurvish** [comment]
Probably, I will need to see how we eliminate plugins from being built. The current build process build everything in the plugin folders, but I can probably add an exclusion list. If we do this then no update xml will be created and then it would show as unsupported in the joomla pre-update check.

During install if we found a plugin no longer supported we can stop the install immediately, just like we do for J! and PHP level checks.

**Comment by trob** [comment]
We should have a "single point of plugin status". 
I would use https://github.com/joomlahenk/fabrik/wiki/Status-of-plugins (and link to it in https://github.com/joomlahenk/fabrik/wiki/Alpha-Tester-Instructions) to have only one point to keep up to date.

So with an additional column "included in alpha-zip"?
Remove the column "issue"? Issues related to a plugin can be put into Description.

**Comment by skurvish** [comment]
Sounds like a good idea. I have changed the Issue column to Alpha3? and will insert Yes into the appropriate rows.

**Comment by skurvish** [comment]
Status inserted into the list. I will update the alpha tester instructions when we are ready to release alpha3. I have the package build stuff ready and will PR those changes but not the actual alpha3 update.

I need to look at what is required to limit the plugin builds to only those in the package so that the update xml files do not get built.

**Comment by raramuridesign** [comment]
@skurvish Looks better... and I think this will help for testing

**Comment by skurvish** [comment]
build process updated to only build and upload supported plugins to the update server. PR #430
