### ISSUE TITLE
Can't Empty trashed elements (hangs for very long time)

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#425]
Trashing an element then clicking empty trash gives the js alert box **_"Fabrik is still loading, please wait a few second"_**  and then its not possible to delete the trashed items.
Have tried with 1 element and multiple elements in the trash.

**Comment by skurvish** [comment]
Interesting,  will have a look as I added the alert.

**Comment by skurvish** [comment]
OK, I see the issue. It is not with the alert per se, but on the trash page we are getting a bunch of other javascript errors. Will investigate.

**Comment by skurvish** [comment]
I have submitted PR #427 which eliminates this issue. You can now empty the trash OK. The javascript errors still exist but they do not impede functionality. I will open another issue on that separately with low priority.

**Comment by trob** [comment]
The alert was only if you also select column for deletion. Ok after PR https://github.com/joomlahenk/fabrik/pull/427
