### ISSUE TITLE
Empty Trash Javascript Errors

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#428]
For some reason in this view the requirejs.config is not being inserted into the DOM. As a result the path fab is undefined and is not translated to media/com_fabrik/js as it should. Normally this config is inserted by the display function of the elements view, but the confirmdelete function isn't doing it.

I have only seen this on this one page but the errors do not impede the operation so this is going on the list as low priority to investigate at some time.

**Comment by PRO-BROS** [comment]
I also faced a similar issue on my [site](https://prhocoding.com/) but thankfully I hire a developer which resolve that's issue.

**Comment by skurvish** [comment]
Fixed with PR #470
