### ISSUE TITLE
DBJoin Element

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#43]
@trob do I understand that you have this sort of working? If so I will add it to the list of elements that get installed.

**Comment by trob** [comment]
Yes, I have it working. But at the moment I'm struggeling with merge conflicts locally.

**Comment by trob** [comment]
See https://github.com/joomlahenk/fabrik/wiki/Status-of-Plugins

**Comment by joomlahenk** [comment]
you don't have any files to commit ? Can I then close the issue ?

**Comment by skurvish** [comment]
Yes. I am going to add a few more elements to the install package based on the status of plugins wiki. But this issue can be closed.
