### ISSUE TITLE
Jquery-UI not loaded

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#434]
Jquery-UI should be loaded as it is in J!3. This was not loaded in J!4 till now. So far I didn't encounter any issue with it being not loaded. I updated ..\Helpers\Html.php and now it's loaded. Maybe it solves or prevents some issues.

**Comment by trob** [comment]
This also solved 4. in https://github.com/joomlahenk/fabrik/issues/337

**Comment by PRO-BROS** [comment]
Very well. Facing same issue but now resolved on my [site](https://prhocoding.com/)
