### ISSUE TITLE
Fabrik Tables with datetime values of 0000-00-00 00:00:00 fail on save

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#435]
**To Reproduce**

Find an existing F3 fabrik table such as lists, forms, etc and find a record that has 0000-00-00 00:00:00 stored in ether the date_time or created columns. Edit the record in the admin and the attempt to save it.

**Expected behavior**

Record saves correctly.

**Actual behavior**

Save failed with the following error: Incorrect datetime value: '' for column ....

** comments

Looks like various versions of Fabrik stored null dates in some of these tables. Null dates in the past were allowed to be this value but not now. Need to change each tables save function to check for zero value dates in its various datetime columns and update them to either the current date/time or null ass appropriate.

This is going to affect people as they start to do upgrade tests.

**Comment by skurvish** [comment]
It is interesting that in the various models that some of the datetime fields are set using the \Database::getNullDate() function call which currently returns "0000-00-00 00:00:00". Given that joomla no longer supports this as stated [here](https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#PHP_MySQL_Extension) I suspect that this is wrong and have opened an issue on it on the J! issue tracker.

**Comment by joomlahenk** [comment]
I am unable to reproduce.
In J!4 I have a list with several records containing date-time columns.
In phpMyAdmin i changed these records to have 0000-00-00 00:00:00.
Then in fabrik I open the record to edit and the date-time fields are now blanc. I can keep it like that or change it to a valid date and I can save them without any problem.
Can you help me to reproduce this?

**Comment by skurvish** [comment]
It is not a list table, but the fabrik table of lists/forms/etc. so check table #__fabrik_lists for any created dates of all zeros. Open one of these and try and save.

**Comment by skurvish** [comment]
So I know how to fix it. The question is, if the current value of the created field is and empty string or "0000-00-00 00:00:00" should we save a new value of null or set the created date to now?

**Comment by joomlahenk** [comment]
So I created a new list from #_fabrik_elements, because this contains a lot of 0000 dates as I can see in PMA. I try to edit and save => no problem.
I still can't reproduce. If you can fix it OK. In that case such value should then be NULL, I think.
