### ISSUE TITLE
Placeholders not interpreted in List Link Plugin

### ISSUE THREAD

**Issue by thommangooo** [joomlahenk/fabrik#437]
Perhaps there's a variation on how placeholders are supposed to appear in link urls, but if I'm remembering it correctly, then this is not working.

**To Reproduce**

1. Add Link plug-in to a list.
2. Create a link that has parameters where the value comes from a placeholder (
eg "...add-job?jobs___property_id_raw={contracts___property}

**Expected behavior**
The value of the field property in the current row of contracts should appear in the URL of the link

**Actual behavior**
The curly braces are shown in the URL

**Screenshots**

![Screen Shot 2022-10-27 at 1 54 10 PM](https://user-images.githubusercontent.com/100867227/198363390-39ecc9e9-e854-43fc-b2d9-2e4bbeb907ac.png)
![Screen Shot 2022-10-27 at 1 53 26 PM](https://user-images.githubusercontent.com/100867227/198363441-9943449c-06cb-4eeb-8a44-79bf5592b0ff.png)

**Comment by trob** [comment]
Confirmed.
But obviously this was never working in F3 (nor php7 nor php8), just tested with all combinations of "Fabrik Link".

**Comment by thommangooo** [comment]
Actually, I currently have F3/J3 sites that use this extensively and without issue.

**Comment by trob** [comment]
Ok, yes. I missed to add _raw in F3.

**Comment by trob** [comment]
Solves with https://github.com/joomlahenk/fabrik/pull/439
