### ISSUE TITLE
Element Field - Validation PHP - NOT WORK Fabrik4

### ISSUE THREAD

**Issue by HyperOsmar** [joomlahenk/fabrik#443]
if (preg_match('/^(([0-9]{3}.[0-9]{3}.[0-9]{3}-[0-9]{2})|([0-9]{11}))$/', $data) == 1) {
 
$c = preg_replace('/\D/', '', $data);
      
  if (strlen($c) != 11 || preg_match("/^{$c[0]}{11}$/", $c)) {
        return "false";
        }
        
  for ($s = 10, $n = 0, $i = 0; $s >= 2; $n += $c[$i++] * $s--) ;
       
  if ($c[9] != ((($n %= 11) < 2) ? 0 : 11 - $n)) {
        return "false";
        }
        
	for ($s = 11, $n = 0, $i = 0; $s >= 2; $n += $c[$i++] * $s--) ;
       
	if ($c[10] != ((($n %= 11) < 2) ? 0 : 11 - $n)) {
        return "false";
        }
        return true;
}

**Comment by trob** [comment]
Please use the issue templates and mention which code base you are running (latest alpha download or lastest GitHub version). 

Php validation is running.

Please report only issues with F4 functions, not issues with your custom code.

**Comment by HyperOsmar** [comment]
What I wanted to show is that in Fabrik3 the code presented PHP works perfectly as a validation of the element Field, while in Fabrik4 it doesn't...

Sorry if I didn't express myself properly in the previous post.

Joomla 4.2.4
Fabrik 4.0alpha3 (28.10.22)

**Comment by skurvish** [comment]
Before we look too closely at this, please change your code and remove the quotes around the word false. You are returning a string of the word false which would equate to true if tested as a boolean. PHP8.1 is much more strict about what it accepts as true/false, empty etc so your code needs to be correct.

**Comment by HyperOsmar** [comment]
I appreciate the feedback.
