### ISSUE TITLE
Forms view missing Content Type icons

### ISSUE THREAD

**Issue by bumpsadmin** [joomlahenk/fabrik#444]
In the list of Forms the Content Type Icons are missing

The Title is not representative of the selection

![image](https://user-images.githubusercontent.com/87337728/198608031-1330d3f0-1697-4722-b463-2a00f59db364.png)
 Export button appears when selected
![image](https://user-images.githubusercontent.com/87337728/198611050-675c5efd-ce0b-4676-9506-6cce13906ba0.png)

New Joomla 4.2.3 built with Fabrik 4.0 Alpha 2 form github download.

**Comment by skurvish** [comment]
Can you please install alpha3 and retest. I doubt it will fix the issue but best to be as close to what we are using as possible.

**Comment by trob** [comment]
It's like in Fabrik3, what do you expect?

https://github.com/joomlahenk/fabrik/pull/447 does remove the unnecessary "<" (which is already there in F3 but obviously not displayed)
