### ISSUE TITLE
Alpha3 : new gmap viz hang --> error 500 on loading mootools.js (indeed)

### ISSUE THREAD

**Issue by lcollong** [joomlahenk/fabrik#445]
**To Reproduce**
create a new Gmap viz in the backend

**Expected behavior**
parameters form

**Actual behavior**
hang

**Screenshots**

**Additional context**

**Comment by skurvish** [comment]
We do not support Can you check the javascript console and report any errors that are displayed when you do this?

**Comment by lcollong** [comment]
I thought you intend to support visualization plugins as per the last paragraph of https://github.com/joomlahenk/fabrik/wiki/Status-of-plugins ? 
As soon as you select "googleMap" in the plugin selection dropdown, you'll get the error : 

mootools-core.js:3          POST http://j4/administrator/index.php 500 (Internal Server Error)
send @ mootools-core.js:3
s.extend.$owner @ mootools-core.js:3
send @ mootools-more.js:3
changePlugin @ adminvisualization-min.js:3
s.extend.$owner @ mootools-core.js:3
(anonymous) @ adminvisualization-min.js:3
dispatch @ jquery.min.js?3.6.0:2
v.handle @ jquery.min.js?3.6.0:2
handleMouseUp_ @ unknown

**Comment by trob** [comment]
We DO support Googlemap viz and it was working fine.

I now get
"Cannot assign by reference to overloaded object"
for my existing Googlemap viz and also Fullcalendar viz in the frontend.

Let me check when this crept in (I didn't try the vizs for some time)

**Comment by trob** [comment]
I reset my local repo to a point way back where Googlemap viz surely was working (with J!4.2.1 or 2 at this time).

I still get the "overload" error.
Is it related to J!4.2.3 resp. 4.2.4?

**Comment by skurvish** [comment]
Sorry, my bad, I started to write we did not support it, then I went back to check and we did. I forgot to delete the first part of the sentence.

**Comment by trob** [comment]
I have a J!4.1.5/F4 from 4 Sep where it's working

**Comment by trob** [comment]
It's a J!4.2 issue. I installed J!4.2.0 on this "working site" -> error with Googlemap and Fullcalendar viz.

But this "overloaded object" is out of my scope.

**Comment by skurvish** [comment]
the overload object is easy to fix. I am now getting a "Fabrik\Plugins\Visualization\" class not found. Will investigate further tomorrow.

**Comment by joomlahenk** [comment]
Yeh, from 4.2. they stared to make use of more DI and traits. That's why we needed to add the Database interface and Database traits in FormField also. So the solution is probably in that area. From 4.3 they will use even  more of that.
I have no experience with any viz plugin and how to set it up.

**Comment by lcollong** [comment]
On my wamp/J4.2.4/PHP.8.1.0/Alpha3 : I get an error at the very beginning : 
go to "visualizations" on the left Fabrik's menu
click on "new"
on the bottom of the form coming up, select "googleMap" in the dropdown "plugin". It starts hanging with the error 500 at that point.

**Comment by trob** [comment]
Yes, but error 500 comes from the error "overload..." in the JSON network response. So it's the same reason.

**Comment by skurvish** [comment]
The overload issue is solved with PR #450 I tested with fullcalendar and it seems to work OK. I haven't tested with gmaps.

**Comment by joomlahenk** [comment]
I tested with gmaps, just select gmaps instead of fullcal.

PR#450 solves the 500 error in console.
But now I have (2 times):
Notice: Indirect modification of overloaded property FabrikFEModelVisualization::$row has no effect in /var/www/html/joomla4upd/components/com_fabrik/models/visualization.php on line 73

Also the modal boxes that are opened on the select buttons need BS5
And tooltips are not as in other forms.

**Comment by lcollong** [comment]
Indeed. PR#450 solves the issue. All what I've tested works as expected

**Comment by skurvish** [comment]
@lcollong thanks. @joomlahenk do you still have issues here?

**Comment by joomlahenk** [comment]
OK, "Notice: Indirect modification of overloaded property..." disappeared after latest GH update. Other updates still todo (BS5, tooltips)

**Comment by skurvish** [comment]
Working on it now.

**Comment by skurvish** [comment]
@joomlahenk The tooltips I see look just like the tooltips on other element plugin types. Or are you talking about somewhere else?

**Comment by skurvish** [comment]
Modal styling fixed in PR #458

**Comment by trob** [comment]
All fine (nearly) on my site now. 
Three low prio points remaining:

1. @joomlahenk is right: The tooltips in googlemap and fullcalendar viz are no tooltips but just titles - but only on new vizs (and only in the plugin options). After saving the new viz the tooltips are ok when opened again.

2. In both viz plugins we have still the sticky spinner below the list dropdown

3. In both vizs: When selecting a list it's showing sa console error "unexpected token..." coming from a warning in the network response afer the JSON :`<b>Warning</b>:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: C:\xampp8\tmp) in <b>C:\xampp8\htdocs\j4h40\libraries\vendor\joomla\session\src\Storage\NativeStorage.php</b> on line <b>114</b><br />` (which doesn't tell me anything)
But the viz can be saved and is working normally.

**Comment by skurvish** [comment]
I will have a look tomorrow.

**Comment by skurvish** [comment]
Point #1, this is how it worked in F3.

**Comment by skurvish** [comment]
Point #2, I cannot figure this one out. Does not affect the workings though.

Point #3, I am not seeing this.

**Comment by trob** [comment]
Point 1: indeed, I never realized this
Point 3: doesn't occur again on my site

Point 2: I will open a new low prio issue for this
