### ISSUE TITLE
Deprecated: DateTime::__construct(): Passing null to parameter 1

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#446]
See issue #377 
We have the deprecation back again after PR#436.
Deprecated: DateTime::__construct(): Passing null to parameter 1 ($datetime) of type string is deprecated in /var/www/html/joomla4upd/libraries/src/Date/Date.php on line 124

**Comment by joomlahenk** [comment]
Tried again after undoing the changes of PR#436, but still have that nasty deprecation.
I discovered this after new fabrik install on vanilla J! and create a list with just id and jdate.
The deprecation is on opening view-data in the backend. In issue 377 we had this on the form. In this case I don't have it on the form.

**Comment by skurvish** [comment]
I won't be hard to find. I am somewhat tied up the rest of today but can look at these first thing Saturday.

**Comment by skurvish** [comment]
Should be fixed with PR #453

**Comment by joomlahenk** [comment]
Not fixed here.

**Comment by skurvish** [comment]
I tested this on the backend and opened a record in both edit and view mode and am not getting the deprecated error. Are you looking at this somewhere else?

**Comment by joomlahenk** [comment]
I discovered this after new fabrik install on vanilla J! and create a list with just id and jdate, like always. Browser cache was cleared first, like I always do. I always create a new list with just id and jdate.
The deprecation is on opening view-data in the backend.

**Comment by skurvish** [comment]
@joomlahenk I am not seeing this. Can you confirm that it is still happening on your site?

**Comment by joomlahenk** [comment]
After several reinstalls and GH updating I don't see this deprecation anymore. Guess clearing cache does not clear cache or some other cache.
