### ISSUE TITLE
Upgrade: 

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#448]
**What happend**

installed alpha3 on a site containing alpha2

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Error message**
Table 'db-name.DB-prefix_fabrik_sequences' doesn't exist
Package Update: an error occurred installing an extension: plg_fabrik_element_sequence_4.0alpha3.zip

**Screenshots**

**Additional context**
I created the table with the sql in the plugin which installed correctly after that

**Comment by skurvish** [comment]
Interesting, the installation should create that table. Will investigate.

**Comment by joomlahenk** [comment]
So far I never tested installing alpha3 on a site containing alpha2. I always first uninstall alpha2 first and then install alpha3.
If you mean to do an update in this way you should use the J! update feature, but for fabrik4 we don't support that yet.
Maybe it should work like you did, but I never tried that with any other extension.
I will try and see what happens.

**Comment by skurvish** [comment]
@EricdeWaal Did this get resolved on your latest upgrade attempt or is it still outstanding?

**Comment by EricdeWaal** [comment]
The are data in my testing site, and I wanted to keep those for testing, therefore did not uninstall fabrik.
So far I updated fabrik as I did just now without problems.
And the issue "Table 'db-name.DB-prefix_fabrik_sequences' doesn't exist" did not occur now and the table is there.
