### ISSUE TITLE
Upgrade: 

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#449]
**What happend**
After install of alpha3 over alpha2

**To Reproduce**

**Expected behavior**
See new packages and alpha2 packages all updated

**Actual behavior**
Some 18 elements stayed on version alpha2 
Some elements and validations, which were previously not in alpha2, were missing.
They are present in the package, but obviously not in the install list
The package version is still alpha2 >> found this is in the extensions com_fabrik manifest_cache field in the database

**Error message**

**Screenshots**

**Additional context**

**Comment by skurvish** [comment]
@EricdeWaal can you provide a screenshot for me please?

**Comment by EricdeWaal** [comment]
Not anymore I'm afraid, I manually installed everything from the package that was missing and that all went well.
I only had the incorrect package version alpha2 issue left.
The I installed com_fabrik_4.0alpha3.zip from the packe but now have a not working backend: 
0 PLG_FABRIK_SYSTEM_AUTOLOAD_MISSING

**Comment by skurvish** [comment]
Can you check that you have the file libraries/fabrik/include.php ?

**Comment by skurvish** [comment]
And that the permissions are correct

**Comment by EricdeWaal** [comment]
I dont have that file

**Comment by skurvish** [comment]
Reinstall the library zip from the alpha3 package, that should clear it up. Then I need to figure out why it got uninstalled.

**Comment by EricdeWaal** [comment]
I can't do that as I cannot do anything in the backend: just have the **0 PLG_FABRIK_SYSTEM_AUTOLOAD_MISSING** error

**Comment by EricdeWaal** [comment]
I can restore a midnight backup and start all over again

**Comment by skurvish** [comment]
OK. Stop as soon as you see something wrong and let me know the steps you took to get there, with screenshots if you can. I will then try and replicate to that point.

**Comment by EricdeWaal** [comment]
Will do

**Comment by EricdeWaal** [comment]
Ok, done. Now install the alpha3 package?

**Comment by skurvish** [comment]
Yes.

**Comment by EricdeWaal** [comment]
Unbelievable! It installed without a problem (so far as I can see). I have really no idea why it did not previously. I'll just do some further checks.

**Comment by skurvish** [comment]
I love the ones that fix themselves.

Is it possible the upgrade did not complete the first time? Maybe a timeout or something?

**Comment by EricdeWaal** [comment]
I don't think so, I have max_execution_time 240 s, memory limit 256 MB and max upload 100MB on a very fast high quality hosting.
