### ISSUE TITLE
.col-sm-2 CSS overriden in modal form

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#460]
**To Reproduce**
use any element in a modal form

**Expected behavior**
the label will be displayed left of the content field on the same line, lines are striped

**Actual behavior**
the label is made 100% wide pushing the element content to the line below
Striped (background and line-separating borders) are missing

**Screenshots**
modal
![afbeelding](https://user-images.githubusercontent.com/5586423/198839565-179716e2-3d15-4740-a535-2d585a24c5a9.png)

non-modal:
![afbeelding](https://user-images.githubusercontent.com/5586423/198839530-62694da1-4ef0-4d50-a28a-8ef0409f6075.png)

**Additional context**
The label has classes: form-label fabrikLabel  col-sm-2 col-form-label
The cassiopeia.min.css template has:
  @media (min-width: 576px)
.col-sm-2 {
  flex: 0 0 auto;
  width: 16.66666667%;
}
Similar for the element content. That works. 
In a modal form, however, it is overridden by (from the same css file):
.modal label {
  width: 100%;
}

**Comment by joomlahenk** [comment]
Did you try to set the pop-up size and position in the list links settings ?

**Comment by skurvish** [comment]
I have seen this behavior myself. Knew it was going to come up. Will have a look.

**Comment by EricdeWaal** [comment]
> Did you try to set the pop-up size and position in the list links settings ?

Yes I tried that but it makes no difference

**Comment by skurvish** [comment]
Yes, the modal label size is set to 100% by both the Atum and Cassiopeia templates. No idea why. PR #472 forces the width back to 16.6% when rendered in a modal.

**Comment by EricdeWaal** [comment]
Yes it's soved in beta1, thanks!
