### ISSUE TITLE
databasejoin hangs

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#462]
**To Reproduce**
databasejoin element in a list: try to define the join to a field element in another list

**Expected behavior**

**Actual behavior**
Spinner in data area don't stop. 
Error 500 when calling the list data:  Fabrik has generated an incorrect query for the list Terminanfrage: <br /> 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18248764/198865437-8922b620-eb46-4c95-8312-68913affe774.png)

**Additional context**
J4.2.4 F Alpha3

**Comment by trob** [comment]
I assume it is working if you turn off J! error reporting?
Can you check your browser console and the network response?

I can see this issue on one of my sites (the reason is also the "session" warning mentioned here https://github.com/joomlahenk/fabrik/issues/445
An other site (also J4.2.4 F Alpha3) seems to be ok.

**Comment by wezetel** [comment]
Strange: I turned of error reporting and the error 500 disappeared. Then I turned on error reporting again and still no error 500 :-)
So this seems to work now !
But the spinners at the value and label fields are still present. As long as this is just a visual problem, but the selected values are saved, it's not a big issue,

**Comment by trob** [comment]
These spinners are only a visual issue, yes.
But the warning is strange...

**Comment by skurvish** [comment]
Spinner issue fixed in PR #468

**Comment by wezetel** [comment]
Not sure, if I did it the correct way. I just replaced listfields.js and listfields-min.js from the code base. Now there are no spinners, but it is also not possible to select a value/label, even if I have selected a table to join..

**Comment by trob** [comment]
It's ok for me.

Did you clear all Joomla and browser cache?
Did you try with FabrikOptions/Debugging AllowFabrikDebug=Debug JS (which will load the uncompressed JS file).
Any JS errors?

**Comment by wezetel** [comment]
Sorry, I was to stupid to download the files the correct way from github. In fact with the correct file the problem is solved.

Thanks a lot!
