### ISSUE TITLE
date field mini calendar design 

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#466]
**To Reproduce**
Create a date field to show a date picker (mini calendar) in a form

**Expected behavior**
Mini calendar as in J3 F3 with correct placed controls

**Actual behavior**
Mini calendar with controls in non-logical order

**Screenshots**
J3 F3
![grafik](https://user-images.githubusercontent.com/18248764/198886840-0f95ebd4-6af3-4ace-a5ce-1ba1667a8907.png)

J4 F4
![grafik](https://user-images.githubusercontent.com/18248764/198886888-1852848c-40ba-468e-9a12-fb1b0691da8c.png)

**Additional context**

**Comment by trob** [comment]
issue https://github.com/joomlahenk/fabrik/issues/466

**Comment by wezetel** [comment]
Thanks a lot!!
