### ISSUE TITLE
Added or edited record is only displayed in the list after extra refresh.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#467]
**To Reproduce**
Open a list in the backend. Add or edit a record, then save.

**Expected behavior**
Added or edited record is displayed in the list.

**Actual behavior**
Added or edited record is not displayed in the list. Only after a refresh it is displayed.

**Additional context**
This was working ok before, but has changed since latest GH updates.

**Comment by skurvish** [comment]
This is working on my site in the admin, both normal edit as well as ajax edit. The record is updated on save and the updated record is shown in the list data.

**Comment by joomlahenk** [comment]
OK, tested again with new installed alpha3 and updated with GH. Cleared browser cache and opened in chrome incognito mode.
Then I don't see the issue
