### ISSUE TITLE
textarea wysiwyg

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#47]
Not the highest priority but
![grafik](https://user-images.githubusercontent.com/1045355/177985204-2e32ae2a-5393-4db8-8ac8-c39bab90cb36.png)

In https://api.joomla.org/cms-3/deprecated.html it says
\Joomla\CMS\Editor\Editor::save() | 350 | 4.0 Bind functionality to form submit through javascript

(which doesn't mean much to me...)

**Comment by joomlahenk** [comment]
I ran into a simular issue:  JFormFieldEditor::save has been removed without replacement. I deleted this to make ik work, but one time I have to find out how to put it back.
And remember: this is joomla, we don't document.

**Comment by joomlahenk** [comment]
I guess we now need to this in JS (not my hobby)

**Comment by trob** [comment]
`I guess we now need to this in JS (not my hobby)` Nor is mine. It will become exciting with all the ajaxfied stuff...

**Comment by joomlahenk** [comment]
Also if you update any plugin, remember to update the xml forms as well and take the xml form for field or jdata as an example.
This is because I change some styling and we like to have them all about the same.

**Comment by skurvish** [comment]
I have some javascript experience but not mootools or jQuery, simply vanilla javascript but I can take a look. Will add to my list :)

**Comment by skurvish** [comment]
It appears this is simply not needed any more. Removing the getinstance and save does not change the behaviour. Works in 3.10 as well. Fixed with PR #129
