### ISSUE TITLE
$model unavailable to php script in list plugin

### ISSUE THREAD

**Issue by thommangooo** [joomlahenk/fabrik#471]
**To Reproduce**
Install a script on a list plug in and try to access $model

**Expected behavior**
Return values 

**Actual behavior**
Return null

**Screenshots**

**Additional context**
Could just be that I'm not doing something right, but I've tried to follow the directions in [list plugins
](http://fabrikar.com/forums/index.php?wiki/php-list-plugin/) and I can't seem to access $model.    Here's my code:
`
function insertNewJobRecords($next_job, $today, $company){
    $app = JFactory::getApplication();
    $ids = $app->input->get('ids', array(), 'array');
    $item = $model->getTable();
    print_r($item); exit;

    foreach ($ids AS $myid) {
        $row = $model->getRow($myid);
        print_r($row); exit;`
I get a "Call to a member function getTable() on null" message back.  Same problem for both $model->getTable and $model->getRow

**Comment by joomlahenk** [comment]
You can no longer use the same code in J!4 as in J!3. In J!4 JFactory is deprecated and you need to use name spacing.
try $app = Joomla\CMS\Factory::getApplication(); instead.
Please read the list of [Backward Compatibility Issues](https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4) as explained on the wiki page: [Upgrading from fabrik3.10 to fabrik4](https://github.com/joomlahenk/fabrik/wiki/Upgrading-from-fabrik3.10-to-fabrik4).

**Comment by skurvish** [comment]
Not sure $model is definitely available. I think though what you have done is you haven't passed it into your function. Inside the insertNewJobRecords function you have not defined what $model is, so you have to pass it in.

**Comment by thommangooo** [comment]
Thanks.  If it's working fine then it's a user error issue.  We can close it.  FWIW, I found a way around it.
