### ISSUE TITLE
Yes/No element generates warning

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#473]
**To Reproduce**
use Yes/No element in form

**Expected behavior**
No warnings

**Actual behavior**
On the front-end, both in pop-up and normal forms, the yes/No element generates

Warning: Undefined array key "view" in /usr/www/users/prachta/dtc/plugins/fabrik_element/yesno/yesno.php on line 304

**Screenshots**

**Additional context**
By mistake submitted in the MAT J3 branch as well, will remove it there

**Comment by skurvish** [comment]
This has already been fixed in git with PR #454 not in a release yet though.
