### ISSUE TITLE
Display of calc field

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#474]
**To Reproduce**
Create list with 3 elements:

- dropdown element with selections short text and long text
- calc element which returns depending on dropdown selection short or long text (Ajax enabled!); width and height not defined ( = 0)
- display element to mark the end of form

**Expected behavior**
returned text is displayed (html formatted) and takes the necessary place (as in J3F3)

**Actual behavior**
Only first part of text is displayed and html is not taken into account.

**Screenshots**

![J3F3 long text](https://user-images.githubusercontent.com/18248764/199303634-65895d33-1ded-4773-8979-611e446dcde3.jpg)
![J3F3 short text](https://user-images.githubusercontent.com/18248764/199303642-e36ea854-fce1-41f3-8519-fd7f93b84215.jpg)
![J4F4 long text](https://user-images.githubusercontent.com/18248764/199303644-67209a05-8fed-4fc5-9c71-59f6b244a7ce.jpg)
![J4F4 short text](https://user-images.githubusercontent.com/18248764/199303648-3b9cfb34-dac4-4872-9a91-2383ef67725a.jpg)

**Additional context**

**Comment by wezetel** [comment]
@trob Do have any idea? I tried a var_dump on variable $d->value in plugins\fabrik_element\calc\layouts\fabrik_element_calc_form.php and get as a result NULL...???
In addition I saw that the class form-control-plaintext is assigned to the field. If I'm correct this would explain, why html is not interpreted (even if the field is displayed in full length in details view)

**Comment by trob** [comment]
Details view is ok on my site. But list view is showing HTML tag, too.

I just checked in Fabrik3, it's pretty the same: HTML tags are shown in list view. And they are shown in form view if you have a textarea for the calc (textareas are always plain text).

In F3 it's ok only if calc height <=1 because in this case the output is done in a <span>, not in an <input> with a "value".

@skurvish : Why did you change span to input in the form layout and this.update(r) (which would also update a span) to this.element.value = r; in calc.js?

**Comment by trob** [comment]
My suggestion PR https://github.com/joomlahenk/fabrik/pull/484

**Comment by wezetel** [comment]
For me details view and list have been ok before the PR, only form in edit mode showed the cropped field with html.
Btw.: I replaced the 3 files mentioned in the PR, cleared browser and Joomla cache. Now the calc field doesn't show any value..

**Comment by trob** [comment]
What did you set for Width and Height?
Is this a vanilla F4 (or are you updating F3)?

**Comment by wezetel** [comment]
I have set 0 for width and height. And it is a vanilla J4 and F4. (F4 installed alpha 2 and then installed alpha3) -> https://fabrikar.wezetel.de

**Comment by trob** [comment]
Try with FabrikOptions Debugging Debug Fabrik = debug js (so loading the uncompressed file)
I did minifying myself, it seems something went wrong.

**Comment by skurvish** [comment]
If minfy was the problem I will be reminifying today when I build the beta1 release.

**Comment by wezetel** [comment]
That's it! The minified JS was the problem. With debug js enabled it works.
Thanks a lot!

**Comment by skurvish** [comment]
OK, I will make sure the correct minified version is in the release.

**Comment by trob** [comment]
I did it manually :-(.
The PR is not merged anyway, you should have a look first https://github.com/joomlahenk/fabrik/pull/484
The minified file should be ok now, too.

(At the moment my test site is loading always the uncompressed files, no idea why. So I could not test)
