### ISSUE TITLE
Element settings: unnecessary input field

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#48]
All elements are now showing an unnecessary input field
![grafik](https://user-images.githubusercontent.com/1045355/177992556-482e7e37-d2fe-402e-9fbc-cc52eb585953.png)

It's in all tabs (Advanced, Formatting... if field element)
and in all element types.

**Comment by joomlahenk** [comment]
Strange, I don't have this.

**Comment by joomlahenk** [comment]
OK, now I see it. This should be the help button. Will fix it.

**Comment by joomlahenk** [comment]
Was caused by changing classnames: class FormFieldHelpLink extends FormField must be: class JFormFieldHelpLink extends  FormField
