### ISSUE TITLE
Tooltips are rendering as html source

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#485]
**To Reproduce**

Add a tootlip text to any element

**Expected behavior**

Hover over element and see the tooltip

**Actual behavior**

Hover over the element and you see a bunch of unformatted html

**Additional context**

Current github as of this moment.

**Comment by trob** [comment]
I can't replicate (tested with field element in existing and new record). 
The "Tip Text" is showing as tooltip in form/detail and even list view, although here with 'old' F3 styling (no black background)

**Comment by skurvish** [comment]
Yes, I am looking at it now.

**Comment by skurvish** [comment]
My bad, I was playing with something else and had changed the tooltip. Reverting the change resolved the issue. It is a change I had not checked in, it was part of something else.
