### ISSUE TITLE
Responsive CSS for List column visibility not working

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#486]
**To Reproduce**
Open List > Details > Layout Tab > Responsive CSS 
Choose an element and set to "hidden phone" 

**Expected behavior**
Chosen element should be invisible on mobile device using list view menu item

**Actual behavior**
Chosen element stays visible

**Screenshots**

<img width="672" alt="Screenshot 2022-11-05 at 14 40 26" src="https://user-images.githubusercontent.com/26169616/200125257-ff92f9ca-989a-4fba-ae4f-8d9af7122e95.png">

<img width="503" alt="Screenshot 2022-11-05 at 14 41 10" src="https://user-images.githubusercontent.com/26169616/200125317-2341cbdb-55d1-420f-8ca9-b1dc8786f7e3.png">

**Additional context**

**Comment by trob** [comment]
PR https://github.com/joomlahenk/fabrik/pull/491

**Comment by skurvish** [comment]
@ontargetWeb Can you test and confirm that this is fixed in Beta1 please? Thanks.

**Comment by ontargetWeb** [comment]
@trob @skurvish I updated list.xml with the #491 commit but the columns are still visible. I tried with Layout > frontend template div and bootstrap. I also cleared the browser cache. I tested on shrinking my full screen on Mac and  on iphone

**Comment by ontargetWeb** [comment]
@trob @skurvish tested and working thank you
