### ISSUE TITLE
Encrypt Data on field elements causes fabrik to hang

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#489]
**To Reproduce**
Field element > Access tab > Encrypt data = Yes
Message convert Varchar to Blob appears.
Fabrik hangs and tab becomes unresponsive 

**Expected behavior**
col should be changed to BLOB in the database

**Actual behavior**
Col remains as e.g varchar in the table - have to manually change to BLOB using phpMyAdmin

**Screenshots**

<img width="1014" alt="Screenshot 2022-11-05 at 15 50 14" src="https://user-images.githubusercontent.com/26169616/200128425-ce8c7c65-1200-4d5d-8745-534fa34caeb0.png">

**Additional context**

**Comment by skurvish** [comment]
Hmm, OK, this may be easy to fix.

**Comment by skurvish** [comment]
Fixed with PR #498 @ontargetWeb can you confirm please? It is a small change to one file.

**Comment by ontargetWeb** [comment]
@skurvish fix confirmed thanks .

**Comment by sweker** [comment]
@skurvish - I had this issue as well, and confirmed fixed. 

I am using BETA1, and I must say that it is working absolutely great. Thank you all for your hard work and effort. I appreciate this group keeping Fabrik alive!
