### ISSUE TITLE
Upgrade to Beta1 -> lost control of Joomla

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#496]
**To Reproduce**
Upgrade notification received 
Just selected 1st item (Fabrik component), as I knew from Alpha 3 update others won't work

**Expected behavior**

**Actual behavior**
**Can't do anything.** All actions I try stop with a Fabrik error.
It is even not possible to log out of Joomla...

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18248764/200165007-8a9838f3-65d7-4861-8bbd-c8651620f478.png)

**Additional context**

**Comment by skurvish** [comment]
You got in too quickly, I haven't announced it yet. You need to install the full package as there are database changes. The package link will be available with the announcement.

**Comment by skurvish** [comment]
Package is available now, link in tester instructions in the wiki.

**Comment by trob** [comment]
@wezetel : Which "upgrade notification"? I can't see any in Joomla.

**Comment by wezetel** [comment]
You didn't announce it, but Joomla did :-)
As I can't use Joomls update mechanism now, I need to find a way to get rid of the error.
Any proposal which part I should upload manually to get access again to Joomla?

**Comment by skurvish** [comment]
Do you have access to phpmyadmin? If so disable the fabrik system plugin in the #__extensions table.

**Comment by wezetel** [comment]
@trob I have got the standard Joomla notification, that there are updates available. No idea, why you can't see it (probably a mountain hinders your Joomla :-) )
@skurvish Thanks a lot, that did the trick. Now I have installed Beta1 successfully.

**Comment by trob** [comment]
So closing this one
