### ISSUE TITLE
Few sticky DB tables after uninstalling beta1

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#497]
**To Reproduce**
Install beta1 (new installation, no Farik before)
Uninstall it

**Expected behavior**

all #__fabrik_ tables gone from DB; 

Edit: #__fabrik_comments contains user content (the comments) so better keep it?

**Actual behavior**

_comments, sequence, thumbs are still there

**Screenshots**

![image](https://user-images.githubusercontent.com/1045355/200168134-73ea426b-0646-4b46-aeaf-81645a4ab9b3.png)

**Additional context**

**Comment by joomlahenk** [comment]
How come #__fabrik_comments contains user content if you did a new installation, no Farik before ?

**Comment by skurvish** [comment]
Also, fabrik always deleted all tables on uninstall so that would include comments I would think.

**Comment by trob** [comment]
Some further tests:
_sequence table is dropped correctly if uninstalling only the sequence plugin.

So I think it's the order of uninstalling:
I checked all for uninstall and got a bunch error messages like "..not a folder..." etc.

Uninstalling the component already removes nearly all Fabrik files and folders, but keeps plugins/system, pluglins/content and modules and all entries in #_extensions.

So afterwards all plugins will uninstall but can't run plugin specific uninstall stuff because the folder is already gone.

Uninstalling the **Package** will do a clean uninstall (including _fabrik_comments etc.).

Maybe it's possible to have the Fabrik Package at top of the list?

`How come #__fabrik_comments contains user content if you did a new installation, no Farik before ?` Not in this installation but in other ones.

**Comment by joomlahenk** [comment]
AFAIK It's not possible to have the Fabrik Package at top of the list, this is Joomla. You only have the option to use search for that.
J! has a filter 'Select packages', but that is misleading. It does not select the Fabrik Package, but does the same as search for 'fabrik'. After that you still need to search the Fabrik Package.
Maybe suggest J! to change that?

**Comment by trob** [comment]
You can filter for Select Type=Package

So Select Type=Package + Select Package = FabrikPackage will show you exactly the Fabrik Package.

Maybe we can put this in some "Uninstall docu" - but actually you should never uninstall Fabrik ;-)

From my site we can close this. 
If you do the uninstall via the Package all Fabrik including all _fabrik_xxx is gone.

About the #_fabrik_comments:
I think the better way would be to have the comments stored in a table per form (like the repeat tables) and not all together in a _fabrik-meta-data-table - but this is an other issue/enhancement.

**Comment by skurvish** [comment]
Agreed, closing.
