### ISSUE TITLE
Update Col List plugin no Email sent

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#505]
**To Reproduce**
Update col list plugin > Email notification tab > Set "Email Address" field to user element field 
No email is sent on update.
I also tested a calc element in the "Email Address" field  to ensure the email address was being returned but no email sent either.
Hardcoding and email address into the "Or Email To" field sends an email with no issue.
Entering a element place holder e.g {aaa_claims___current_email} in the "Or Email To" field does not work either.

**Expected behavior**
Send email on update 

**Actual behavior**
No email sent

**Screenshots**

**Additional context**

**Comment by trob** [comment]
Did you try with _raw placeholder?

**Comment by ontargetWeb** [comment]
Tried the following in the "Or Email To" field using the calc element which is returning the email:
`$db = JFactory::getDbo();
$table = $db->quoteName('aaa_my_profile');
$jid = $db->quoteName('userid');
$email = 'email';
$query = "SELECT $email FROM $table WHERE $jid = '{aaa_claims___current_userid}'";
$db->setQuery($query);
$result = $db->loadResult();
return $result;`

return '{aaa_claims___current_email_raw}';
Eval = Yes

{aaa_claims___current_email_raw}
Eval = No

{aaa_claims___current_email_raw}
Eval = Yes

'{aaa_claims___current_email_raw}'
Eval = No

'{aaa_claims___current_email_raw}'
Eval = Yes

None of these send the email :(

**Comment by trob** [comment]
It's working fine.
But see the tooltips, you can't use placeholders.
![image](https://user-images.githubusercontent.com/1045355/200198739-3b0e19df-3df5-437d-a03a-a0c8808ed6b9.png)

**Comment by ontargetWeb** [comment]
@trob thanks for your help I tried with your code but still nothing is being sent (not in spam either)
I converted the calc field to a basic text element to capture the email and tried to send via the Email field.
No email is sent.
I tried "Or Email To" / eval = Yes and the following:
return $row->current_email;
and 
return $row->current_email_raw;
and
return $row->aaa_claims___current_email;
and
return $row->aaa_claims___current_email_raw;
No email is being sent with any of these.

<img width="690" alt="Screenshot 2022-11-07 at 11 38 40" src="https://user-images.githubusercontent.com/26169616/200301179-ddd576d8-f076-458d-b963-6d0e5e360231.png">

**Comment by ontargetWeb** [comment]
return $row->aaa_claims___current_email_raw; (calc element)
Eval = **Yes**
Set Email after Updates = **No** fixed the email issue!
