### ISSUE TITLE
Block User Input on Front End

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#507]
I have noticed that on the front end when a form is loading that it is possible for the user to do something before Fabrik has fully loaded. I think this might affect things like onLoad javascript actions and onLoad form plugins. I think I should add the blockUserInput script to the frontend as well.

Any objections?

**Comment by trob** [comment]
ok for me

**Comment by joomlahenk** [comment]
ok

**Comment by skurvish** [comment]
Fixed. Will be in beta2a
