### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by elmarra90** [joomlahenk/fabrik#508]
I just tried to install fabrik 4 on empty joomla 4.2.4 but without success.
I downloaded the package from here. [link](https://github.com/joomlahenk/fabrik/wiki/Tester-Instructions)
In Extensions and Install I load the previously downloaded zip file and I get the following error.
![errore fabrik](https://user-images.githubusercontent.com/74364336/200194998-7a5a0bcc-df92-41e3-b479-067be7d8d853.png)

**Comment by trob** [comment]
Are you sure you downloaded 
https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta1.zip
?

**Comment by elmarra90** [comment]
You downloaded from that link.
I then went into system extensions, and installed it from the zip file I just downloaded.
I get that error.

**Comment by trob** [comment]
Please download again and try again. Maybe something got corrupted.
I did the installation several times without error.

**Comment by elmarra90** [comment]
I'm doing.
but the download is very slow.
I'll let you know as soon as it finishes

**Comment by trob** [comment]
Additionally check in System/Systeminformations/Folderpermissions if all your folders are writable.

**Comment by elmarra90** [comment]
> Additionally check in System/Systeminformations/Folderpermissions if all your folders are writable.

All writable
Downloaded again and I get the same error.
Seems like a problem with lib
`Pacchetto Installazione: si è verificato un errore nell'installazione di un'estensione: lib_fabrik_4.0beta1.zip`

**Comment by elmarra90** [comment]
Is the correct installation procedure to download the zip file from that site?
And upload it as is in
-system
-extensions
-upload package file?

**Comment by trob** [comment]
Yes.
Download this file https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta1.zip
then install this downloaded pkg_fabrik_4.0beta1.zip via "upload package file"

The lib lib_fabrik_4.0beta1.zip (included in pkg_fabrik_4.0beta1.zip) is very big (> 60MB), make sure your php limits are set big enough.

I just downloaded the package again and installed it on J!4.2.4/php8.1.6 it without error.

Do you have enough disk space (zio must be unpacked)?

Some php settings to check (my values with working installation):

![image](https://user-images.githubusercontent.com/1045355/200197686-4fc61f7f-b130-4fc5-a9c9-fdecac0c597e.png)

post_max_size | 80M
upload_max_filesize | 80M

**Comment by elmarra90** [comment]
> Download this file https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta1.zip then install this downloaded pkg_fabrik_4.0beta1.zip via "upload package file"
> 
The php settings were ok
I solved it by downloading the package from the link again and it worked.
It used to be very slow in downloading .. maybe something was lost.
Thank you
