### ISSUE TITLE
Error instaling beta1

### ISSUE THREAD

**Issue by gwstyles** [joomlahenk/fabrik#510]
Uninstalled alpha 3 and tried to install beta1.

JInstaller: :Install: Can't find Joomla XML setup file.
danger
Unable to detect manifest file.
No problem with alpha 3, php 8.1  Joomla 4.2.4 vanilla. Using Cassiopeia.

**Comment by trob** [comment]
beta1 downloaded from https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta1.zip ?

**Comment by gwstyles** [comment]
I first downloaded from git, I have now downloaded from the link above and it installed OK. Time to play with it. Thanks for the link trob.

**Comment by trob** [comment]
See https://github.com/joomlahenk/fabrik/wiki/Tester-Instructions
