### ISSUE TITLE
edititing elements causes a hang in admin

### ISSUE THREAD

**Issue by gwstyles** [joomlahenk/fabrik#518]
Alpha 3, J 4.2.5 , php 8.1.11

Feedback.
When editing an element the back end hangs.
example= change a textarea (ph) element to a yes/no , when you save changes the page displays "item saved"
"update field structure for ph from  MEDIUM TEXT to TEXT  "  ? it was changed to a yes / no.
Now the page is no longer responsive,you can not do anything,go back , refresh,exit...
The only solution is to manually change the url to xxx/administrator and enter and then you go to a normal admin page. Now it is necessary to check in the fabrik db and then everything has worked as it should.
I think this is a bug.

**Comment by gwstyles** [comment]
![screen-dump](https://user-images.githubusercontent.com/89599900/201331905-ce74895c-cf28-4541-be56-8a84aaa802f8.jpg)
A screen shot of the problem.

**Comment by trob** [comment]
Can you please update to the latest version (now beta) + have a look at https://github.com/joomlahenk/fabrik/wiki/Changelog + 
+ closed issues + (if you want) https://github.com/joomlahenk/fabrik/wiki/Testing-a-fix?

See https://github.com/joomlahenk/fabrik/issues/489
