### ISSUE TITLE
Spinner again: cron php plugin

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#521]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Create cron php plugin
Select the list to work on.

**Expected behavior**

**Actual behavior**
See screenshot

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18248764/201402979-327965a4-39e5-4ee6-8a57-5cf7bb6de914.png)

**Additional context**
Not really important, as it works as expected

**Comment by trob** [comment]
Known issue, see https://github.com/joomlahenk/fabrik/issues/483 (viz in this case)

**Comment by trob** [comment]
I mentioned it in https://github.com/joomlahenk/fabrik/issues/483 (Sticky spinner below viz table selection and php cron), so closing this one
