### ISSUE TITLE
Upgrading Fabrik 4 via Git

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#529]
Hi
Sorry if this is a stupid and obvious question....
To date I have been applying commits directly to files in my Fabrik  4 installation.
In Fabrik 3 to get all commits updated on my installation what i would normally do is download the git files and unzip them in my project directory (overwriting / updating all fabrik files and directories). Is this what you recommend for Fabrik 4 too?

**Comment by skurvish** [comment]
At this time we do not have updating directly from git. The only means of updating is via the install package.

**Comment by ontargetWeb** [comment]
Ok why is the joomlahenk git repo <>Code menu item now showing the old Fabrik 3 files or am i missing something? https://github.com/joomlahenk/fabrik
How can i now access the Fabrik 4 code?

**Comment by wezetel** [comment]
Best is to go to the tester instructions in the wiki. The link is there to the Beta1.zip

**Comment by wezetel** [comment]
https://github.com/joomlahenk/fabrik/pulls?q=is%3Apr+is%3Aclosed

**Comment by Sophist-UK** [comment]
Yes - as far as several of us can see the henk40 branch has disappeared. It might have been deleted, though why anyone would want to do this is beyond me, or it might be some sort of glitch by Github. But I am assuming that it can be restored by a new push or from a Github backup or possibly something else.

**Comment by ontargetWeb** [comment]
Hi @trob @joomlahenk I lost track of which commits i have added to my fabrik 4 project. Does the beta1 installer pkg have all the latest commits in it ?

**Comment by trob** [comment]
No, the changelog since beta1 is here https://github.com/joomlahenk/fabrik/wiki/Changelog

**Comment by ontargetWeb** [comment]
ok thanks

**Comment by skurvish** [comment]
Updating from git is not supported at this time. Primarily due to the sql tables changing and these changes do not get reflected doing a git update. When and if this is possible we will let everyone know.
