### ISSUE TITLE
Cron and visualizations: list selection won't stay

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#53]
Save in the DB but if opening the cron email for editing it's empty and has to be selected again.

Logging to admin mail throws
Message body empty
if no mail is sent.

**Comment by joomlahenk** [comment]
Working now??

**Comment by trob** [comment]
not at home, can't test

**Comment by trob** [comment]
Empty log message is fixed with https://github.com/joomlahenk/fabrik/pull/56

Missing selected list on edit is a general cron issue. I assume some JS issue, it seems watching the connection instead of setting the existing table id to 'selected'.

**Comment by joomlahenk** [comment]
I entered 2 new lists and I can select them in the cron. Don't have a cron plugin so that's all I could test.

**Comment by trob** [comment]
Yes, you can select and save, it's ok in the database and the cron is working. But if you then edit your scheduled task the selected list is gone and you have to reselect before saving againg.

**Comment by joomlahenk** [comment]
OK, I didn't get that far yet, didn't even expect that it works. Did you compare with J!3 ? Because I never had to use a list in the cron, I only use the php plugin where it's not needed.

**Comment by trob** [comment]
The list selection in crons and vizs won't stay. 
It's saved correctly in #__fabrik_cron/visualisation in the params but obviously not loaded correctly on edit.
It's loading all lists but didn't set a "selected" one.

So e.g. in an existing fullcalendar viz the selected elements for start date etc won't show until the list is re-selected manually.

**Comment by skurvish** [comment]
I can confirm this behaviour. 

When I create a menu link to the fullcalendar vis the vis opens OK and the calendar displays. But there are issues with add and edit an event on the calendar. Getting a JS error looking for a form title. Will need some investigation.

**Comment by skurvish** [comment]
The javascript error on form title is a red herring, it is a result of something else. I am struggling with the vis parameters not loading. Once the full-calendar vis plugin loads initially, there are 2 ajax events. The first populates the database and table dropdowns, the second populates everything from the start date onward. The first completes and the database table dropdown is populated. The second is never initiated. These requests go through a request queuing mechanism so it is very difficult to determine what is supposed to happen next.

Anyway, still struggling...

**Comment by trob** [comment]
`I am struggling with the vis parameters not loading.`
It's this missing table selection on edit. As soon as you select the missing table manually (the one which was selected the last time) the options will populate correctly.
And the viz is running pretty fine in frontend: the only issue I see is that the start date is not populated in the small popup (the one with edit/view link). But the title (from the selected "Label" element) is shown and the links are working, also the limit options etc.

**Comment by skurvish** [comment]
I need to minify the javascript file. For initial testing put &fabrikdebug=1 at the end of the url

**Comment by trob** [comment]
Ah, I didn't realize that it's an open PR. Yes, with opt.id == this.options.value it's loading the lists in viz and cron (still showing the spinner but this doesn't hurt).
I fixed the same == instead of === in list.js https://github.com/joomlahenk/fabrik/pull/116/commits/e359b6abaa7daac0b7be6e6faeb038f5c8beb71d, maybe there are some more...
BTW: with debugging = "Debug JS" you don't need to add fabrikdebug=1, it's running the uncompressed JSs in this case

**Comment by trob** [comment]
Fixed with https://github.com/joomlahenk/fabrik/pull/133/commits/49bf7dc759c8be7e964c79558a0152c65eeed074
