### ISSUE TITLE
Googlemap element works in list, not in form

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#530]
I have a list of event locations with addresses and maps generated from the addres. The Google maps elements are set to 'Use static map' to full.
Through a list database join I can use the addresses and maps in an events list.

In the events list, all the fields from the joined list including the maps can be displayed.

If an event is clicked and the form opens (modal or non-modal), all the other fields from the locations list are shown.
But the map is only shown when I unlink it from the parent and set the 'Use static map' either to Static or Static (cached).
The user then has no controls the (cannot zoom in, etc). 
When I set it to full, the map still shows in the list but in the form it's a blank square.

**Comment by trob** [comment]
I can't replicate.
The joined googlemap element with 'use static map' = full and geocoding on is also working in the form.

As you referring to "Static": this is for readonly. 
Do you mean details view instead of form view? 
Is this behaviour only if the element is in a joined group or is it also in the original (event locations) details view?

**Comment by EricdeWaal** [comment]
To start with the last question: in the locations list the Googlemaps element is set to "Full". In the associated form it works as expected (the users who have access to that list and form can create a new location with address and map, zoom in and out, set options like Traffic, Satellite, Street view, etc).

Yes I mean Details view of the events list (that uses the form, right?). There in list view the maps are shown whatever the settings of the (decoupled) Googlemaps element: Static, Static (cached), Full.
But as soon as a row is clicked, Full does not work anymore and shows a blank square in stead of the map. The other 2 options do show a map, but with no "extra's", like zoom in and out, Traffic, Satellite, Street view, etc.

**Comment by trob** [comment]
[googlemapsDetailsView.zip](https://github.com/joomlahenk/fabrik/files/10226717/googlemapsDetailsView.zip)
Can you try this?
It's only the uncompressed file so make sure to have "Debug JS" enabled in Fabrik Options/Debugging

**Comment by wezetel** [comment]
At least for me this seems to work now. Not sure if @EricdeWaal can also confirm.
The control parameter doesn't work for large/large map control, but this seems to be the same in F3 as mentioned in the F3 wiki.

**Comment by EricdeWaal** [comment]
Yes. also for me this solves the issues!

**Comment by skurvish** [comment]
Thanks to you both for testing and getting back to us with the status.
