### ISSUE TITLE
Please add emailexists validation

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#533]
Could the emailexists validation rule please be added to the F4 set?
Thanks in advance!

**Comment by skurvish** [comment]
Yes, it is one I did some testing on earlier but need to get back to.

**Comment by skurvish** [comment]
Eric, can you test the attached please. I have never used it so am unsure if it is doing what it is supposed to. Thanks.
[emailexists.zip](https://github.com/joomlahenk/fabrik/files/10096941/emailexists.zip)

**Comment by EricdeWaal** [comment]
Hi Alex, yes this works as in Fabrik 3, thnks!

**Comment by skurvish** [comment]
OK, thanks. I will add it to the install package for the next beta.
