### ISSUE TITLE
JDate field problems

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#534]
I set the following: 
Time selector No
24h hrs: Yes
Store Date As: Local time
List: d-m-Y
Form format: d-m-Y
Default to current date: No
Always return today's date: No
Allow typing in field: Yes

When I type: 1-1-2000 and the field loses focus, it's set to today's date.
Using 01-01-2000 it becomes a different date, like 14-05-2024, every time the field loses focus, so not consistent.

When I use the calendar pop-up, it seems to work, but that's a lot of clicking before you have 1-1-2000!

**Comment by EricdeWaal** [comment]
Addition: the good old Date element works wel when typing in the field. No strange date conversions, and even the popup year list selector seems to be better, although it's short, small and does not display all years, it uses a 2 year interval.

**Comment by skurvish** [comment]
Thanks Eric, we will have a look.

**Comment by trob** [comment]
Is this still the case?
I can't replicate with the current version.

**Comment by EricdeWaal** [comment]
It seems that most of the issues are gone now, that's good news. But neither element is perfect.
1) the Jdate element.
there is no decent way to set the year from the pop-up, if it is lets say 40 years ago. Click 40 times?
2) the date element
The year selection in the pop-up is very clumsy and hidden
For both, there is no validation on typing in the field, users can enter 01-13-2022 or 31-02-2000. The element does a calculation and end up a few days later.

**Comment by skurvish** [comment]
Is this a different behavior from F3?

**Comment by EricdeWaal** [comment]
No, not really, but very annoYng!

**Comment by skurvish** [comment]
Closing as working as before. Maybe at some point in the future we can fix it.
