### ISSUE TITLE
calc element not rendering html

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#535]
Hi try doing the following in a calc element
```
$hello = "foobar";
return "<h1>" . $hello . "</h1>";
```
Instead of rendering the html it shows 
```<h1>foobar</h1>```

<img width="819" alt="Screenshot 2022-11-18 at 14 48 42" src="https://user-images.githubusercontent.com/26169616/202732057-7dbcaa7a-9e56-4183-ba76-5e6edcb4c0f2.png">

Is this a php8.1 thing or a F4 bug? This works fine on F3 and the html gets rendered.
also the area for the text that is being returned by the calc element is very small and cuts off the output 
w-auto {
    width: auto!important;
}
Could use 100% here instead?

**Comment by trob** [comment]
https://github.com/joomlahenk/fabrik/pull/484/files
This should be already in beta1.
Do you have these files?

**Comment by ontargetWeb** [comment]
Ok that commit wasnt in @skurvish 's cumulative package
I made the changes to my files but now the calc comes back blank
Here is the code
`$id = '{aaa_participant_claim___school_roll_raw}';
//added this if else to allow NCSE ETB schools to claim 
$category = '{aaa_participant_claim___category}';

if ($id[0] == 7 && $category != 'NCSE')
{
echo "<span style='color:red;'>Sorry this is an ETB School Roll Number. You cannot claim using this system</span>"; 
return false;
}

else {
$db = JFactory::getDbo();
$query = $db->getQuery(true);
$query
    //->select(array('schoolName', 'address1', 'address2', 'county' ,'eircode'))
    ->select(array('schoolName', 'address2', 'county' ,'eircode'))
    ->from('aaa_schools')
    ->where('schoolRoll = ' . $db->quote($id));
$db->setQuery($query);
$rows = $db->loadObjectList();
 
$list = array();
foreach ($rows as $row)
{
    $list[] = "<li> School: " . $row->schoolName . "</li> " . "<li>Address: " . $row->address2 . "</li>" ."<li>County: " . $row->county . "</li>" . "<li> Eircode: " . $row->eircode . "</li> ";
}
return "<ul>" . implode($list) . "</ul>";
}`

**Comment by trob** [comment]
`Ok that commit wasnt in @skurvish 's cumulative package` Yup, because it's already in beta1. So if you didn't have this code, did you install beta1 at all?

**Comment by ontargetWeb** [comment]
I'm reopening this issue, as I know have beta1 installed.

The calc element was successfully returning a database join output in Alpha3 version.
my dbjoin element = aaa_my_profile___school_roll

My calc element is a simple return like this:
```
$id = '{aaa_my_profile___school_roll_raw}';
return $id;
```
Ajax calc = Yes
Now the output is blank  var_dump returns an empty string.

**Comment by skurvish** [comment]
@ontargetWeb Can you try this again with beta3 and unzip the attached cululative into your joomla root.
[cumulative_12_14_2022.zip](https://github.com/joomlahenk/fabrik/files/10227834/cumulative_12_14_2022.zip)

**Comment by ontargetWeb** [comment]
Hi Skurvish yes i can confirm it works in a calc 
`$hello = "foobar";
return "<h1>" . $hello . "</h1>";`

**Comment by ontargetWeb** [comment]
The cumulative package you provided leads to an error:
**0
Class "Factory" not found**

The Fabrik4Beta03 worked fine with the `$hello = "foobar"; return "<h1>" . $hello . "</h1>";`
