### ISSUE TITLE
Unable to create a list from import

### ISSUE THREAD

**Issue by dimoss** [joomlahenk/fabrik#539]
Hi,

I get the following error when i try to create a new list from import using a .csv
![image](https://user-images.githubusercontent.com/10183465/202847440-7ba55285-4f20-46d7-af87-df97abaf8add.png)

**Comment by skurvish** [comment]
@dimoss would you be so kind as to attach a sample csv file. Thanks so much.

**Comment by dimoss** [comment]
@skurvish please find attached.
[fab_countries.csv](https://github.com/joomlahenk/fabrik/files/10073277/fab_countries.csv)

**Comment by skurvish** [comment]
This is going to take a while. The selected table name is not being populated into the model. i am going to have to go back to a F3 version to figure out where that is supposed to happen, then figure out why it isn't happening in F4.

**Comment by skurvish** [comment]
OK, I know what the problem is and where it is occurring. Having trouble trying to fix it though. Stand by.

**Comment by joomlahenk** [comment]
@dimoss : What exactly did you enter as the DB table name and List label ?

**Comment by dimoss** [comment]
> @dimoss : What exactly did you enter as the DB table name and List label ?

Table name: fab_countries
List label: Countries

**Comment by trob** [comment]
It seems nor @joomlahenk  nor I can replicate.
What are the structure settings of your #_fabrik_lists table?

Is this in a vanilla J!4 or an updated J!3/Fabrik3?

**Comment by dimoss** [comment]
@trob it's a vanila J!4

**Comment by joomlahenk** [comment]
@dimoss : The error that you have is not expected to occur if you do an import, but may more likely occur during an export. 
I am still unable to replicate. 
Is the table fab_countries a new table that does not already exists ?
What are the exact steps you did before you get this error ?

**Comment by dimoss** [comment]
> @dimoss : The error that you have is not expected to occur if you do an import, but may more likely occur during an export. I am still unable to replicate. Is the table fab_countries a new table that does not already exists ? What are the exact steps you did before you get this error ?

@joomlahenk The table is a new table. Doesn't exit in the database.
On the lists I click ib the Import and I try to create the new list
![image](https://user-images.githubusercontent.com/10183465/204024276-aa63fb77-c810-45f3-ba5c-f4ad9347c6c3.png)

**Comment by trob** [comment]
Strange. It seems only @skurvish can replicate.
I created a list via Import with your csv without issue
![image](https://user-images.githubusercontent.com/1045355/204027662-696d7338-caeb-4309-937e-61aa5bfcc4ae.png)


Did you set any option beside DB table name and List label?

What did you select as field types?

**Comment by dimoss** [comment]
@trob DB table name, List label, Field delimiter

**Comment by trob** [comment]
Which field delimiter? And why? (Your CSV has the standard settings).
Does the error occure already if you click "Continue" or do you get the field type selection list?

**Comment by dimoss** [comment]
> Which field delimiter? And why? (Your CSV has the standard settings). Does the error occure already if you click "Continue" in this first import form or do you get the field type selection list?

Yes. Field delimiter is by default.
It happens after i get the field type selection list where i select the element types.
I get teh error and it creates a record on the fabrik list table and a record on teh fabrik form table. Nothing in groups, nothing in elements.

**Comment by skurvish** [comment]
@dimoss can you unzip the attached into the root of your joomla installation and try the import again? I am now able to import successfully with this change. Still no idea how the others got it to work. At any rate, if yours still does not work I may ask you to get me an akeeba backup of your installation so I can troubleshoot it locally.
[import.zip](https://github.com/joomlahenk/fabrik/files/10096918/import.zip)

**Comment by dimoss** [comment]
@skurvish the import worked fine with the file you shared. Thank you!
