### ISSUE TITLE
GitHub WIKI

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#54]
I created a page for keeping track of (partly) tested plugins etc

**Comment by joomlahenk** [comment]
Where to find it?

**Comment by trob** [comment]
https://github.com/joomlahenk/fabrik/wiki
![image](https://user-images.githubusercontent.com/1045355/178152387-3144c2dd-c1e2-4887-b561-573bf5e95f52.png)

**Comment by joomlahenk** [comment]
Of course, didn't expect it there but perfect. Maybe something on the homepage?
Missing plugin jdate = ok
