### ISSUE TITLE
Birthday element generates deprecated wornings

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#540]
On opening of a form with the birthday element, these warnings are shown:

Deprecated: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/plugins/fabrik_element/birthday/birthday.php on line 269

Deprecated: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/plugins/fabrik_element/birthday/birthday.php on line 274

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/plugins/fabrik_element/birthday/birthday.php on line 429

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/plugins/fabrik_element/birthday/birthday.php on line 429

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/plugins/fabrik_element/birthday/birthday.php on line 429

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/plugins/fabrik_element/birthday/birthday.php on line 429

**Comment by EricdeWaal** [comment]
In my birthday.php line 252 is:
$value = strstr($value, ',') ? array_reverse(explode(',', $value)) : explode('-', $value);
How should I insert your code? And are the hrs:min:seconds necessary as the element will be set to 'date' in the database?

Thanks in advance!

**Comment by trob** [comment]
Sorry, insert it before line 252
(This is only for the "internal" use, and it's only for "deprecated")

But there a several other clitches with birthday element if not using the default settings...

**Comment by EricdeWaal** [comment]
With (part of) my birthday.php looking like this:
		}
		else
		{
			// Weirdness for failed validation
			in_array($value, $aNullDates)) $value = '0000-00-00 00:00:00';
			$value = strstr($value, ',') ? array_reverse(explode(',', $value)) : explode('-', $value);
			$yearValue = FArrayHelper::getValue($value, 0);
			$monthValue = FArrayHelper::getValue($value, 1);
			$dayValue = FArrayHelper::getValue($value, 2);
			$errorCSS = (isset($this->_elementError) && $this->_elementError != '') ? ' elementErrorHighlight' : '';
			$advancedClass = $this->getAdvancedSelectClass();

I get an error opening the element in the backend plus in the frontend:
Unclosed '{' on line 250 does not match ')'

**Comment by trob** [comment]
Ok, I missed a superfluous linebreak in my copy/paste. So

```
...
          else
		{
			if (in_array($value, $aNullDates)) $value = '0000-00-00'; 
 
			// Weirdness for failed validation
....
```

But as I said: 
This issue is only a deprecated warning (will be gone if you don't set error reporting to max and there are several other deprecated warnings coming from Joomla)
And there are still other issues in the birthday element.

**Comment by EricdeWaal** [comment]
I can confirm this works and the warnings are gone, thanks!
