### ISSUE TITLE
ASC and DESC arrows missing

### ISSUE THREAD

**Issue by dimoss** [joomlahenk/fabrik#543]
Element allow ordering works fine.
However fa-sort-asc and fa-sort-desc icons are missing.
fa-sort is ok,
I am using Cassiopeia on clean J4 installation

**Comment by dimoss** [comment]
Similar issue with fa-refresh on Clear Filters.

**Comment by dimoss** [comment]
At the moment I solved it with an list layout override replacing the icon naming in the files below:
fabrik-filters.php -> instead of 'refresh' i used 'undo'
fabrik-order-heading.php ->  instead of 'asc' / 'desc' I used 'up' / 'down'

**Comment by trob** [comment]
Thanks. Yes, there's no fa-sort-asc etc. and additionally Cassiopeia doesn't support all fa icons
But strange enough in F3 asc uses the down-arrow (and vice versa).

**Comment by dimoss** [comment]
@trob Installed the Beta 2. ASC/DESC buttons are now ok and thanks!

Possible to fix also fa-refresh issue on 'Clear filters'? At the moment I used 'fa-undo' on overidde. Thanks in advance!

**Comment by trob** [comment]
Try with [ListFilters.zip](https://github.com/joomlahenk/fabrik/files/10117565/ListFilters.zip)

**Comment by dimoss** [comment]
> Try with [ListFilters.zip](https://github.com/joomlahenk/fabrik/files/10117565/ListFilters.zip)

Hi Troester
I can see the fa-refresh icon now. However it seems that there were some changes in the css styling
![image](https://user-images.githubusercontent.com/10183465/204730307-7e3b825c-5d8b-441d-82db-2b2df589b13e.png)

**Comment by trob** [comment]
>  it seems that there were some changes in the css styling

Yes. 1 column list filter is now also Bootstrap5 and got accessibility labels.
But I concentrated to much on the multi column filter. I'll change the 1-column filter label to col-sm-2 analogue to labels in form view in components\com_fabrik\layouts\list\fabrik-filters-bootstrap.php around line 50
```
                    <div class="row mt-3" data-filter-row="$key">
                        <div class="col-sm-2 "><label for={$filter->id} >{$filter->label}</label></div>
                        <div class="col-sm-10">{$filter->element}</div>
                    </div>
```

**Comment by dimoss** [comment]
Thanks @trob
