### ISSUE TITLE
List filter display/design

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#544]
Define two fields as dropdown filter elements.

Leave list->filter->filter columns on initial value (1)
![grafik](https://user-images.githubusercontent.com/18248764/202913677-7a10a186-4a33-42fa-b3c1-bb7fdbb33134.png)

Change value of filter columns to 2 
![grafik](https://user-images.githubusercontent.com/18248764/202913726-a061c021-eb4c-4892-884b-db771c3bcb73.png)
I expected the two filters to be in a row.

**In addition:**

- The filter section only spans on half of the row
- The reset filter text gets an inline styling (text-align:right), which from my knowledge can't be overwritten with a custom css

**Comment by trob** [comment]
Yup, filter block needs some BS5 etc added, it's on my list.

**Comment by trob** [comment]
Try with [ListFilters.zip](https://github.com/joomlahenk/fabrik/files/10117565/ListFilters.zip)

**Comment by wezetel** [comment]
Thanks for the !important tip
The multi column filters work well. 
What I need to check is, how I can apply the same width to all dropdowns, because currently the width seems to be dependent on the width of the values in the list and so resulting in different sizes
The element settings -> list settings -> filter don't do it. Length and filter class fields have no influence on the display.

**Comment by trob** [comment]
element settings -> list view settings -> filter settings ->Filter class

**Comment by wezetel** [comment]
As mentioned: filter class doesn't do it, but I will find a way....

**Comment by trob** [comment]
Let me check.

**Comment by wezetel** [comment]
The fix solves the different widths of the dropdown (at least on wider displays..)
The filter class doesn't have an influence, but for me this is ok and not worth looking deeper.
Thank you!

**Comment by wezetel** [comment]
You're a hero! Nothing to complain. It works as expected.
