### ISSUE TITLE
Custom CSS (custom_css.php)

### ISSUE THREAD

**Issue by dimoss** [joomlahenk/fabrik#545]
I have added the following into custom_css.php to disable the list row color change:

#listform_$c .oddRow0 td {
    background-color: #FFFFFF;
}
#listform_$c .oddRow1 td {
    background-color: #FFFFFF;
}

It works fine in F3 in all my apps but seems not in Cassiopeia (clean J4 installation) with F4. Maybe not an issue and could be solved differently but I would like to reported.

**Comment by wezetel** [comment]
Hi dimoss, not sure, why you didn't just make the apropriate setting in the list settings:
![grafik](https://user-images.githubusercontent.com/18248764/202919272-cef36c18-292e-4a4e-8633-d0406c371aab.png)

**Comment by dimoss** [comment]
> Hi dimoss, not sure, why you didn't just make the apropriate setting in the list settings (layout tab): ![grafik](https://user-images.githubusercontent.com/18248764/202919272-cef36c18-292e-4a4e-8633-d0406c371aab.png)

I sware i tried this and didn't work! But I removed the code and re-done and it works. Thanks @wezetel

**Comment by wezetel** [comment]
Nonetheless, I'm wondering, why the custom_css.php didn't work....

**Comment by trob** [comment]
custom CSS: I just tried, it's working fine here.
Maybe some typo in your file ?
```
header('Content-type: text/css');
$c = $_REQUEST['c'];
echo <<<EOT
/* BEGIN - Your CSS styling starts here */

#listform_$c {
	margin-top: 25px !important;
}
#listform_$c .oddRow0 td {
background-color: yellow;}
#listform_$c .oddRow1 td {
background-color: silver;}

/* END - Your CSS styling ends here */
EOT;

```

**Comment by dimoss** [comment]
Yes. Works. Thanks.
Seems it was not configured well on list settings with the Stripe.
