### ISSUE TITLE
Problems trying to update Fabrik

### ISSUE THREAD

**Issue by isidoroi** [joomlahenk/fabrik#546]
In an attempt to update Fabrik as indicated, I get the following error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF EXISTS `cae_fabrik_sequences` ALTER `table_name` SET DEFAULT ''' at line 1

**Comment by trob** [comment]
What did you try exactly?

**Comment by skurvish** [comment]
This is related to #547

**Comment by skurvish** [comment]
@isidoroi can you try installing this plugin and once it is installed try and reinstall beta1. Let us know the outcome. Thanks.
[sequence.zip](https://github.com/joomlahenk/fabrik/files/10070783/sequence.zip)

**Comment by skurvish** [comment]
Yes, I was aware there were a couple of other plugins with the same issue. I wanted to ensure that the first one worked. i will go ahead and update the others now.

**Comment by isidoroi** [comment]
> Yes, I was aware there were a couple of other plugins with the same issue. I wanted to ensure that the first one worked. i will go ahead and update the others now.

Ok, but will you post here or do we have to wait for a new beta? Thank you in advance

**Comment by skurvish** [comment]
@isidoroi quick question, at what point did you install the above attached zip file? Before or after trying to install beta2?

**Comment by skurvish** [comment]
Never mind, I will make additional zip installs for the other plugins which you can install and that should allow you to install beta2. Stand by.

**Comment by skurvish** [comment]
install these.
[rating.zip](https://github.com/joomlahenk/fabrik/files/10093154/rating.zip)
[thumbs.zip](https://github.com/joomlahenk/fabrik/files/10093161/thumbs.zip)
[subscriptions.zip](https://github.com/joomlahenk/fabrik/files/10093187/subscriptions.zip)
[notification.zip](https://github.com/joomlahenk/fabrik/files/10093188/notification.zip)
[log.zip](https://github.com/joomlahenk/fabrik/files/10093189/log.zip)
[comment.zip](https://github.com/joomlahenk/fabrik/files/10093193/comment.zip)
[consent.zip](https://github.com/joomlahenk/fabrik/files/10093197/consent.zip)

**Comment by fstorch** [comment]
In a J3 upgraded to J4 Wamp Installation with no previous Fabrik 4 Alpha or Beta installed (All Fabrik still disabled) got errors to install Beta 2. Then tried above zips. Some still fail.
**comment.zip** fails with
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `notify` TINYINT(1) NOT NULL DEFAULT 0' at line 1

**notification.zip** fails with
Unknown column 'label' in 'jcc_fabrik_notification'

**subscription.zip** fails with
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE `jcc_fabrik_subs_users` MODIFY `time_date` datetime NULL DEFAULT NUL' at line 23

All others installed fine.

**Comment by skurvish** [comment]
I will be releasing a beta2a later today which should correct these issues.

**Comment by skurvish** [comment]
Beta2a is available now.

**Comment by fstorch** [comment]
Sorry, upgraded J4 still failing in comments:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `notify` TINYINT(1) NOT NULL DEFAULT 0' at line 1
Paket Update: Bei der Installation der Erweiterung trat ein Fehler auf: plg_fabrik_form_comment_4.0beta2a.zip
```

**Comment by fstorch** [comment]
FWIW there is another error:
![grafik](https://user-images.githubusercontent.com/34415681/204109077-1a2752e3-fadf-40d9-8f46-66d33715a179.png)

**Comment by skurvish** [comment]
can you try this please? https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta2b.zip

**Comment by fstorch** [comment]
Different error at install:
```
BLOB, TEXT, GEOMETRY or JSON column 'default' can't have a default value
Package Update: There was an error installing an extension: com_fabrik_4.0beta2b.zip
danger
Error installing package
```
Database:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''#__fabrik_ratings WHERE field = 'listid' AND UPPER(type) REGEXP '^INT([(][0-9]+' at line 1

and
![grafik](https://user-images.githubusercontent.com/34415681/204112275-43cca321-e91a-4483-a032-18f7428e1977.png)

**Comment by fstorch** [comment]
Did a Repair of the Database which got rid of most errors except the ratings.
I actually used that and it deems to be part of the beta.
But after checking back with 100% of my users (aka my wife), she confirmed that she never used it.
So I dropped it and reinstalled beta2b.
Just warnings left:
```
Warning
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\css
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\js
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\sef_ext
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\dbdriver
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\driver
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\query
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\fabrik
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]\components\com_fabrik\Document
success
Installation of the package was successful.
```
Database Maintenance remains at 
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''#__fabrik_ratings WHERE field = 'listid' AND UPPER(type) REGEXP '^INT([(][0-9]+' at line 1`

**Comment by skurvish** [comment]
Ratings is not supported. Closing this.
