### ISSUE TITLE
Updating to Beta errors

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#547]
When i install the Fabrik package  i get
an Install Error message about plg_fabrik_element_sequence.
So then i try to install the com_fabrik_4.0beta1.zip on its own
I then get
An error has occurred.
0 PLG_FABRIK_SYSTEM_AUTOLOAD_MISSING
And it completely disables my entire Joomla backend.

I never install Fabrik via installer as its always been error prone for me that is why i prefer to do a git / zip / override of my files.
Can you please provide a zip of the git files and put them in the wiki

**Comment by joomlahenk** [comment]
You need to install Fabrik 4 via the installer. Please read the wiki for more info.

**Comment by ontargetWeb** [comment]
> You need to install Fabrik 4 via the installer. Please read the wiki for more info.

I am using the installer as per wiki instructions

**Comment by ontargetWeb** [comment]
Ok due to multiple errors and attempts the only way I could upgrade form alpha to beta was by making a vanilla install of joomla > install the fabrik 4 beta package > zip the entire joomla-fabrik site (excluding images / configuration.php) > upload to my project and unzip.
Caution to anyone else doing this - if you have any 3rd party components or plugins in your joomla project you should uninstall them then reinstall before unpacking the joomla-fabrik zip. Not exactly an easy solution. 
The most robust method of upgrading fabrik is via the git files (which are currently in a private repo).

**Comment by skurvish** [comment]
Let's back up a bit. What was the original problem and what was the state of your installation at the time? Vanilla J4 or updgraded fro J3? Fabrik version at the time of installation of Beta1, and any other info you can provide.

I would like to try and replicate this issue before moving on to the next one.

**Comment by ontargetWeb** [comment]
I was running a J4 vanilla with FAlpha3
I tried to upgrade to F4beta using the installer package.
This didn't work (see above) so i made a fresh J4 install and uploaded the F4beta package to that which did work.
I then zipped this up and overwrote my j4Alpha3 project.

**Comment by trob** [comment]
The problem is plugins\fabrik_element\sequence\sql\updates\mysql\4.0.sqll
It seems you can't do ALTER TABLE **IF EXISTS**

**Comment by skurvish** [comment]
Interesting. I put that in there specifically. I will investigate further.

**Comment by trob** [comment]
At least my 10.4.24-MariaDB doesn't accept it and I found several questions addressing this - but no short solution.
e.g. https://stackoverflow.com/questions/64221547/how-do-i-check-if-table-exists-before-alter-table

**Comment by joomlahenk** [comment]
I thought I tested this ok, but seems not. Indeed you can't do ALTER TABLE IF EXISTS, I could not find this in the MYSQL doc.
Solution may be on https://stackoverflow.com/questions/16837134/alter-table-if-exists-or-create-if-doesnt

**Comment by skurvish** [comment]
I have played around a bunch and I think the best way to solve this would be to insert a create table if not exists in the update sql, and then follow it with the ALTER statements. If the table did not exist then the ALTER statements are redundant and will execute but will not cause any issues. If the table did exist then the ALTER statements will change the existing table.

I will go ahead and make these changes and test them. Let me know if anyone has another idea.

**Comment by skurvish** [comment]
That seems to work. I will ask the person in #546 to try out the plugin update.

**Comment by skurvish** [comment]
Hope to build a Beta2 today.

**Comment by trob** [comment]
Beta2 is out.

**Comment by skurvish** [comment]
I will be releasing a beta2a later today which should correct these issues.

**Comment by skurvish** [comment]
Beta2a is available now.

**Comment by skurvish** [comment]
Should now be fixed.
