### ISSUE TITLE
Save part-edited records Form leads to error 0 on clear

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#548]
Using J!4.2.5 and Fabrik Beta with the cumulative updates zip from the changelog applied.

In the form I have turned on **Save part-edited records.** for logged in users.
It's a multipage form.
When I log in as a user I get the message:
_It appears you have already started filling in this form. Your starting from the last page you visited. If you wish to restart the form press the 'clear' button._

When I click the clear button I get

```
0
urldecode(): Argument #1 ($string) must be of type string, array given
```

**Comment by skurvish** [comment]
First, is this for a new form or one that you had already started? i.e. is the "It appears..." message legitimate or incorrect? You do not say.

Can you turn full J1 debug on so we can get the stack trace and source file/line number where this is occurring? Likely a simple fix.

**Comment by ontargetWeb** [comment]
Thanks for the reply:

> First, is this for a new form or one that you had already started? i.e. is the "It appears..." message legitimate or incorrect? You do not say.
> 
Yes the message is correct as i had started filling the form and wished to go back to it to continue as its a large multipage form.
> Can you turn full J1 debug on so we can get the stack trace and source file/line number where this is occurring? Likely a simple fix.

Full Debug:
Deprecated: Function strftime() is deprecated in /home/otwddevacc/xxx/libraries/src/HTML/HTMLHelper.php on line 1076

Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /home/otwddevacc/xxx/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 114

Also I am getting a bunch eval'd debug on JFactory stuff e.g 
_An error has occurred with a eval'd field - please inform the web-site owner.    
Debug: Caught exception on eval of userid: Joomla\CMS\Factory::getUser() is deprecated. Load the user from the dependency injection container or via Joomla\CMS\Factory::getApplication()->getIdentity()._

So my code i am using is getting the user object in a field element eval
```
$user = JFactory::getUser();
$name = $user->get('name');
return $name;
```

I try to change it to use the non-deprecated Factory method https://docs.joomla.org/Accessing_the_current_user_object

```
use Joomla\CMS\Factory;
$user = Factory::getUser();
$name = $user->get('name');
return $name;`
```
But then i get the error message
**0 Class "Factory" not found**

**Comment by skurvish** [comment]
@ontargetWeb can you retry this with joomla debug enabled so we can get the full call stack please.

Where do you have the use statement? It needs to be before any executable code other than the defined if you have one.

**Comment by skurvish** [comment]
@ontargetWeb the reason you get the class Factory not found is because Fabrik is stripping out the slashes in the use statement prior to passing the code to php eval. For now simply use double slashes in the use statements and that will work for you.

**Comment by skurvish** [comment]
Oh, and getting the name is easies tlike this:

return \\Joomla\\CMS\\Factory::getUser()->name;

**Comment by skurvish** [comment]
@ontargetWeb can you try unzipping this into your joomla root and trying the clear again. Let me know how it goes.
[cumulative_12_11_2022.zip](https://github.com/joomlahenk/fabrik/files/10202222/cumulative_12_11_2022.zip)

**Comment by ontargetWeb** [comment]
Thanks for the comments,
I will make those changes and revert

**Comment by skurvish** [comment]
Also, as mentioned elsewhere, you need to double slash all classname paths. Fabrik does a removeslashes to convert escaped data back into unescaped data on all evals, defaults etc. Double slashing ensures that the classname path remains intact through this process. So make the suggested line `\\Factory::getUser()->name;`

**Comment by skurvish** [comment]
@ontargetWeb were you able to test this yet?

**Comment by skurvish** [comment]
Fixed in Beta4
