### ISSUE TITLE
Hidden elements validation

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#550]
I have several elements being hidden using form_1.js.
e.g 
```
function hidePrev(el)
{
var prevClaim = el.form.formElements.get('aaa_my_profile___prev_claim');
var prevSucc = el.form.formElements.get('aaa_my_profile___prev_success');
var prevYear = el.form.formElements.get('aaa_my_profile___year_application');
var prevTitle = el.form.formElements.get('aaa_my_profile___official_course_title');
var prevProv = el.form.formElements.get('aaa_my_profile___course_provider');


while(prevClaim.getValue() < 0.01){
    prevSucc.hide();
    prevYear.hide();
    prevTitle.hide();
    prevProv.hide();
    return;
}
while(prevClaim.getValue() > 0.01){
    prevSucc.show();
    prevYear.show();
    prevTitle.show();
    prevProv.show();
    return;
}
```
The js is being triggered with prevClaim onload / onchange yesno element
I am using notempty validation on the elements.
If the elements are shown i want them to be validated
If the elements are hidden i don't want them to validate 
I set the element to Validate hidden = No
However it is still being validated when hidden.

**Comment by trob** [comment]
Is this working in F3?

**Comment by wezetel** [comment]
Probably your JS code doesn't set the right fabrikHide class
![grafik](https://user-images.githubusercontent.com/18248764/203613678-21292460-506b-4a9a-acb7-95a5c5b3f87f.png)

**Comment by trob** [comment]
https://fabrikar.com/forums/index.php?threads/fabrik-element-with-validate-hidden-no.53396/#post-279044

**Comment by ontargetWeb** [comment]
Ok let me check this by adding fabrikHide to my hidden elements

**Comment by trob** [comment]
Closing this one. You  may reopen if necessary.
