### ISSUE TITLE
Beta2 update: database problem for form comment plugin

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#551]
There seems to be a problem with the sql statements in 4.0.sql according the database checks.
As I don't use this plugin, I have no clue, if this creates problems

![grafik](https://user-images.githubusercontent.com/18248764/203714257-88d0c88b-9c9d-438d-8c49-170ca19cd554.png)

**Comment by wezetel** [comment]
Seems similiar to #547 and #546

**Comment by skurvish** [comment]
I will be releasing a beta2a later today which should correct these issues.

**Comment by skurvish** [comment]
Beta2a is available now.

**Comment by wezetel** [comment]
Beta2a doesn't solve the problem, but you have already seen this and reported as a new issue #561.
So one of both issues should be closed :-)
