### ISSUE TITLE
database structure problem after update to beta2

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#553]
After updating, 2 tables were reported as not up-to-date. I could update the structure for Fabrik Administrator Component, but not for the other one:

![afbeelding](https://user-images.githubusercontent.com/5586423/203775638-6730706a-da28-4545-9311-b94f40fa7652.png)

**Comment by skurvish** [comment]
Was this a beta1 to beta2 update or a clean install?

**Comment by EricdeWaal** [comment]
A beta 1 to beta 2 update

**Comment by trob** [comment]
See https://github.com/joomlahenk/fabrik/issues/551

**Comment by skurvish** [comment]
I will be releasing a beta2a later today which should correct these issues.

**Comment by skurvish** [comment]
Beta2a is available now.

**Comment by EricdeWaal** [comment]
I installed beta2a, and the database structure error did not disappear. Also, it is still not possible to correct it from the Maintenance: Database screen.

**Comment by skurvish** [comment]
It is good the install problem is fixed. Not sure what is going on with the db version problem. The other plugins are showing OK and I see no difference in the xml & sql files to explain it. Will take some further investigation. I am going to open a separate issue for this as it is not causing any failures, just the display.
