### ISSUE TITLE
List not responsive

### ISSUE THREAD

**Issue by gwstyles** [joomlahenk/fabrik#554]
beta 1 & 2  vanilla J4.2.5 + akeeba backup php 8.1.12

I have a simple list from a single table, I can not get the table to be responsive? I am using a vanilla casiopeia template.
Is it a bug or my lack of knowledge?
Thanks GWS.

**Comment by trob** [comment]
Not sure what you mean with responsive in this case.
Is this a different behaviour to Fabrik3?

**Comment by gwstyles** [comment]
Yes F3 is better.
My normal screen is 1600 px wide and all is well.
Reduce browser screen width to 1026px and everything responds as it should ,everything is thee just a bit smaller.
Reduce screen to 756px and there are horizontal scroll bars,this should not happen,the data elements should then be one under the other not side by side,on a phone it is next to impossible to see anything just a huge scroll needed to  get to the magnifying glass for detail view.
Changing casiopeia from fluid layout to static make no difference.
Thanks GWS,

**Comment by trob** [comment]
> the data elements should then be one under the other not side by side,on a phone it is next to impossible to see anything

This has nothing to do with Fabrik4 or Cassopeia, this is how HTML tables are displayed.
If youhave a lot of elements in list view and/or long texts without whitespace it's up to you to force your table to wrap text of some columns or set fix column width with hidden overflow etc.

**Comment by gwstyles** [comment]
The following css makes it almost good,makes phone usable at least. If any one has some improvements please post them.

@media 
only screen and (max-width: 560px),
(min-device-width: 980px)  and (max-device-width: 1624px)  {

	/* Force table to not be like tables any more */
	table, thead, tbody, th, td, tr { 
		display: block; 
		 
	}
	
	/* Hide table headers (but not display: none;, for accessibility) */
	thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
	

	
	tr { border: 1px solid #ccc; }
	
	td { 
		/* Behave  like a "row" */
		border: none;
		border-bottom: 1px solid #eee; 
		position: relative;
		padding-left: 50%; !important
	}
	
	td:before { 
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 6px;
		left: 6px;
		width: 25%; 
		padding-right: 10px; 
		white-space: nowrap;
	}

**Comment by gwstyles** [comment]
Just found that using an embedded list module performs better then a menu list item.

**Comment by trob** [comment]
Thanks for sharing.

But as I said this is nothing Fabrik4 specific.
This is what custom CSS or custom Fabrik templates are for.
