### ISSUE TITLE
Opening a form from a menu gives error in some cases

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#555]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Make (or use an existing) a menu item to open a form. No further settings in the Fabrik Form Options.

**Expected behavior**
Form opens, as it did in Beta 1

**Actual behavior**

Form does not open, error: Unclosed '{' on line 250 does not match ')' 

**Screenshots**

**Additional context**
Does not happen all the time, only for some forms.

**Comment by trob** [comment]
Yup, birthday element. Closing this one.
