### ISSUE TITLE
Add elements error on calling page

### ISSUE THREAD

**Issue by bumpsadmin** [joomlahenk/fabrik#556]
**To Reproduce**
After update to Beta2 on fresh install Alpha 1 adding new elements produces error

**Expected behavior**
Add elements worked before update to script

**Actual behavior**
From Element menu or any page request the error occurs

**Screenshots**
![image](https://user-images.githubusercontent.com/87337728/203825728-74619b4c-af5b-4d0b-a885-dd26589f1f75.png)

**Additional context**

**Comment by EricdeWaal** [comment]
That's the same error that I saw (#555)

**Comment by bumpsadmin** [comment]
Yes but thought as its element based and all the time it could help with diagnosis

**Comment by EricdeWaal** [comment]
In my case it occured in opening previously working forms. I suspected an element, tried to disable them all, but that was not the cause. I think it's in the form logic somewhere.

**Comment by dimoss** [comment]
@bumpsadmin I confirm it's happening after upgrading from Beta 1 to Beta 2.

**Comment by bumpsadmin** [comment]
@dimoss I upgraded from Alpha 3  to Beta 2 
It was fine in Alpha 3 as I built many elements with no errors.

**Comment by trob** [comment]
Sorry, that was my fault (missed an if ( while copying the code)
Please disable the birthday element or fix it by replacing 
plugins\fabrik_element\birthday\birthday.php line 251 with
**if (** in_array($value, $aNullDates)) ....

**Comment by EricdeWaal** [comment]
Yes, that did it, thanks!

**Comment by bumpsadmin** [comment]
Perfect thanks

**Comment by dimoss** [comment]
Thanks @trob
