### ISSUE TITLE
Deprecates error in birthday statement

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#557]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**

use birthday element in form

**Expected behavior**

Form opens without errors

**Actual behavior**

When the form opens, next error is shown 4 times:

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /usr/www/users/prachta/dtc/plugins/fabrik_element/birthday/birthday.php on line 431

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/5586423/203944027-cc4cb2fa-76d8-4305-b39d-771831a756b3.png)

**Additional context**

**Comment by trob** [comment]
I can't replicate, maybe it's only with special element settings.
Can you try with line 431 changed to
`if ($params->get('empty_is_null', '1') == '0' || (isset($val) && !in_array('', explode('-',$val))) )`

**Comment by EricdeWaal** [comment]
Yes, I am on Beta 2 and did apply the #540 fix.

Changing line 431 as indicated above makes the error go away, thanks!

Question; unlike the datetime element, the birthday element does not use timezones or anything that could lead to incorrect birthday display in a different time zone, is that correct?

**Comment by trob** [comment]
Bithday is a "date" column, so I assume it doesn't use timezone (but I don't know exactly, "dates" are also different in different time zones).

**Comment by EricdeWaal** [comment]
What I try to prevent (not for my testing site, but another one) that persons look a day older or younger when viewed from a different time zone.
Functions like date_default_timezone_set (https://www.php.net/manual/en/function.date-default-timezone-set.php)make me wonder ...
Maybe it's best to use a normal field and then and forget about the day/month year dropdowns.

**Comment by skurvish** [comment]
Can we close this?

**Comment by EricdeWaal** [comment]
Yes I have closed it
