### ISSUE TITLE
date elements default to today despite setting

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#558]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**

use date element in form, set 'Default to current date' and 'Always return today's date' to No. 

open form, do not enter a date 
or open existing record where date is NULL in the database

**Expected behavior**

field is blank or shows placeholder

**Actual behavior**

current date is shown and stored when form is stored

**Screenshots**

**Additional context**

**Comment by trob** [comment]
You mean the old date element? I can replicate.

Not sure what you mean with birthday element. The birthday element has some more issues but I can't see any situation where it's filled with the current date.

**Comment by EricdeWaal** [comment]
> You mean the old date element? I can replicate.

OK, will that be solved?

> Not sure what you mean with birthday element. The birthday element has some more issues but I can't see any situation where it's filled with the current date.

In my case when an existing record with an empty (NULL) birthday field is opened, it shows the current date. And stores if.

**Comment by trob** [comment]
Date element:
Try date.php line 1117
$isNullDate    = $nullDate == $value || $shortNullDate == $value || empty($value);

Birthday element:
I can't replicate.
What are your exact settings?

**Comment by EricdeWaal** [comment]
> Date element:
> Try date.php line 1117
> $isNullDate = $nullDate == $value || $shortNullDate == $value || empty($value);

I can confirm that this solves the default today in the date element

**Comment by EricdeWaal** [comment]
> Birthday element:
> I can't replicate.
> What are your exact settings?

I am sorry, it seems to work as expected now! I will close the issue
