### ISSUE TITLE
Fabrik placeholders not being rendered in form php plugin

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#559]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
php plugin form > onDeleteRowsForm
I'm using the rowid placeholder to return the id of the current row:

```
$row = '{rowid}';
var_dump($row);
exit;
```

**Expected behavior**
I should see **int(4)** 4 being the row id i went to delete.

**Actual behavior**
I see **string(7)"{rowid}"** which means the place holder is being rendered as a string.

**Screenshots**

**Additional context**
Here is the code in context
```
$db = JFactory::getDbo();
$myQuery = $db->getQuery(true);
$row ='{rowid}';
$trclaims = $db->quoteName('aaa_claims');
$eventmeeting = $db->quoteName('event_meeting');
$query = "SELECT COUNT($eventmeeting) FROM $trclaims WHERE $eventmeeting ='{rowid}'";
$db->setQuery($query);
$result = $db->loadResult();
//var_dump($result);
//exit;
if ($result == 0) {return true;}
else{return false;}
```

**Comment by trob** [comment]
Obviously in onDeleteRowForms you can't use element placeholders, but this is the same in Fabrik3.

**Comment by trob** [comment]
Sorry, it's working in F3 if you use the form Delete button but not on delete in the list. But this is running the same code, so you shouldn't use element placeholder "onDelete"

**Comment by trob** [comment]
See http://fabrikar.com/forums/index.php?wiki/php-form-plugin/#do-something-on-record-deletion
for onDelete code.
