### ISSUE TITLE
Comments Plugin Showing table issue

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#561]
Doesn't effect operation but needs to be fixed.
![image](https://user-images.githubusercontent.com/8654397/204096652-87f66301-c1ee-4720-b64c-9e82202b425b.png)

**Comment by skurvish** [comment]
So the problem is with the column create statement. There is no way to check if a column exists and if not then create it, using simple sql statements as are required in the sql file. Therefore I am going to remove this statement and place it in the construct function of the plugin.

**Comment by skurvish** [comment]
@wezetel can you try this plugin and confirm that the database warning is gone?

I also note that with beta2a additional warnings are showing for the database version for the component and the sequence and Thumbs plugins. This will get fixed on the next release, it was a merge issue.
[comment.zip](https://github.com/joomlahenk/fabrik/files/10096888/comment.zip)

**Comment by wezetel** [comment]
First needed to check, where in the file structure I need to extract the zip-file :-)
I found the right place:  plugin->fabrik_forms->comment
And after extracting the file and doing the repair the database warning is gone!
Thanks, so another issue can be closed.

**Comment by skurvish** [comment]
Great, thanks.

**Comment by wezetel** [comment]
Just saw: the manifest version is wrong (4.0 beta1).......just a naming....
