### ISSUE TITLE
Detail form does not close after using Apply button

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#562]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**

Activate "Apply" button on a form, Open it from a list using a link to details (not ajaxified). 
Use the Apply button once or more times.
Try to close the form either using Back or Save

**Expected behavior**
Form closes and the list is displayed again

**Actual behavior**

Form remains open

**Screenshots**

**Additional context**

**Comment by trob** [comment]
> Expected behavior
Form closes and the list is displayed again

No. Save or Back are going back to" where it comes from". After having used the Apply button this "where it comes from" is the form.
So it doesn't make sense to have Apply and Back enabled at the same time.
With Apply enabled use a redirect plugin to force Save to go back to the list.

This is the same with Fabrik3.

**Comment by EricdeWaal** [comment]
Well, jein as you say in German. I have used detail forms mostly with ajaxified links from a list. In that case, also after using Apply one or more times, Save closes the modal form. It still does in F4 as I now found out.

In my test I did not yest use an ajaxifed link. And in that case, Save does not close the detail form. Indeed the same as in F3.
But inconsistent at least.
