### ISSUE TITLE
Filters are not cleared with "Clear filters" button after using "Search all" field for filtering.

### ISSUE THREAD

**Issue by juuser99** [joomlahenk/fabrik#563]
Also "Search all" field is not cleared. Issue exists with ajaxified and not ajaxyfied lists.

**Comment by trob** [comment]
Try with [ListFilters.zip](https://github.com/joomlahenk/fabrik/files/10117565/ListFilters.zip)

**Comment by juuser99** [comment]
Thanks @trob. Working as expected now (both ajaxified and non-ajaxyfied lists).
