### ISSUE TITLE
Form Comment plugin causing "Call to a member function getTableColumns() on null "

### ISSUE THREAD

**Issue by fstorch** [joomlahenk/fabrik#566]
**To Reproduce**
Every Form that uses the Comment plugin fails
Just updated to pkg_fabrik_4.0beta2c which got rid of all install and database issues (Had to drop ratings though).
So first time I activated F4 extensions and such first post install test.
Installed comments.zip from  #561 but issue remains.
After disabling comments, form loads fine.
Testsite on Wampserver with restored production site.

**Expected behavior**
no error

**Actual behavior**
<blockquote>Call to a member function getTableColumns() on null                    </blockquote>
                                            <div>
                            

Call stack
--
# | Function | Location
1 | () | JROOT\plugins\fabrik_form\comment\comment.php:661
2 | PlgFabrik_FormComment->fixTable() | JROOT\plugins\fabrik_form\comment\comment.php:79
3 | PlgFabrik_FormComment->__construct() | JROOT\libraries\src\Extension\ExtensionManagerTrait.php:234
...

</div>

**Comment by skurvish** [comment]
Can you unzip this in your joomla root directory and let us know?
[comment.zip](https://github.com/joomlahenk/fabrik/files/10099349/comment.zip)

**Comment by skurvish** [comment]
Fixed.

**Comment by fstorch** [comment]
Sorry for the delay.
Updated .\plugins\fabrik_form\comment\comment.php
Now getting
                        <span class="badge bg-secondary">1103</span> Incorrect table name ''                   
                                            <div>
                            

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php:137
2 | mysqli->prepare() | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php:137
3 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliDriver.php:1048
4 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT\libraries\vendor\joomla\database\src\DatabaseDriver.php:1900
5 | Joomla\Database\DatabaseDriver->setQuery() | JROOT\libraries\vendor\joomla\database\src\Mysqli\MysqliDriver.php:584
6 | Joomla\Database\Mysqli\MysqliDriver->getTableColumns() | JROOT\plugins\fabrik_form\comment\comment.php:662
7 | PlgFabrik_FormComment->fixTable() | JROOT\plugins\fabrik_form\comment\comment.php:79
8 | PlgFabrik_FormComment->__construct() | JROOT\libraries\src\Extension\ExtensionManagerTrait.php:234
...

</div>

table jcc_fabrik_comments exists.

**Comment by skurvish** [comment]
Interesting, I will investigate.

**Comment by skurvish** [comment]
OK, fixed that problem, but now I am running into something else. Will need some more time to track it down.

**Comment by fstorch** [comment]
No rush. I'm impressed how many things are working already,

**Comment by skurvish** [comment]
OK, I think i have it. Can you try this file. I also need you to try actually doing a comment in the form and make sure it works.

[comment.zip](https://github.com/joomlahenk/fabrik/files/10107679/comment.zip)

**Comment by skurvish** [comment]
Turn off joomla debug. I get this often with debug turned on.

**Comment by skurvish** [comment]
Re the message box, can you give the the url that is showing at the time?

**Comment by fstorch** [comment]
turned off debug and backend seems to behave again.

The URL is http://disqus.com/:
![grafik](https://user-images.githubusercontent.com/34415681/204396799-f771e44e-8c9e-4d30-b896-92283fdf6bfb.png)

while comments is set to local commenting:
![grafik](https://user-images.githubusercontent.com/34415681/204396682-cae66942-0f4e-423a-b142-d66e3ce19fdb.png)

**Comment by skurvish** [comment]
Can you turn of seo so I can see the true url?

**Comment by trob** [comment]
With [comment.zip](https://github.com/joomlahenk/fabrik/files/10107679/comment.zip)
I get an "unexpexted token" in comments.js coming from
<b>Warning</b>:  Undefined property: stdClass::$default in <b>C:\xampp8\htdocs\j4h40\plugins\fabrik_form\comment\comment.php</b> on line <b>667

**Comment by fstorch** [comment]
SEO is off
![grafik](https://user-images.githubusercontent.com/34415681/204479804-b1ed125a-6ac7-4ceb-8918-9a92dc129fc4.png)

**Comment by fstorch** [comment]
But Comments are now working all of a sudden.
At least after I toggled Publish Commment plugin off/on and saving the form.
Adding a comment works as well.
![grafik](https://user-images.githubusercontent.com/34415681/204480561-9e9b7439-9c51-496c-945f-b93f4dc710d7.png)

**Comment by trob** [comment]
> But Comments are now working all of a sudden.

Did you re-save your form or add a new comment plugin? 
I'm pretty sure I also have seen this Disqu link instead of the local comment form at some point but wasn't able to replicate.

**Comment by trob** [comment]
Closing this one. If this Disque link will pop up somewhere we can have a new issue.

**Comment by fstorch** [comment]
Just went into the form, disabled the existing comment plugin and enabled it again. After that saved the form.
