### ISSUE TITLE
Upgrade: Three PHP errors in Fabrik 4 Systems plugins

### ISSUE THREAD

**Issue by davidspring** [joomlahenk/fabrik#567]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**What happend**
After updating the website to Joomla 4 with no problem, I  I downloaded and installed the beta2b version from the bottom of this page: 
https://github.com/joomlahenk/fabrik/issues/565
This ended in this error: 
Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin() 

**To Reproduce**

Update a fabrik site from J3 to J4 and then install the beta of Fabrik 4

**Expected behavior**

No erros 

**Actual behavior**

error

**Error message**

this error: 
Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin() 

**Screenshots**

**Additional context**
I solved all three errors with the following: 

The trace indicated the problem was here: 
JROOT/plugins/system/fabrik/defines.php:82
The problem appears to be in this Fabrik system plugin. 
Back to the file manager and open plugins/system/fabrik/defines.php
Line 82 is 
if ($app->isAdmin())
Change this line to: 
if ($app->isClient('admin'))
Then click Save and close. 
Then reload the Joomla dashboard page. 
a second error appears: 
Joomla error    0 Class "JResponse" not found 
This class doesn't exist in J4. The trace indicated the error was on Line 336 this plugin
/plugins/system/fabrik/fabrik.php
Line 336 is 
$content           = $lessThanThreeFour ? JResponse::getBody() : $app->getBody();
The problem is that Joomla 3.x uses JResponse to get and set the body. But in Joomla4 it returns Class 'JResponse' not found. 
Instead we should use 
JFactory::getApplication()->getBody() 
I therefore used this: 
$content           = $lessThanThreeFour ? JFactory::getApplication()->getBody() : $app->getBody();
Then click save and close. 
The third error also was Class "JResponse" not found  is in the same file on line 347
$lessThanThreeFour ? JResponse::setBody($content) : $app->setBody($content);
The problem is that Joomla 3.x uses JResponse to get and set the body. But in Joomla4 it returns Class 'JResponse' not found.
Instead we should use: 
    JFactory::getApplication()->setBody()
so change the line to this
$lessThanThreeFour ? JFactory::getApplication()->setBody($content) : $app->setBody($content);
Then click Save. 
I then reloaded the admin page and there were no more errors. 
Let me know when these errors are fixed in the next beta and I will try the new beta on some more of my Fabrik websites. 
Regards,
David Spring

**Comment by trob** [comment]
Recent Fabrik4 is beta2c, see https://github.com/joomlahenk/fabrik/wiki/Tester-Instructions or https://fabrikar.com/forums/index.php?threads/fabrik-4-0-beta2-now-available-for-download-and-testing.53548/

But anyway
It seems something got wrong with your updates, you don't have the Fabrik4 code in your Fabrik system plugin,
Maybe some folder access issue (e.g. no write access for the new files?)

**Comment by trob** [comment]
You must install the package not only the component.

**Comment by skurvish** [comment]
@davidspring not sure what you did but none of those code lines exist as described in the current codebase. Please try installing the beta2c version.

**Comment by davidspring** [comment]
I do not know what I did wrong either. The good news is that whatever it was the beta2c version of Fabrik fixed it. I have now used the Beta2c version of Fabrik to update several sites from Joomla 3 to Joomla 4 and all of them updated without a single error!

**Comment by trob** [comment]
@davidspring : You did install **com_**fabrik_4.0beta2b.zip (not **pkg_**fabrik)
Which is only the component, no plugins, no libs. So all your code (beside code in /com_fabrik) was the old F3 code.
