### ISSUE TITLE
Global placeholders (e.g. {shortlang} or {year} ) not replaced

### ISSUE THREAD

**Issue by lorenzo51** [joomlahenk/fabrik#573]
I currently have F3/J3 sites that use {shortlang} in Lists Pre-filter.
This seems not to be replaced in F4/J4 whereas other placeholders, like {$my->username}, are correctly replaced.

**Comment by trob** [comment]
It's not only in Pre-filters but also e.g. in element default.

**Comment by trob** [comment]
Try 
[GlobalReplace.zip](https://github.com/joomlahenk/fabrik/files/10126332/GlobalReplace.zip)

**Comment by lorenzo51** [comment]
Global placeholders are now correctly replaced with the file you shared. Thank you!
