### ISSUE TITLE
Not able to install package beta2c

### ISSUE THREAD

**Issue by davidspring** [joomlahenk/fabrik#575]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
On a website recently updated from Joomla 3.10 to Joomla 4.2.5, I uninstalled the Fabrik beta2c package with the goal of reinstalling it. However, the uninstall ended with this error: 
An error has occurred.  0 array_diff(): Argument #1 ($array) must be of type array, bool given 
I repeated the uninstall and the second uninstall succeeded. I then tried to reinstall Fabrik beta2c package and got the same error. 

**Expected behavior**

can uninstall and install without error

**Actual behavior**

error on both uninstall and install

**Screenshots**

**Additional context**
I turned on debug. The trace route showed this as the problem: 
JROOT/tmp/install_63878788275bc/packages/install_638787badd967/com_fabrik.manifest.class.php:69 
Here is line 69: 
$files = array_diff(scandir($directory), ['..', '.']);

I thought perhaps this problem may be due to the upgrade. So I made a new Joomla 4.2.5 demo site and tried to install Fabrik beta2c. I got the same error. I was not able to install Fabrik beta2c. 
So I tried to install beta2b. It installed without problem. So I compared the  com_fabrik.manifest.class.php file between the two versions and they are different.

**Comment by trob** [comment]
> Instructions updated for Beta2c
Note If installing this release on a J! system that has not had Fabrik installed before, please create a file on your system /administrator/components/com_fabrik/sql/updates/mysql/3.10.sql which can be an empty file. This will be fixed in the next release. 

https://github.com/joomlahenk/fabrik/wiki/Tester-Instructions

**Comment by davidspring** [comment]
Thanks. That solved the problem

**Comment by davidspring** [comment]
But why did it not work on my website that had Fabrik installed before?

**Comment by davidspring** [comment]
I was not able to install beta2c on either site and even the site that had Fabrik on it before I had to add the empty sql file.

**Comment by davidspring** [comment]
Perhaps it was because I deleted Fabrik rather than installing beta2c over an existing Fabrik package.

**Comment by davidspring** [comment]
In any case, the problem is solved by the empty sql file so this issue can be closed.

**Comment by davidspring** [comment]
another option is to install beta2b and then install beta2c over the top of it. I just tested this and it also works without error.

**Comment by trob** [comment]
> Perhaps it was because I deleted Fabrik rather than installing beta2c over an existing Fabrik package.

Yup. Beta2c is searching for .sql files  and throws this error if there's none which is the case if your never had Fabrik installed or if you deinstalled an existing one.
Will be fixed in the next release.
