### ISSUE TITLE
Unpublished list can't be edited

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#577]
**To Reproduce**
Unpublish a list in lists view and edit something
or
edit a list, change something and additionally set Status to Unpublished (or Trashed)

**Expected behavior**
Changes will be saved (including the status) 

**Actual behavior**
Any changes are ignored

**Additional context**
It's working in F3.

In unpublished forms changes will be saved (F4).

**Comment by skurvish** [comment]
This is another date issue. The publish_down value is null and the sql driver is not accepting it. Needs more investigation.

**Comment by skurvish** [comment]
OK, I think I have it understood. The J! team went through a major update back around the 4.0 release in September 2019 specifically for these datetime columns. Here are the sql updates used for com_tags which are the same throughout:

ALTER TABLE `#__tags` MODIFY `created_time` datetime NOT NULL;
ALTER TABLE `#__tags` MODIFY `modified_time` datetime NOT NULL;
ALTER TABLE `#__tags` MODIFY `publish_up` datetime NULL DEFAULT NULL;
ALTER TABLE `#__tags` MODIFY `publish_down` datetime NULL DEFAULT NULL;
ALTER TABLE `#__tags` MODIFY `checked_out_time` datetime NULL DEFAULT NULL;

Furthermore, they then proceed to update the database as follows:

UPDATE `#__tags` SET `modified_time` = `created_time`, `modified_user_id` = `created_user_id` WHERE `modified_time` = '0000-00-00 00:00:00';
UPDATE `#__tags` SET `publish_up` = NULL WHERE `publish_up` = '0000-00-00 00:00:00';
UPDATE `#__tags` SET `publish_down` = NULL WHERE `publish_down` = '0000-00-00 00:00:00';
UPDATE `#__tags` SET `checked_out_time` = NULL WHERE `checked_out_time` = '0000-00-00 00:00:00';

And the one more very important change is in the Table store function, the default for this needs to have the $updatenulls = true set on the store function. This is one thing we missed when we were working on this a while ago.

I will go through and make these changes and test them out. I think it will solve a lot of our problems including this one.

**Comment by trob** [comment]
Great work

**Comment by trob** [comment]
Looks ok now.
