### ISSUE TITLE
Can't find XML setup file

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#579]
### Discussed in https://github.com/joomlahenk/fabrik/discussions/578

<div type='discussions-op-text'>

<sup>Originally posted by **neriozanzini** December  2, 2022</sup>
I've tried both beta 1 and beta2 on a subdomain (test site) but I always get the install error:
"
JInstaller: :Install: Can't find XML setup file.
Table 'gres_2021.b8bd4_fabrik_connections' doesn't exist
Package Install: There was an error installing an extension: com_fabrik_4.0beta2c.zip
"
PHP 8.1
J! 4.2.5
Template: Helix Ultimate 2.0.5
I previously created a file /administrator/components/com_fabrik/sql/updates/mysql/3.10.sql because there was no previous installation of Fabrik.
Tips?</div>

**Comment by skurvish** [comment]
Try the beta3 package just uploaded.

**Comment by trob** [comment]
ok with beta3
