### ISSUE TITLE
Upgrade: error 1103 Incorrect Table Name

### ISSUE THREAD

**Issue by davidspring** [joomlahenk/fabrik#581]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**What happend**
I have several Fabrik websites that I thought had been updated with no issues. However, when I create a new form on any of them and then click on Update Database,  I get the following error: 
**Error 1103 Incorrect table name.** 
This error occurs regardless of the name I give the database table. Also strangely, when I create a form, the matching list is not created. 
After turning on debug, this is shown in the trace as the error. 
 error, libraries/src/Menu/SiteMenu.php (line 155) 
This line reads:  
  $this->db->quoteName('m.publish_down') . ' IS NULL',

I updated all of the sites from Beta2b to Beta2c to Beta3 but it did not help. 

In reading the Joomla forum posts on similar problems, some claim that Fabrik did not delete all of the database entries during an update and thus there are duplicate entries. Here is one forum post: 
Which database tables and files are added by a failed update?  In my case, it was Fabrik. Even after the uninstall, its tables remain in the database. 

However, when I went to PHP MY ADMIN I could not find any duplicate entries. 

The good news is that a new install of Fabrik Beta3 does not have this problem. So if necessary I will have to just rebuild my Fabrik sights from scratch.  I have spent the past two days trying to fix this problem. Any ideas on how to fix my updated Fabrik sites would be greatly appreciated. 

**To Reproduce**
I used several methods to update the sites from J3.10 to J4.2.5. I have PHP 8.1 and the Helix template. 

**Expected behavior**
I can make new Fabrik forms and update the database without error even after the update. And when I make a new form, Fabrik should automatically make the matching List. 

**Actual behavior**
No matching list. error when try to update datebase. 

**Error message**

Error 1103 Incorrect table name.

**Screenshots**

**Additional context**

**Comment by trob** [comment]
I can see issues with "Update database" and while creating a list via a form in some cases, too.
But slightly different from yours, and not on my F3->F4 updated site.
Trying to find any systematic.

In any case your workflow (creating a new form to get a new list) is not recommended.
Start with creating a new list.

Using "Update dabase" should not be necessary at all (already in Fabrik3 I was not sure if it was always working correctly).

**Comment by davidspring** [comment]
Thanks for the feedback. I was aware that starting with a List was the recommended way and I will try that and report back. As for Update Database, it has always worked for me on all of my Joomla 3 websites and also works on my new install of Fabrik Beta 3 on a Joomla 4 website. I use it as a quick test that everything is working OK after making major changes to my Fabrik forms and lists. It seems to be able to tell if I have done something wrong.

**Comment by davidspring** [comment]
I have now tested creating the List first. I do need to manually enter the name on the Details screen for the database name to be complete. But it does create the list and it also creates the form with the proper database name and the group and the elements. So in the future, I will just create the list first. I will also pass this information on to all of my students. So I think you can close this issue. Thank you for your help.

**Comment by davidspring** [comment]
By the way, starting with the new List first is only needed on my updated Fabrik websites. New Fabrik sites that begin with an install of Fabrik version beta3 can start with either a new List or a new Form. But on both new lists and new forms I need to manually type out the full name of the list or form for the database table to enter properly. Also, if I do a form first, then I need to manual enter the name of the database table also.

**Comment by trob** [comment]
> I do need to manually enter the name on the Details screen for the database name to be complete.

This is strange.
Having a workaround is ok. But something is not good at all.

Do you have any JS errors in your browser console?
Which browser do you use?
Do you have any other components/plugins installed (which may break Fabrik JS)?

**Comment by davidspring** [comment]
There are no JS errors and I am using the Linux Debian version of Firefox recently updated. As for components and plugins, I have installed Phoca Download and Kunena Forum and BW

**Comment by skurvish** [comment]
@davidspring can you test this for us please? https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta3b.zip we think it will fix a number of database issues, but it is a big change so needs so further testers. Thanks.

**Comment by davidspring** [comment]
I am testing it right now. I will have a report in about one hour.
