### ISSUE TITLE
One validation not updated by Beta 3

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#582]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Upgrade from Beta 2a to Beta 3

**Expected behavior**
All Fabrik extensions to be version 4.0beta3, date 2022-12-01

**Actual behavior**
One validation is still an older version:

Fabrik Validation - email exists in Joomla   4.0beta2a | 2022-11-01

**Screenshots**

**Additional context**

**Comment by dimoss** [comment]
@EricdeWaal Updating from Beta3c -> Beta3 i can't find this validation among the fabrik validations in the extensions manager.

**Comment by EricdeWaal** [comment]
@dimoss I got a pre version from @skurvish for testing, so I already had it.
It's indeed in the Beta 3 package but not on the install list, that's why mine was not updated and it was not installed on your site.

BTW: <file group="fabrik_validationrule" id="isemail" type="plugin">plg_fabrik_validationrule_isemail_4.0beta3.zip</fille> is in the XML TWICE!

**Comment by EricdeWaal** [comment]
Its seems that some more elements, like 'folder', 'picklist', 'timer' are also in the zip and OK according to the Status page, but not installed.

**Comment by trob** [comment]
If they are in the code you can always install via "Discover".

**Comment by dimoss** [comment]
> If they are in the code you can always install via "Discover".

@trob tried to click on Discover but it doesn't bring them. All 3 that @EricdeWaal mentioned are missing from the .xml from the Beta 3 package.

**Comment by skurvish** [comment]
I will get this sorted out today and get a new install package uploaded. Lots of moving parts.

**Comment by davidspring** [comment]
On my Fabrik websites that were updated several times now from the various beta versions, and all used to be on Joomla 3.10, the email exists plugin has always been there and is still there and is working very well. I am currently using Beta 3 on all of my websites. I did have to enable it again.

**Comment by davidspring** [comment]
I just checked a new install of Beta 3 and the is email validation is there. I tested it and it appears to be working well.

**Comment by skurvish** [comment]
@dimoss please try beta3a, thanks.

**Comment by dimoss** [comment]
> @dimoss please try beta3a, thanks.

Looks good. Thanks @skurvish

**Comment by EricdeWaal** [comment]
Indeed all 75 elements/plugins are in the install list and get installed without problems.
Closing the issue now.
