### ISSUE TITLE
Elements miss the list name after list creation from existing view

### ISSUE THREAD

**Issue by dimoss** [joomlahenk/fabrik#583]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Creating list from existing view on DB.

**Expected behavior**
Elements have the Full Element Name including the list name as in F3. 1st screenshot.

**Actual behavior**
Elements don't have the Full Element Name including the list name. 2nd screenshot, 3rd screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/10183465/205439463-f2808def-ca2f-4c6b-9735-ed817ba6a73e.png)

![image](https://user-images.githubusercontent.com/10183465/205439495-952cbfca-28c0-4f76-92e2-a63f2bc8004d.png)

![image](https://user-images.githubusercontent.com/10183465/205439557-e527ba8a-551d-40f5-bb87-05b2ed35b1ec.png)

**Additional context**

**Comment by dimoss** [comment]
Don't know if the following is related to the above but I cannot select the id to set the PK and cannot select any element for ordering,

![image](https://user-images.githubusercontent.com/10183465/205439972-8ab0be9a-5b14-46ea-abe8-2907cda339cc.png)

**Comment by trob** [comment]
Confirmed. No form or element connected.
Maybe related to https://github.com/joomlahenk/fabrik/issues/581?

**Comment by davidspring** [comment]
In a new site with Fabrik 4 beta3 installed, I added a new list. When I copy pasted the name of the list in, only the first letter was used for the name of the table. However, when I manually typed on the name in the details screen, the full name was used in the table. Also the full name was used as expected in the elements. 

I am now testing in my updated sites to see if there is a difference. I will report back shortly.

**Comment by davidspring** [comment]
By the way, I had this same problem in the Joomla 3 version of Fabrik where the names have to manually added in the Details screen.

**Comment by skurvish** [comment]
David, you may be a little early on upgrading production sites to F4. There is still much testing that needs to be done and we wouldn't want you to get into a panic situation if something goes wrong with one of your paying customers.

**Comment by trob** [comment]
Still the same with beta3b

**Comment by skurvish** [comment]
I didn't expect this release to change this issue.

**Comment by davidspring** [comment]
Thankfully I do not have any paying customers. I am basically a retired teacher,. I spend my time volunteering for non-profits and helping local community groups. Also I have a very good backup system. Finally, I have a series of demo sites that I test stuff on before putting it on real websites. Personally, I think Fabrik 4 is working really well compared to some other Joomla components I have been dealing with.

**Comment by skurvish** [comment]
@dimoss please try https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0-2022-12-08.zip thanks.

**Comment by dimoss** [comment]
> @dimoss please try https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0-2022-12-08.zip thanks.

Same issue.

**Comment by skurvish** [comment]
OK, I wasn't sure if the changes I made would affect this or not. Good to know so we will keep working on it.

**Comment by skurvish** [comment]
@dimoss I have not used views before on my site. You could save me a bunch of time in research if you could write up a quick summary of what I need to do to set up to test this problem. Thanks.

**Comment by dimoss** [comment]
> @dimoss I have not used views before on my site. You could save me a bunch of time in research if you could write up a quick summary of what I need to do to set up to test this problem. Thanks.

1. You create a view n your DB using your prefered DB Editor (ex. phpMyAdmin). The view needs to have a unique INT key which will be used in your fabrik list as PK.
2. You create a list as usual and instead creating the DB table, you select from existing DB table which is your view.
3. You save the list and you select the unique INT key as PK.
4. The view fields are the elements of your list.

**Comment by skurvish** [comment]
Thanks. I will tackle this as soon as I solve the publish down issue.

**Comment by skurvish** [comment]
@dimoss where does this unique INT key live? Do I create a new column in the list for this? Or do I create it somewhere else?

**Comment by trob** [comment]
You need a column in the view which can be uses as PK by Fabrik, so it has to be in the view definition. somthing like
CREATE VIEW view_name AS
SELECT id, column1, column2, ...
FROM table_name
WHERE condition;

A view is readonly (so you can't add elements via Fabrik)

**Comment by skurvish** [comment]
So id is the same id used for the list itself?

**Comment by trob** [comment]
Usually yes. 

But I think the issue here is similar to the other ones with "form missing table name".
Fabrik is creating list/form/group/elements from the view correctly but the form id is missing in the list.

 At some point it's inserting 0 in #__fabrik_lists.form_id
and this is the only link between a form and it's list.

**Comment by trob** [comment]
Just to mention it:
If you are running into an error "Prepared statement needs to be re-prepared" while trying to display the list on a view "another possible solution is to increase the value of table_definition_cache and table_open_cache in your my.conf file" resp. in your DB settings via phpMyAdmin..

**Comment by skurvish** [comment]
Which other issues with the form name missing? I would rather test this on a basic form than a view as I am having great difficulty getting the view set up. Fabrik doesn't give me any elements for the PK.

**Comment by trob** [comment]
I meant https://github.com/joomlahenk/fabrik/issues/581
He mentions somewhere that "Table name" in form settings/Form processing is or gets blank.
But I'm not sure what is going on his site  at all, because I never saw this "typing a list or form label won't copy this label into 'Table name' field" happen.

So better stay with the view which is replicatable.

>  Fabrik doesn't give me any elements for the PK.

Yup, that's exactly a consequence of this issue.
After creating a list linked to a mySQL-view list/form/group/elements are there but _fabrik_lists.form_id is 0 (instead of holding the new form id).

So if this form_id is empty the link (and it't the only link) between list and form (and so group and elements) is missing, the list can't show you any element.

This "link list to MySQL-view issue" can be "solved" by manally adding the form_id to the list entry.
Then you can select a PK etc. 
But this should be done during list creation, also setting isView Parameter to 1, Alter fields to no etc.

Fabrik "knows" that it's linking to a view (you get the System message) but after this messages something goes wrong.

**Comment by skurvish** [comment]
OK, I see the issue now.

**Comment by skurvish** [comment]
@dimoss please unzip the attached into your joomla root. It should fix this problem. Let us know your results.
[cumulative_12_12_2022.zip](https://github.com/joomlahenk/fabrik/files/10207595/cumulative_12_12_2022.zip)

**Comment by trob** [comment]
Looks very good.

**Comment by dimoss** [comment]
> @dimoss please unzip the attached into your joomla root. It should fix this problem. Let us know your results. [cumulative_12_12_2022.zip](https://github.com/joomlahenk/fabrik/files/10207595/cumulative_12_12_2022.zip)

@skurvish Works! I should delele the previous list/form/group from Fabrik and re-create to make it work. 

Something else I noticed is that the form record was not deleted from #__fabrik_forms table on the DB when I cleared the trash.

**Comment by skurvish** [comment]
That is probably an afteraffect of the incorrect list creation. I think if you remove the new one that worked you should see the records in all the tables go away. If they do not open a new issue on it.
