### ISSUE TITLE
juser element does not send new user details to mailer

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#584]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**

Make a form, add juser plugin, add user data fields and bind all juser fields to corresponding form fields.
Set Bypass activation and registration to Yes, Set Account details email and Bypass all email to No.
Synchronize users and Sync on edit On.

**Expected behavior**

When creating a new user from this form, Joomla sends the site and user details by mail.

**Actual behavior**

The Joomla user is created, the email is sent but contains %s placeholders for site and user details.

**Screenshots**

**Additional context**

**Comment by trob** [comment]
Which language?
It's ok on my site (in German).

**Comment by trob** [comment]
Joomla4 has changed (some of?) it's own language strings from %s to {some placeholder}.
See language\en-GB\com_users.ini for the strings.

Do you havecustom language overrides? (you'll have to adapt)
Or is your Dutch package not up-to-date?

**Comment by EricdeWaal** [comment]
> Joomla4 has changed (some of?) it's own language strings from %s to {some placeholder}. See language\en-GB\com_users.ini for the strings.
> 
> Do you have custom language overrides? (you'll have to adapt)

Yes, that was the case, thank you!
