### ISSUE TITLE
beta3b: saving an element is showing an "empty", green error message

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#585]
Saving any element I get this
**Screenshots**
![image](https://user-images.githubusercontent.com/1045355/205520333-bcb85784-b909-44bf-ae1b-dfb606931429.png)

instead of "Item saved".
It's not only with jdate but also with a simple field.
But all seems to be saved correctly.

**Comment by skurvish** [comment]
OK, will have a look in the morning. Probably something simple, especially if it is actually saving.

**Comment by skurvish** [comment]
Found the problem, in file administrator/components/com_fabrik/tables/element.php at line 123, change it to return parent::store($updateNulls);

There may  be other places, I will investigate tomorrow.

**Comment by skurvish** [comment]
I found a few more and updated the beta3b package.

**Comment by davidspring** [comment]
I installed beta 3b on a demo site you sent me the link to over the previous beta version that had been working very well - I had made several forms and lots of elements without error. Unfortunately, the beta3b has  problems. I created a new list and then tried to open the matching form and got this error: An error has occurred.
    0 syntax error, unexpected token ";", expecting ")" 
I went to system database. It said the Fabrik component tables were not up to date. Clicked update structure. Problem remained. 
So I turned on debug system and tried again to open the form. 
This time I could open the form. Shockingly the Table Name was missing - despite the fact that I had manually entered the table name when I created the list. I then closed the form and clicked add to add a field. This was the stack trace of the error: 
/plugins/fabrik_element/sequence/sequence.php: Line 375 
I then tried to add a field to an existing form that had been previously working fine. I got the same error going to Line 375. 
So I rolled back the demo site to the Beta 3 version. My advice is to stay with Beta 3 until Beta 3 B is doing better. 
Regards, David

**Comment by davidspring** [comment]
Feel free to email me when you have another version of beta 2B I have my own Virtual Private Server and I have lots of demo sites and I do not mind destroying them.

**Comment by skurvish** [comment]
Ok, thanks for testing. I have discovered another issue with J4 saving null values to the database. I am going to have to open an issue on the J! issue tracker. So for now stay with the beta3 that works for you.

**Comment by skurvish** [comment]
I have opened an issue on the issue tracker, let's see what they say. In the mean time I will see if I can figure out any of these other issue and whether they are related or not.

**Comment by skurvish** [comment]
There is definitely a problem creating a list. I am looking into it now.

**Comment by davidspring** [comment]
I am hoping that one of you can email me as soon as possible regarding the status of Fabrik. My email is david spring at proton mail dot com

**Comment by skurvish** [comment]
What is it you need David? We are working the issues. This particular issue has bee solved, just hasn't made it into the release yet. The problem here is just a display, it doesn't change anything and it is working.

Is there one particular thing holding you up?

**Comment by davidspring** [comment]
I need to talk with you or Henk or Strob in private about the status of
Fabrik. I am hoping that one of the three of you would be willing to email
me so I can reply with an email privately. It would only take about 10 to
20 minutes. But I need your input about the status of Fabrik.

**Comment by skurvish** [comment]
I have responded to David.

**Comment by skurvish** [comment]
@trob please try https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0-2022-12-08.zip

**Comment by skurvish** [comment]
Fixed.
