### ISSUE TITLE
Cant delete row from list

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#586]
Fabrik4Beta3

**To Reproduce**
 Try to delete a row from the list in the backend.
Use the delete at the top of the list (or use inline buttons) - not the dropdown delete next to the row
I get the error: 
```
An error has occurred.
0 trim(): Argument #1 ($string) must be of type string, stdClass given
```

**Expected behavior**
Row should be deleted

**Actual behavior**
Error message above shown row is not deleted

**Screenshots**
<img width="891" alt="Screenshot 2022-12-07 at 09 20 20" src="https://user-images.githubusercontent.com/26169616/206138990-977862ce-fe9f-4197-a7f8-e941a20e9ef4.png">

**Additional context**
I dont think its the same behaviour as #528

**Comment by ontargetWeb** [comment]
Thanks I'm using skurvish install pkg beta3a from the wiki.

**An error has occurred.
0 trim(): Argument #1 ($string) must be of type string, stdClass given**

Trace Stack

Call stack
--
```
# | Function | Location
1 | () | JROOT/plugins/fabrik_element/fileupload/fileupload.php:3347
2 | trim() | JROOT/plugins/fabrik_element/fileupload/fileupload.php:3347
3 | PlgFabrik_ElementFileupload->onDeleteRows() | JROOT/components/com_fabrik/models/list.php:9114
4 | FabrikFEModelList->deleteRows() | JROOT/administrator/components/com_fabrik/controllers/list.php:263
5 | FabrikAdminControllerList->delete() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
6 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_fabrik/fabrik.php:104
7 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
8 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
11 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
12 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
14 | require_once() | JROOT/administrator/index.php:32
```

Also have the following fabrik debug errors which may be affecting it?
```An error has occurred with a eval'd field - please inform the web-site owner.    Debug: Eval exception : school_address (id 97)::preFormatFormJoins() : $id = '01116A'; $db = JFactory::getDbo(); $query = $db->getQuery(true); $query ->select(array('schoolName', 'address2', 'county' ,'eircode', 'phone')) ->from('aaa_schools') ->where('schoolRoll = ' . $db->quote($id)); $db->setQuery($query); $rows = $db->loadObjectList(); //var_dump($id); $list = array(); foreach ($rows as $row) { $list[] = $row->schoolName . ', '. $row->address2 . ', ' . $row->county . ', ' . $row->eircode. ', ' . $row->phone; } return implode($list); : Joomla\CMS\Factory::getDbo() is deprecated. Load the database from the dependency injection container.```
<img width="1892" alt="Screenshot 2022-12-07 at 10 34 18" src="https://user-images.githubusercontent.com/26169616/206156229-9d92f181-9149-4d63-9aa2-8e62d5677422.png">

**Comment by ontargetWeb** [comment]
I corrected the deprecated getDBo() 
`$db = JFactory::getDbo();`
using 
https://github.com/joomla/joomla-cms/discussions/38111#discussioncomment-3971334

```
use Joomla\CMS\Factory;
use Joomla\Database\DatabaseInterface;
$db = Factory::getContainer()->get(DatabaseInterface::class);
```
So that error has gone

**Comment by ontargetWeb** [comment]
Sorry but the 
An error has occurred.
0 trim(): Argument https://github.com/joomlahenk/fabrik/pull/1 ($string) must be of type string, stdClass given
Still exists...

**Comment by trob** [comment]
> Looking at the stack trace I am using ajax fileupload elements which are set to Delete images? = Yes when the record is deleted - could this be a cause?

Yes. But I can't replicate.
This is a non-ajax fileupload?
Some special settings? e.g. in a repeat group or a list  join or...? with/without thumb, crop?

**Comment by ontargetWeb** [comment]
Ok I can confirm the behaviour.
I have 6 file upload elements all using ajax file upload method
All are set to **Delete images? = Yes**
If i change them to **Delete images? = No**
Then i can delete the row.

**Comment by trob** [comment]
> User tables need to go through the FabrikWorker::getDbo() 

Ok. 
But I assume in most cases there's only the J! DB and most users (including me) have $db = JFactory::getDbo(); in their custom code (as it's shown in many WIKI examples etc).
So maybe one more point to mention in the "upgrade WIKI"

If FabrikWorker::getDbo() is used there should not be a depreated warning (if this is already fixed in FabrikWorker, is it?).

**Comment by skurvish** [comment]
FabrikWorker::getDbo calls the DatabaseDriver directly passing in the connection details, either the configuration database details or the connection details. No deprecation warning there.

**Comment by trob** [comment]
Back to the fileupload issue:
> I have 6 file upload elements all using ajax file upload method...

I can't replicate with a standard ajax fileupload.
Do you have in (one of ) these 6 fileuploads non-default settings? I assume at least one of them has "Max. files"=1?
Please mention such non-defaults.

**Comment by trob** [comment]
Meanwhile in beta4b
