### ISSUE TITLE
List filter not working in Admin

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#588]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**

Open the data view of any list in the admin side. Click on the filter icon.

**Expected behavior**

The filter modal comes up.

**Actual behavior**

Javascript error in console:

Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at Modal._isAnimated (modal.min.js?5.1.3:1:5041)
    at Modal._initializeBackDrop (modal.min.js?5.1.3:1:3008)
    at new Modal (modal.min.js?5.1.3:1:1383)
    at Modal.getOrCreateInstance (dom.min.js?5.1.3:1:8526)
    at HTMLAnchorElement.<anonymous> (modal.min.js?5.1.3:1:6489)
    at HTMLDocument.o (dom.min.js?5.1.3:1:4911)

**Comment by trob** [comment]
Which filter type? Filter as popup or Advanced search?
Both is working at my site (latest code).

**Comment by skurvish** [comment]
It's the filter modal. I admit I have not tested it much, I just happened to come across it and wanted to get it documented before I forgot. Is the latest code as late as the last 30 minutes or so, as I checked a lot of stuff in.

**Comment by trob** [comment]
I added some BS5 styling to the modal filter.
But I still can't see any JS issue (nor in backend nor frontend).

**Comment by skurvish** [comment]
I will check it again.

**Comment by skurvish** [comment]
Still failing with the js error for me.

**Comment by trob** [comment]
Maybe related to some element?
On my site filtering is failing with some php errors related to jdate in case Advanced search is enabled.
I have to investigate.

**Comment by trob** [comment]
Is this still an issue?
I can't get an error nor with modal filter nor with Advanced search (no matter if J!debug is on or off or Fabrik's Debug JS on/off)

**Comment by skurvish** [comment]
I am no longer getting the above error, however, once I set the filter I am getting an error that DateFilter is not defined. I have a jdate element in the filter list. Looking at it now.

**Comment by trob** [comment]
date and jdate filters have already issues in F3, so it may be an "old" one.

As far as I can remember for date filter the date element must be in list view or set to "always render" and jdate had issues at least in Advanced search.

**Comment by skurvish** [comment]
found the problem, remember the issue we had very early on with a function call that the J had been dropped but it was need to call a specific F! function versus the default J! function? This issue is similar, we dropped the J in front of the JDateFilter class instantiation. Once I put it back in no more error.
