### ISSUE TITLE
Advanced search in list data in admin needs BS5 markup

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#589]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**

Open any list in the admin and view the data. Click on the Advanced search button.

**Expected behavior**

Nicely formatted advanced search modal.

**Actual behavior**

Ugly advanced search modal popup.

**Comment by trob** [comment]
One issue is that Atum does funny color settings on .modal .btn

**Comment by skurvish** [comment]
Fixed.
