### ISSUE TITLE
List module link target

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#590]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Have a list, where one of the elements in the list is defined to link to the details view in list settings. Define as link target 'Default' (not new window/tab!)
Create a fabrik list module with the above mentioned list. Click a link of one record in the module

**Expected behavior**
Details view is opened in the content area

**Actual behavior**
New (modal) window is opened with the details view

**Screenshots**

**Additional context**

**Comment by trob** [comment]
> to link to the details view in list settings

I assume you mean "List view settings" in element settings?

> Expected behavior
Details view is opened in the content area

No. it depends on your module settings. If Ajaxfy=yes it will open modal, with No it will open in content area (same as in F3)

**Comment by wezetel** [comment]
Thanks, I wasn't aware there is a difference in link target interpretation depending on Ajaxify settings (not really self explaining)
