### ISSUE TITLE
Cannot add PHP Plugin to an edit List item

### ISSUE THREAD

**Issue by bumpsadmin** [joomlahenk/fabrik#591]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
List view made without a plugin. Added PHP plugin for Javascript fields. On Save it reports success but plugin has not saved.

**Expected behavior**
Add plugin on list form and its available when saved.

**Actual behavior**
As above on how to reproduce. Tried other options from dropdown but no save either.

**Screenshots**

![image](https://user-images.githubusercontent.com/87337728/207088950-3cdb4bf4-7a9c-4740-b263-9fb771f7b366.png)
![image](https://user-images.githubusercontent.com/87337728/207089806-9eec6256-1fbc-4622-91d8-0e1dca85d4b1.png)

**Additional context**

**Comment by trob** [comment]
I can't replicate.
Is this with any of your lists or a special one?

**Comment by skurvish** [comment]
@bumpsadmin you should update to the latest version and then apply the cumulative update file from issue #548 then try again.

**Comment by bumpsadmin** [comment]
Thanks for the reply, its a standard list but will apply the cumulative update as requested and will get back

**Comment by bumpsadmin** [comment]
Hi all,
Just rebuilt with cumulative update added from #548 and all is working. Thanks for the steer @trob and @skurvish
