### ISSUE TITLE
OnAfterProcess Form php plugin submission not getting calc values 

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#592]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**
J!4.2.5 and Fabrik 4.0beta3a

**To Reproduce**
Setup a form with a php plugin OnAfterProcess event
setup a Ajax calc element e.g
```
$test = "hello";
return $test;
```

return the calc element in the form php plugin
```
$test = '{aaa_claims___test_raw}';
var_dump($test);
exit;
```

**Expected behavior**
Should return "Hello"

**Actual behavior**
var_dump shows
string(23) "{aaa_claims___test_raw}"

**Screenshots**

**Additional context**
I have exactly same form in fabrik alpha 3 and it works fine

**Comment by trob** [comment]
See http://fabrikar.com/forums/index.php?wiki/php-form-plugin/#accessing-form-data for onAfter.

You example (trying to access a calc element onAfter via placeholder) is not working in Fabrik3 and also not working in F4
Use e.g.
$formModel->formData['short-element']

**Comment by ontargetWeb** [comment]
Thank You @trob and apologies for my ignorance. I have updated my code as per the wiki and the calc data is now sending. Strangely I have other forms using both Fabrik 3 and 4Alfa using exactly the method i described above and they do work. I am now going to update them to this more robust method.
