### ISSUE TITLE
Install fail: BLOB, TEXT, GEOMETRY or JSON column 'default' can't have a default value

### ISSUE THREAD

**Issue by thommangooo** [joomlahenk/fabrik#594]
I got a installation fail msg when installing F4 beta 3.  I've had so many problems trying to get a working upgrade from J3-> J4 that I took an odd route to get to the point of installing it.  Started with a clean environment and did the following:
1) installed J3.10
2) Installed F3 +several fabrik plug-ins
3) copied my fabrik tables into the new install
4) confirmed all the tables worked properly
5)deactivated all Fabrik plug-ins
6) upgraded to J4
7) installed the beta 3 Fabrik - got this error: BLOB, TEXT, GEOMETRY or JSON column 'default' can't have a default value

**Comment by trob** [comment]
> copied my fabrik tables into the new install

From where - i.e. which Fabrik version has the installation you took these fabrik tables from?

**Comment by trob** [comment]
@thommangooo : Does it show a table name? Can you check your _fabrik_elements table structure?
@skurvish 
fabrik_elements has column `default` TEXT
Maybe from old F3 versions it has a default set. In the 4.0.sql update file this column is missing, maybe it should be added with DROP DEFAULT

**Comment by skurvish** [comment]
As far as I can see this column has never had a default. I looked at all the original fabrik sql and updates and there is no default there. However, it appears we snuck a default value in on beta3. I will add a drop default into the update sql. This is probably a good reason to create a beta4.

**Comment by skurvish** [comment]
@thommangooo We have a new install that will correct this,, should be out in a few days. In the mean time, prior to installing F4 on your J4 upgraded site, using phpmyadmin go to your database and open the sql window. Place the following into the window and click go. You should then be able to install F4 OK.

`ALTER TABLE `#__fabrik_elements` ALTER `default` DROP DEFAULT;`

**Comment by skurvish** [comment]
You will need to change the #__fabrik_elements and put in your table prefix before you execute this.

**Comment by thommangooo** [comment]
Thanks.  I've kinda started from scratch again on a local machine.  After disabling everything I can find and upgrading to J4, and before applying the fix you mentioned, I'm getting some errors showing when I go to Database Maintenance in the J4 control panel and I'm unsure whether I'm supposed to fix these errors before installing F4 or ignore them.  I tried dropping the default column from the elements table, but I try running update and get:  

"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''#__fabrik_ratings WHERE field = 'listid' AND UPPER(type) REGEXP '^INT([(][0-9]+' at line 1.  There are tables not up to date."

I will probably try applying F4 while awaiting a response on this.  Fingers Crossed!

**Comment by skurvish** [comment]
If you read the wiki on upgrading you would note we advise that there will be database warnings which you can safely ignore.

**Comment by thommangooo** [comment]
Okay, I've tried again and it failed again.  With the default column dropped from elements in F3 on J4, I got an error mentioning the default column.  After restoring the elements table so that it has the default column again, I tried installing again and, as with 2nd attempts on other hosts, I get a number of path related errors:

Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/css
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/js
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/sef_ext
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/dbdriver
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/driver
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/query
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/fabrik
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/Document
BLOB, TEXT, GEOMETRY or JSON column 'default' can't have a default value
Package Update: There was an error installing an extension: com_fabrik_4.0beta3a.zip

**Comment by trob** [comment]
You should not drop the column but only the column default setting.

```ALTER TABLE b6nts_fabrik_elements ALTER COLUMN `default` DROP DEFAULT```
Replace b6nts with your Joomla prefix

**Comment by skurvish** [comment]
Those Path is not a folder warnings are because they were deleted on a previous install of beta3, you can safely ignore them.

**Comment by thommangooo** [comment]
Okay, I will ignore those, but the install still fails and fabrik doesn't show up in the components menu.

**Comment by skurvish** [comment]
@thommangooo can you try installing this: https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0-2022-12-14.zip

**Comment by thommangooo** [comment]
I tried it and I get a result of Unexpected token '<', ".   Fabrik doesn't appear in the components menu.  I'm using php 8.1.0, btw.

**Comment by skurvish** [comment]
Hmm, I just installed it and it installed fine. Can you turn joomla debug on and set error reporting to maximum and try again? This should tell us where the error is.

**Comment by thommangooo** [comment]
With debug on and messages set to max, I get the following messages:

Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/css
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/js
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/sef_ext
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/dbdriver
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/driver
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/query
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/fabrik
Joomla\CMS\Filesystem\Folder::delete: Path is not a folder. Path: [ROOT]/components/com_fabrik/Document
Incorrect datetime value: '' for column 'created' at row 1
Package Update: There was an error installing an extension: com_fabrik_4.0-2022-12-14.zip

**Comment by skurvish** [comment]
did you have joomla debug enabled and error reporting to maximum?

**Comment by skurvish** [comment]
And maybe the database warnings might show which table this is in. There should be no tables with an empty string for a datetime column.

**Comment by skurvish** [comment]
Oh, you did say it was on. Sorry. Anything in the database warnings?

Again, you can safely ignore the path is not a folder warnings.

**Comment by thommangooo** [comment]
Yes.  it didn't seem like much of a message so i double checked that it was on, ran it again and results were the same.  Here's the query msgs:

26 statements were executed, 2 of which were duplicates, 24 unique28.33ms1.7MB
UniquesDuplicates 1Duplicates 2Duplicates 3Duplicates 4Duplicates 5Duplicates 6Duplicates 7Duplicates 8Duplicates 9UniquesDuplicates 1UniquesDuplicates 1
SELECT @@SESSION.sql_mode;1.11ms1.59KB/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:293Copy
SELECT `data`
FROM `soft_session`
WHERE `session_id` = ?4.53ms1.56MBParams/libraries/vendor/joomla/session/src/Handler/DatabaseHandler.php:261Copy
SHOW FULL COLUMNS FROM `soft_users`935μs2.3KB/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:584Copy
SELECT *
FROM `soft_users`
WHERE `id` = :userid756μs4.62KBParams/libraries/src/Table/User.php:104Copy
SELECT `g`.`id`,`g`.`title`
FROM `soft_usergroups` AS `g`
INNER JOIN `soft_user_usergroup_map` AS `m` ON `m`.`group_id` = `g`.`id`
WHERE `m`.`user_id` = :muserid746μs2.35KBParams/libraries/src/Table/User.php:132Copy
SELECT `session_id`
FROM `soft_session`
WHERE `session_id` = :session_id LIMIT 1425μs1.65KBParams/libraries/src/Session/MetadataManager.php:187Copy
UPDATE `soft_session`
SET `guest` = :guest
	, `time` = :time
	, `userid` = :user_id
	, `username` = :username
	, `client_id` = :client_id
WHERE `session_id` = :session_id2.57ms1.01KBParams/libraries/src/Session/MetadataManager.php:316Copy
SELECT `extension_id` AS `id`,`element` AS `option`,`params`,`enabled`
FROM `soft_extensions`
WHERE `type` = 'component' AND `state` = 0 AND `enabled` = 1816μs1.59KB/libraries/src/Component/ComponentHelper.php:393Copy
SELECT `id`,`rules`
FROM `soft_viewlevels`341μs2.3KB/libraries/src/Access/Access.php:955Copy
SELECT `b`.`id`
FROM `soft_user_usergroup_map` AS `map`
LEFT JOIN `soft_usergroups` AS `a` ON `a`.`id` = `map`.`group_id`
LEFT JOIN `soft_usergroups` AS `b` ON `b`.`lft` <= `a`.`lft` AND `b`.`rgt` >= `a`.`rgt`
WHERE `map`.`user_id` = :userId974μs1.7KBParams/libraries/src/Access/Access.php:868Copy
SELECT `folder` AS `type`,`element` AS `name`,`params` AS `params`,`extension_id` AS `id`
FROM `soft_extensions`
WHERE `enabled` = 1 AND `type` = 'plugin' AND `state` IN (0,1) AND `access` IN (:preparedArray1,:preparedArray2,:preparedArray3,:preparedArray4,:preparedArray5)
ORDER BY `ordering`2.48ms3.94KBParams/libraries/src/Plugin/PluginHelper.php:283Copy
SELECT `id`,`name`,`rules`,`parent_id`
FROM `soft_assets`
WHERE `name` IN (:preparedArray1,:preparedArray2,:preparedArray3,:preparedArray4,:preparedArray5,:preparedArray6,:preparedArray7,:preparedArray8,:preparedArray9,:preparedArray10,:preparedArray11,:preparedArray12,:preparedArray13,:preparedArray14,:preparedArray15,:preparedArray16,:preparedArray17,:preparedArray18,:preparedArray19,:preparedArray20,:preparedArray21,:preparedArray22,:preparedArray23,:preparedArray24,:preparedArray25,:preparedArray26,:preparedArray27,:preparedArray28,:preparedArray29,:preparedArray30,:preparedArray31,:preparedArray32,:preparedArray33,:preparedArray34,:preparedArray35,:preparedArray36,:preparedArray37,:preparedArray38)1.58ms8.03KBParams/libraries/src/Access/Access.php:357Copy
SELECT `s`.`template`,`s`.`params`,`s`.`inheritable`,`s`.`parent`
FROM `soft_template_styles` AS `s`
LEFT JOIN `soft_extensions` AS `e` ON `e`.`type` = 'template' AND `e`.`element` = `s`.`template` AND `e`.`client_id` = `s`.`client_id`
WHERE `s`.`client_id` = 1 AND `s`.`home` = '1'
ORDER BY `s`.`home`473μs1.04KB/administrator/components/com_templates/src/Model/StyleModel.php:739Copy
SELECT `element`,`name`,`client_id`,`extension_id`
FROM `soft_extensions`
WHERE `type` = 'language' AND `state` = 0 AND `enabled` = 1523μs1.07KB/libraries/src/Language/LanguageHelper.php:213Copy
SELECT `m`.`id`,`m`.`title`,`m`.`module`,`m`.`position`,`m`.`content`,`m`.`showtitle`,`m`.`params`,`mm`.`menuid`
FROM `soft_modules` AS `m`
LEFT JOIN `soft_modules_menu` AS `mm` ON `mm`.`moduleid` = `m`.`id`
LEFT JOIN `soft_extensions` AS `e` ON `e`.`element` = `m`.`module` AND `e`.`client_id` = `m`.`client_id`
WHERE 
(
(
(`m`.`published` = 1 AND `e`.`enabled` = 1 AND `m`.`client_id` = :clientId AND `m`.`access` IN (:preparedArray1,:preparedArray2,:preparedArray3,:preparedArray4,:preparedArray5)) AND 
(`m`.`publish_up` IS NULL OR `m`.`publish_up` <= :publishUp)) AND 
(`m`.`publish_down` IS NULL OR `m`.`publish_down` >= :publishDown)) AND 
(`mm`.`menuid` = :itemId OR `mm`.`menuid` <= 0)
ORDER BY `m`.`position`,`m`.`ordering`2.43ms3.59KBParams/libraries/src/Cache/Controller/CallbackController.php:52Copy
SELECT `language_extension`,`language_client_id`,`condition_file`,`condition_method`
FROM `soft_postinstall_messages`
WHERE `enabled` = 1361μs1.05KB/libraries/src/Cache/Controller/CallbackController.php:52Copy
SELECT *
FROM `soft_extensions`
WHERE `element` = :element AND `type` = :type LIMIT 1692μs7.24KBParams/libraries/src/Extension/ExtensionHelper.php:479Copy
SELECT `a`.*,`u`.`name` AS `user_from`
FROM `soft_messages` AS `a`
INNER JOIN `soft_users` AS `u` ON `u`.`id` = `a`.`user_id_from`
WHERE `a`.`user_id_to` = :id AND `a`.`state` = :state
ORDER BY a.date_time DESC480μs2.84KBParams/libraries/src/MVC/Model/BaseDatabaseModel.php:165Copy
SELECT a.id, a.title, a.menutype, CASE COALESCE(SUM(m.home), 0) WHEN 0 THEN '' WHEN 1 THEN CASE m.language WHEN '*' THEN 'class:icon-home' ELSE CONCAT('image:', l.lang_code) END ELSE 'image:mod_languages/icon-16-language.png' END AS icon
FROM soft_menu_types AS a
LEFT JOIN soft_menu AS m ON m.menutype = a.menutype AND m.home = 1 LEFT JOIN soft_languages AS l ON l.lang_code = m.language
WHERE a.client_id = 0
GROUP BY a.id, a.title, a.menutype, m.language, l.lang_code
ORDER BY a.id DESC1.23ms1.09KB/administrator/components/com_menus/src/Helper/MenusHelper.php:809Copy
SELECT title, menutype
FROM soft_menu_types
WHERE client_id = 1
ORDER BY id DESC269μs912B/administrator/components/com_menus/src/Helper/MenusHelper.php:809Copy
SELECT `m`.*,`e`.`element`
FROM `soft_menu` AS `m`
LEFT JOIN `soft_extensions` AS `e` ON `m`.`component_id` = `e`.`extension_id`
WHERE 
(`m`.`menutype` = :menutype AND `m`.`client_id` = 1 AND `m`.`id` > 1) AND 
(`e`.`enabled` = 1 OR `e`.`enabled` IS NULL)
ORDER BY `m`.`lft`1.5ms5.66KBParams/administrator/components/com_menus/src/Helper/MenusHelper.php:353Copy
SELECT `enabled`
FROM `soft_extensions`
WHERE `type` = 'plugin' AND `folder` = 'system' AND `element` = 'languagefilter'718μs872B/libraries/src/Language/Multilanguage.php:82Copy
SELECT *
FROM `soft_template_styles`
WHERE `client_id` = 0 AND `id` = '9'524μs41.29KB/plugins/system/helixultimate/src/Platform/Helper.php:54Copy
SELECT `a`.`id`,`a`.`asset_id`,`a`.`title`,`a`.`type`,`a`.`execution_rules`,`a`.`state`,`a`.`last_exit_code`,`a`.`locked`,`a`.`last_execution`,`a`.`next_execution`,`a`.`times_executed`,`a`.`times_failed`,`a`.`priority`,`a`.`ordering`,`a`.`note`,`a`.`checked_out`,`a`.`checked_out_time`,`uc`.`name` AS `editor`
FROM `soft_scheduler_tasks` AS `a`
LEFT JOIN `soft_users` AS `uc` ON `uc`.`id` = `a`.`checked_out`
WHERE `a`.`state` = :state AND `a`.`next_execution` <= :now
ORDER BY `a`.`title` asc790μs4.66KBParams/administrator/components/com_scheduler/src/Model/TasksModel.php:391Copy
SELECT `a`.`id`,`a`.`asset_id`,`a`.`title`,`a`.`type`,`a`.`execution_rules`,`a`.`state`,`a`.`last_exit_code`,`a`.`locked`,`a`.`last_execution`,`a`.`next_execution`,`a`.`times_executed`,`a`.`times_failed`,`a`.`priority`,`a`.`ordering`,`a`.`note`,`a`.`checked_out`,`a`.`checked_out_time`,`uc`.`name` AS `editor`
FROM `soft_scheduler_tasks` AS `a`
LEFT JOIN `soft_users` AS `uc` ON `uc`.`id` = `a`.`checked_out`
WHERE `a`.`state` = :state AND `a`.`locked` IS NOT NULL
ORDER BY `a`.`title` asc597μs4.63KBParams/administrator/components/com_scheduler/src/Model/TasksModel.php:391Copy
SELECT *
FROM `soft_template_styles`
WHERE `client_id` = 0 AND `id` = '9'

**Comment by skurvish** [comment]
Can you check one other thing for me? In your administrator/components/com_fabrik/sql/updates/mysql do you have any files?

**Comment by skurvish** [comment]
I have an idea there will not be.

**Comment by skurvish** [comment]
OK, they should have run then. This was an install on top of beta3? Any chance you can install one of the beta2 releases and then this latest one? I am at a loss as it install just fine on my upgraded system.

**Comment by thommangooo** [comment]
I didn't download beta 2, is there still a link for it?  (Git newbie here.)

**Comment by skurvish** [comment]
https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta2c.zip

I am away the rest of today. If that doesn't solve the issue I may need to get onto your site. I assume this is a test site yes? Can you email me access information to achartier at admiralsecure dot com. I will be able to look at it again in the morning.

**Comment by thommangooo** [comment]
Thanks. I’ve got some real-world things on the go now too.  Will try this aft and update.

**Comment by thommangooo** [comment]
Same result, I'm sorry to say.

**Comment by trob** [comment]
I just did an upgrade

J!3.10.11 /Fabrik3.10(+Fabrik3-GitHub, so it was running with php8.1)

- Disable all Fabrik
- Update J! to 4.2.6
- Install https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0-2022-12-14.zip via J! Installer
- No issues at all (no folder warnings, no mySQL warnings/errors)
- Enable all Fabrik 4.0 plugins

All it there.

So no idea what is going on on your site.
Check your System Infomation:
Are your folders writable (i.e. also deletable)?
What is your PHP version?
Your database type and version?

**Comment by thommangooo** [comment]
I'm seeing the same results in two different environments.  One is hosted by siteground.  The other is on my local machine.  Both are using php 8.1.  Both are using MYSQLi.  The local MYSQL is 5.7.34.  File permissions are 755.

**Comment by skurvish** [comment]
I have another user with the same problem. I was able to obtain an akeeba backup of his site and tomorrow morning I will figure out what is going on. Stand by.

**Comment by skurvish** [comment]
Closes as fixed in beta4
