### ISSUE TITLE
Upgrade: cumulative_12_14_2022.zip ERROR

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#595]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**What happend**
Unzipping it leads to **0
Class "Factory" not found**

**To Reproduce**
Unzip cumulative_12_14_2022.zip into root dir
Previous 4.0beta3a

**Comment by skurvish** [comment]
Where is this happening? Did you remember to double slash your classnames in use statements or if you call the full class directly? Please see the note in the upgrade wiki.

**Comment by skurvish** [comment]
If you have php in all of your fabrik lists and forms used in direct input as opposed to inside a file, you need to double slash all of the elements of a class path. Please use the tool referenced in the upgrade wiki to identify where all these places are.
