### ISSUE TITLE
Autofill form plugin js error

### ISSUE THREAD

**Issue by ontargetWeb** [joomlahenk/fabrik#596]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Setup an autofill form plugin.
Origin element X = field element in listA
Destination element Y = field element in listB

**Expected behavior**

Expecting field Y to be populated with data from field X

**Actual behavior**
Page hangs with "performing search" message.
Console log shows:
**_Uncaught TypeError: Cannot read properties of undefined (reading 'element')
    at Object.lookUp (autofill-min.js:3:2597)
    at s.extend.$owner (mootools-core.js:3:17367)
    at Object.doLookup (autofill-min.js:3:884)
    at s.extend.$owner (mootools-core.js:3:17367)
    at mootools-core.js:3:9904_**

**Screenshots**

<img width="781" alt="Screenshot 2022-12-16 at 21 31 05" src="https://user-images.githubusercontent.com/26169616/208192298-72f2171d-4862-4824-831f-d8842899efd5.png">

<img width="832" alt="Screenshot 2022-12-16 at 21 31 38" src="https://user-images.githubusercontent.com/26169616/208192372-f4d87d47-2bd0-4456-9ef8-1e299f720ce1.png">

**Additional context**

**Comment by trob** [comment]
Your map data doesn't look correct (form_plugin_autofill___aa....___...). Element names have only one time 3 underscores (between table and column name).

**Comment by skurvish** [comment]
Failing further followup on this issue by @ontargetWeb I am closing this as resolved. It may be reopened if the problem still persists.
