### ISSUE TITLE
Ftext not found

### ISSUE THREAD

**Issue by thommangooo** [joomlahenk/fabrik#597]
Not sure if this is a bug, but I have a table that works fine in F3/J3.  In F4/J4, it's returning an error: Class "FText" not found.  I will try some hunt and peck with turning elements off, but FText doesn't sound like anything I've used before.  The table in question does use the email plug-in, but I've disabled those in the list and it didn't change the issue.  Any idea?

**Comment by thommangooo** [comment]
Not sure if this is a bug, but I have a table that works fine in F3/J3.  In F4/J4, it's returning an error: Class "FText" not found.  I will try some hunt and peck with turning elements off, but FText doesn't sound like anything I've used before.  The table in question does use the email plug-in, but I've disabled those in the list and it didn't change the issue.  Any idea?

**Comment by trob** [comment]
Enable Joomla's System debug. This should show you the error stack

**Comment by thommangooo** [comment]
Call stack
--
# | Function | Location
1 | () | JROOT/plugins/fabrik_list/email/models/email.php:98
2 | PlgFabrik_ListEmail->buttonLabel() | JROOT/components/com_fabrik/models/plugin-list.php:144
3 | PlgFabrik_List->button_result() | JROOT/components/com_fabrik/models/pluginmanager.php:723
4 | FabrikFEModelPluginmanager->runPlugins() | JROOT/components/com_fabrik/models/list.php:624
5 | FabrikFEModelList->getPluginButtons() | JROOT/components/com_fabrik/models/list.php:1773
6 | FabrikFEModelList->addSelectBoxAndLinks() | JROOT/components/com_fabrik/models/list.php:1413
7 | FabrikFEModelList->formatData() | JROOT/components/com_fabrik/models/list.php:1061
8 | FabrikFEModelList->finesseData() | JROOT/components/com_fabrik/models/list.php:956
9 | FabrikFEModelList->getData() | JROOT/components/com_fabrik/models/list.php:733
10 | FabrikFEModelList->render() | JROOT/components/com_fabrik/views/list/view.base.php:437
11 | FabrikViewListBase->display() | JROOT/components/com_fabrik/views/list/view.html.php:44
12 | FabrikViewList->display() | JROOT/libraries/src/Cache/Controller/ViewController.php:102
13 | Joomla\CMS\Cache\Controller\ViewController->get() | JROOT/components/com_fabrik/controllers/list.php:114
14 | FabrikControllerList->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:672
15 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_fabrik/fabrik.php:200
16 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
17 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
18 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
19 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:200
20 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:241
21 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
22 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
23 | require_once() | JROOT/index.php:32

**Comment by thommangooo** [comment]
Whoops, I had turned off two column update plug ins but not the email one.  Problem gone when I disable it.  Any hope that the email list plug-in is going to be updated?  I've used it extensively.

**Comment by trob** [comment]
Yup. List-email is not included in the current F4 packages.
You should enable only Fabrik plugins with version 4+ (in Extensions/Manage).

**Comment by thommangooo** [comment]
Thanks!
