### ISSUE TITLE
Beta4 installation

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#598]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Upgrade from Beta3 to Beta4

**Expected behavior**
Smooth upgrade

**Actual behavior**
Errors. According to extension manager all fabrik extensions have the right version, but there are database errors. (see screenshots)
Data of one list is not available (third screenshot). 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18248764/208477645-6f5795d7-3608-4ac7-862c-fbc4fe4f9b22.png)
![grafik](https://user-images.githubusercontent.com/18248764/208477792-68795ebf-bbb6-4e6c-8cd7-49b6492b62c4.png)
![grafik](https://user-images.githubusercontent.com/18248764/208479054-c314af80-2e48-471a-a69d-03801ab68307.png)

**Additional context**

**Comment by wezetel** [comment]
Sorry, just did a repair. Now only the xxx_fabrik_cron error remains.
But the "Class 'Factory' not found" still exists.
Need to check my code, as this error only occurs with one list...

**Comment by trob** [comment]
Enable J! System Debug to get the error stack where "Factory" is coming from.

**Comment by wezetel** [comment]
I assume, the error results from a calc field, where I do a database query:

$anliegenid= (int)'{terminanfrage___anliegen_raw}';

use Joomla\CMS\Factory;
use Joomla\Database\DatabaseInterface;

$myDb = Factory::getContainer()->get(DatabaseInterface::class);

$myQuery = $myDb->getQuery(true);

$myQuery
    ->select('hinweis')
   ->from('anliegen')
    ->where('id = ' . $anliegenid);

$myDb->setQuery($myQuery);
$fieldA = $myDb->loadResult();
return $fieldA;

This is the call stack
![grafik](https://user-images.githubusercontent.com/18248764/208482938-6279ba6d-f050-4dcd-af7b-8a87c7ab7645.png)

**Comment by skurvish** [comment]
You must double slash all of the classname paths in any php code that is included in calcs, evals etc. This is noted on the F3-F4 upgrade wiki.

**Comment by skurvish** [comment]
@wezetel can you tell me the filenames of any files located in administrator/components/com_fabrik/sql/updates/mysql please?

**Comment by wezetel** [comment]
As I never did an upgrade, just fresh F4 installs, I didn't read the upgrade instructions :-)

In the mentioned directory there is only one file: 4.0-2022-12-18.sql

**Comment by skurvish** [comment]
Great, thank you. I will have an updated beta4a ready for you momentarily.

**Comment by skurvish** [comment]
OK, try this https://skurvishenterprises.com/fabrik/downloads/pkg_fabrik_4.0beta4a.zip

**Comment by trob** [comment]
Installation is now successfull.
But there's still the "Database Problem" 
![image](https://user-images.githubusercontent.com/1045355/208498655-aa7ea9bc-6111-426e-8e58-c1d170e0712a.png)

Is seems as if the UPDATE statements are not run at all.
These two tables have NULL values in `created`. If I run "Update structure" nothing changes (no values updated and so setting `created` NOT NULL  not working)

If I run the UPDATE statement in phpMyAdmin it's working as expected.
And if I run then "Update structure" again it will do the 
ALTER TABLE `#__fabrik_lists` MODIFY `created` datetime NOT NULL;

Maybe UPDATE statements are ignored in the sql files?

**Comment by trob** [comment]
Yup. And I think they only show up if something got wrong before with one of the old alphas/betas.

**Comment by wezetel** [comment]
Strange: I have a second field of type date (not jdate). With allowed dates!!! And if I'm doing the double backslash ( as mentiond in the upgrader instuctions) I'm getting errors.
These errors are gone, when I remove the double backslashes, but a new error occurs:
![grafik](https://user-images.githubusercontent.com/18248764/208502779-411ce3d1-162a-4229-bbb7-b1d624ea670a.png)

**Comment by trob** [comment]
This is only a deprecated warning which only shows up if you have J! System debug enabled.
I assume we must have a look at the date element for this. But for now you can ignore it.

**Comment by skurvish** [comment]
> Installation is now successfull. But there's still the "Database Problem" ![image](https://user-images.githubusercontent.com/1045355/208498655-aa7ea9bc-6111-426e-8e58-c1d170e0712a.png)
> 
> Is seems as if the UPDATE statements are not run at all. These two tables have NULL values in `created`. If I run "Update structure" nothing changes (no values updated and so setting `created` NOT NULL not working)
> 
> If I run the UPDATE statement in phpMyAdmin it's working as expected. And if I run then "Update structure" again it will do the ALTER TABLE `#__fabrik_lists` MODIFY `created` datetime NOT NULL;
> 
> Maybe UPDATE statements are ignored in the sql files?

@trob when you installed beta4a what F4 was installed at the time? Or was it a F3 upgrade? The sql update file should run on upgrade from F3. If F4 to F4 it might depend on what you had before.

**Comment by skurvish** [comment]
> Strange: I have a second field of type date (not jdate). With allowed dates!!! And if I'm doing the double backslash ( as mentiond in the upgrader instuctions) I'm getting errors. These errors are gone, when I remove the double backslashes, but a new error occurs: ![grafik](https://user-images.githubusercontent.com/18248764/208502779-411ce3d1-162a-4229-bbb7-b1d624ea670a.png)

Missed a stripslashes. In plugins/fabrik_element/jdate/jdate.php at line 977, and plugins/fabrik_element/date/date.php at line 952 , change the lines to read:

`$php    = stripslashes($params->get('date_allow_php_func', ''));`

**Comment by skurvish** [comment]
I expect the getLanguage deprecated is coming from a previous error that wasn't captured. Ignore it.

**Comment by skurvish** [comment]
Quick update, the line is different in each file.

id date.php it is as you see above. In jdate it should be:
`$php    = stripslashes($params->get('jdate_allow_php_func', ''));`

note that for date it is date_allow_php_func and for jdate it is jdate_allow_php_func

**Comment by dimoss** [comment]
Trying to update from F4 (ver. 8-12-2022) I got the following error.
![image](https://user-images.githubusercontent.com/10183465/208604841-b06b69b2-9a5b-4444-9768-5f16b0dcc536.png)

I got two DB errors which were resolved after updating structure.
My F4 installation is clean on a fresh J4. No upgrade from F3.

**Comment by wezetel** [comment]
@skurvish Can it be you mixed the line numbers for the stripslashes for jdate.php and date php?

**Comment by trob** [comment]
> @trob when you installed beta4a what F4 was installed at the time? Or was it a F3 upgrade? The sql update file should run on upgrade from F3. If F4 to F4 it might depend on what you had before

Installation was running without error (on existing F3 and F4, so the install.sql with CREATE TABLE IF EXISTS will do nothing).
I think this is Joomla checking the database structure against the update sql files **after** the installation.
And it seems at this point with "Update structure" it's not running the "UPDATE xy" (because this is no strucural update but content?)

**Comment by skurvish** [comment]
> @skurvish Can it be you mixed the line numbers for the stripslashes for jdate.php and date.php?

Yes, I did, sorry. It was late in the day for me. The line numbers are reversed.

**Comment by skurvish** [comment]
> Trying to update from F4 (ver. 8-12-2022) I got the following error. ![image](https://user-images.githubusercontent.com/10183465/208604841-b06b69b2-9a5b-4444-9768-5f16b0dcc536.png)
> 
> I got two DB errors which were resolved after updating structure. My F4 installation is clean on a fresh J4. No upgrade from F3.

This one I found and have now fixed (pending creating a new package). Somehow some extraneous text git into that file. I use a dual screen system and some times when I think I am typing on one screen I am actually typing on the other one. I usually catch this but apparently not this time.

**Comment by skurvish** [comment]
@wezetel  please try the beta4b linked on the tester wiki page.

**Comment by wezetel** [comment]
database version 10.3.37-MariaDB-cll-lve

**Comment by wezetel** [comment]
beta4b still has the xxxx_fabrik_cron database error.
Regarding double backslashes: not only class names need the second backslash applied. As soon as there is a backslash it needs to be double. I had the problem with building a sql-query and escaped the apostrophes ....
At the moment I have another problem. but I need to build a clean testcase before I open another issue.

**Comment by skurvish** [comment]
@wezetel which database error for fabrik_cron. During the install or in the database warnings section.

**Comment by wezetel** [comment]
Just in the database warnings section.

**Comment by skurvish** [comment]
OK, when you get a chance can you attach a screen grab for me.

**Comment by wezetel** [comment]
Is this sufficient?
![grafik](https://user-images.githubusercontent.com/18248764/208732615-2f9fdedf-3463-4819-abbf-df56001e07f2.png)

**Comment by dimoss** [comment]
@skurvish Upgrade from Beta4a to Beta4b I get the following in the database warning section.

![image](https://user-images.githubusercontent.com/10183465/208756101-d9c2cc83-9eed-4b0c-ad16-19244571692e.png)

**Comment by skurvish** [comment]
We believe this is an artifact of a bad install with one of the previous updates. You can safely ignore these messages, and indeed updating table structure clears them. Most people will not get this, especially if they are just starting. It is only our leading edge testers that have run into it. That's why we call these betas.

**Comment by skurvish** [comment]
Closing this. Only people affected by the database issues are those who installed a previous beta and the issue can be resolved by updating the table structure.
