### ISSUE TITLE
JSON string broken if "params" fields of the database tables fabrik_lists or fabrik_forms is too long

### ISSUE THREAD

**Issue by juuser99** [joomlahenk/fabrik#599]
**To Reproduce**
Add plugin code to any list or form which is longer than 65500 characters.

**Expected behavior**
Everything should work normally.

**Actual behavior**
list / form does not open anymore as JSON string in "params" field is cut off at the end.

**Additional context**
This has happened to me twice when I have had many plugins with a lot of code (some disabled) for testing.

**How to solve**
Change "params" field type of #__fabrik_lists and #__fabrik_forms from TEXT to LONGTEXT.

**Comment by skurvish** [comment]
The params fields in these tables have always been of type TEXT which is limited to 65500. Do you have a J3 table with params columns larger than this?

**Comment by juuser99** [comment]
> The params fields in these tables have always been of type TEXT which is limited to 65500. Do you have a J3 table with params columns larger than this?

Yes, I have in some cases where I run a lot of PHP plugins in different conditions and stages. So far I have changed the field types from TEXT to LONGTEXT in PhpMyAdmin. But sometimes I have forgot to do it and yesterday had this problem again where I needed to recover the broken field from a backup.

**Comment by skurvish** [comment]
Ah, so, user memory error. I don't see any reason we cannot change that field to a longer text type. I am surprised this hasn't come up before. Did you report it back in F3 days? If so did you get any response?

**Comment by juuser99** [comment]
No, didn't report in F3 days as the support was already gone by that time :( Just made this change myself in PhpMyAdmin for mty existing sites.

**Comment by skurvish** [comment]
OK, I am discussing with the other devs if we can simply change it to LONGTEXT. I don't see an issue, but need to run it by them. I am going to close this issue now but will update it if we decide to go ahead with the change.

**Comment by juuser99** [comment]
Excellent! Thank you!
