### ISSUE TITLE
Button element missing

### ISSUE THREAD

**Issue by johnonorvic** [joomlahenk/fabrik#600]
Why does Status of Plugins show Element:button as “Planned for Fabrik4? - No” with Description “Does not work in Fabrik 3.10”. I have a  Fabrik 3.10 based site that has several buttons on various forms that work fine (and which I hope to update to Fabrik4 – with buttons). The Fabrik Wiki describes the button element with examples and I can find nothing in the Forum about it not working.

I presume the button element’s main function is to initiate some javascript actions which it certainly does in Fabrik 3.10. It has a few features that I have not used, but which are not complex and seem less important. As it has far fewer lines of code than the complex elements, hopefully it would not be a lot of trouble to add.

**Comment by trob** [comment]
Yes, it seems the button element is working (also in principle in F4). So maybe in some future version...

**Comment by juuser99** [comment]
I agree that this would be an important element to have. I've helped a few Fabrik users with custom code who have this element in their sites and I'm also using it in some of my own sites. So hoping for the best :)

**Comment by johnonorvic** [comment]
Good news. I do not suppose I could be much help, but if I might be, let me know.

**Comment by isidoroi** [comment]
I share too. Use in Fabrik 3.10 of buttons with javascript command that allows data updating as well as page refresh... therefore indispensable at the moment for existing projects.

**Comment by johnonorvic** [comment]
I have for a while been developing a complex site using Joomla/Fabrik 3, but do not want to do more work until it is updated to Joomla/Fabrik 4. Unfortunately it uses several button elements that can not be easily avoided. “Low Priority” was not encouraging, so my only choices seemed to be to give up or have a go at the button element myself. I choose the latter without much optimism. To my surprise, it seems to work and do what I need. I have not tested it fully, but it displays itself and fires some JS when clicked. It would probably benefit from being looked at by someone who knows more about Fabrik than I do.

If anyone is interested in having a look at it, the plug-in file I have created and files showing the changes in the three files I have modified are attached.

[plg_fabrik_element_button_4.0beta4b.zip](https://github.com/joomlahenk/fabrik/files/10356484/plg_fabrik_element_button_4.0beta4b.zip)
[changes-button_php.txt](https://github.com/joomlahenk/fabrik/files/10356487/changes-button_php.txt)
[changes-button_xml.txt](https://github.com/joomlahenk/fabrik/files/10356488/changes-button_xml.txt)
[changes-en-GB_plg_fabrik_element_button_sys_ini.txt](https://github.com/joomlahenk/fabrik/files/10356490/changes-en-GB_plg_fabrik_element_button_sys_ini.txt)

**Comment by skurvish** [comment]
Thanks for your work John. I will take a look and merge in your changes.

**Comment by skurvish** [comment]
@johnonorvic Having never used this element before I need some help. The bootstrap class setting for the element is intended to define the bootstrap button class. As a dropdown it seems rather limited in this regard as it only allows the selection of the primary  styles and does not allow for outlines etc. In fact, if you allow it to default it doesn't insert a button class at all but a grid class which makes no sense at all.

I propose that we leave this field alone but change its description to be the primary button type, and then we add a couple of additional parameters for the modifiers outline and size. As both of these are binary probably a switcher for the choice. In this way the existing table values will still work and we choose what the default value is for the 2 modifiers.

Also, do you see any need to include a bootstrap grid class? This would enable you to make the button very wide if you wanted it. Alternatively we could include a field to place custom classes into. I note that the header and cell css class fields don't actually do anything so not sure why they are there.

**Comment by johnonorvic** [comment]
@skurvish Thanks for having a look at this. I have only ever used the button as a simple means of firing some JS and never changed anything else, being happy with the default formatting.

Initially, I found the options section at the bottom did not appear in Fabrik4. Although I did not need it, I thought it ought to be there and found the line “<folder>forms</folder>” was missing from button.xml. (Why the section appeared in Fabrik3 I do not know.)

Also, initially the button appeared with a transparent background and transparent border, which seems to be the default for Cassiopeia. I found that changing the line in the render function in button.php from ' fabrikinput button btn' to 'btn-secondary button btn' gave a satisfactory appearance, similar to the equivalent in Fabrik3. (I have no idea what the “ fabrikinput” was intended to do.)

For my purposes, I see no great need for changing the formatting of a button from the present default. I chose “btn-secondary” to differentiate the button from form standard buttons (save, delete etc.) that have “btn-primary”.

I am sure you are much better qualified than me to decide exactly what options, if any, should be provided.

This is a quick reply as I have to go out shortly; if I think of anything else, I will reply again later.

**Comment by skurvish** [comment]
There is no need to add the btn-secondary in the render function. Simply select secondary from the bootstrap_class dropdown and it will be inserted for you.

For now then we can leave it alone, but do need to do something about the default inserting a bootstrap grid class.

**Comment by johnonorvic** [comment]
@skurvish I have now had another look at this and understand it a little better. I see that there was no need to change the line in the render function setting $class. To be tidy, I have attached a revised package with the original line restored.

Only for the possible benefit of others converting to Fabrik4 and using buttons, I will mention that, in Fabrik3 with Protostar, leaving “Bootstrap class” as “Default” produces a sensible secondary button, but in Fabrik4 with Cassiopeia, it produces a transparent button, so setting “Bootstrap class” to “Secondary” is probably necessary after the update.

Thanks again for your help and patience.
[plg_fabrik_element_button_4.0beta4b.zip](https://github.com/joomlahenk/fabrik/files/10366353/plg_fabrik_element_button_4.0beta4b.zip)

**Comment by skurvish** [comment]
Added to the package for next build. Closing.
