### ISSUE TITLE
JFactory::getDbo() deprecated

### ISSUE THREAD

**Issue by dimoss** [joomlahenk/fabrik#601]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Changing depreacted code in calc element based on upgrading instruction to replace Factory::getDbo() to:
$db = version_compare(\Joomla\CMS\Version::MAJOR_VERSION, "4", ">=") ? Factory::getContainer()->get('DatabaseDriver') : Factory::getDbo();

**Expected behavior**
Removing notice:
Joomla\CMS\Factory::getDbo() is deprecated. Load the database from the dependency injection container.

**Actual behavior**
Error:
Class "JoomlaCMSVersion" not found

**Screenshots**

**Additional context**
Using J!4.2.5 with F4.0beta4b in a clean J!4+F4 test site.

**Comment by trob** [comment]
I didn't test.
But I think
1. if you know you are on J!4 you don't need the version compare at all
2. in calc elements etc you need to escape \ (so use \\ in these cases)

**Comment by dimoss** [comment]
> I didn't test. But I think
> 
> 1. if you know you are on J!4 you don't need the version compare at all
> 2. in calc elements etc you need to escape \ (so use `\\` in these cases)
> 
> 🎄🎄🎄

Thanks @trob 

Found a solution based on this [https://github.com/joomla/joomla-cms/discussions/38111](url) escaping \ as you suggested. So the final one for calc element is:

use Joomla\\CMS\\Factory;
use Joomla\\Database\\DatabaseInterface;
$db = Factory::getContainer()->get(DatabaseInterface::class);

On a separate note I used the same in j4upgrade.php file provided by @skurvish and works fine. Thanks @skurvish for the file.

Merry Christmas to everyone!

**Comment by wezetel** [comment]
I have to admit: I'm too stupid to implement this solution, even this is not the first try to avoid the depreciated warning. I just can get my application working with the old solution.
In the following picture you see what is working in a calc element:
![grafik](https://user-images.githubusercontent.com/18248764/209480008-1d282014-9b46-44f7-9f20-d05ddfe593ca.png)
If I comment out line 7 and and enable lines 3 to 5 my application hangs.
Probably I'm to blind to see what is wrong with the code, so any hint is welcome

**Comment by trob** [comment]
Did you try
`Joomla\\CMS\\Factory::Factory::getContainer()->get('DatabaseDriver');`

**Comment by wezetel** [comment]
@trob Just gave it a try. It works, but only if I disable Ajax. 
And that's not really what I need, because the calc field should display a hint to the user depending on the selection of another field. And without Ajax the hint is just stored on save and not displayed.

**Comment by trob** [comment]
Just tested: 
```
use Joomla\CMS\Factory;
use Joomla\Database\DatabaseInterface;
$myDb = Factory::getContainer()->get('DatabaseDriver');
//also working with $myDB = Factory::getContainer()->get(DatabaseInterface::class);
$myQuery = $myDb->getQuery(true);

$myQuery
    ->select(array('feld'))
    ->from('test17')
    ->where('id = ' . $myDb->quote(4));

$myDb->setQuery($myQuery);

$x=$myDb->loadResult();
$y=': {atest2___feld3}';
return $x.$y;
```
is working with Ajax calc, with and without Ajaxfied links.  
It also doesn't matter if you use single or double \ (in the DB it's stored with `\\` resp. `\\\\` anyway because of ???)

If you get a sticky spinner with Ajax calc check your browser's network response to see the error.

You should have "use ..." at the beginning of our code (although I think it doesn't matter).
$anliegenid may be 0 in new records or if not selected?
You have to handle this case to get a result in $fieldA.

**Comment by wezetel** [comment]
Thanks for your efforts, @trob 
At the moment, I don't have success, but as it is working for you and others, I will revisit the problem later again with a little more distance in my head....

**Comment by trob** [comment]
https://fabrikar.com/forums/index.php?threads/updating-deprecated-db-jfactory-getdbo-j4-f4.53657/

**Comment by Tazzios** [comment]
I`m running Joomla 3.10.20 and preparing an upgrade to J5

I changed 
`$db = JFactory::getDbo();`
to 
`use Joomla\CMS\Factory;  
$db = version_compare(\Joomla\CMS\Version::MAJOR_VERSION, "4", ">=") ? Factory::getContainer()->get('DatabaseDriver') : Factory::getDbo();`
 
but that did not work. Changed it to JFactory which worked:
`use Joomla\CMS\Factory;  $db = version_compare(\Joomla\CMS\Version::MAJOR_VERSION, "4", ">=") ? Factory::getContainer()->get('DatabaseDriver') : JFactory::getDbo();`

I assume the code now wil work for J3 and J5 I`m i correct?

**Comment by trob** [comment]
This is a closed issue in an outdated GitHub.
Please see https://fabrikar.com/forumss and https://fabrikar.com/forums/index.php?wiki/index/
e.g. https://fabrikar.com/forums/index.php?wiki/upgrade-instructions/
and post questions in [fabrikar.com/forums](https://fabrikar.com/forums)
