### ISSUE TITLE
2 column PDF Output moves subsequent groups to sub.groups of first group

### ISSUE THREAD

**Issue by fstorch** [joomlahenk/fabrik#603]
My site is using several 2 column groups in a form.
I'm having a hard time, to set the widths in order to get a 2-column PDF Output as well.
It seems this might be caused by missing a closing div in a group that has an uneven number of elements.
Rebuilt a Test Form (using bootstrap PDF Template) like this:
![grafik](https://user-images.githubusercontent.com/34415681/209576808-ac17b362-f812-47e4-97e8-60deb61ee9f5.png)

**Expected behavior**
Each of the three groups should be on the same level.

**Actual behavior**
Group 2 and 3 are sub-groups of group 1.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34415681/209576862-a49ff555-36a4-4a56-a63c-60647954e258.png)

**Comment by trob** [comment]
What are you doing?
domPDF still doesn't support float or flex (I think), you still have to create a custom PDF template (copy the recent bootstrap details view) and add custom CSS for the bootstrap classes (in F4 now BS5 ones).

So something like

.row:after {clear: both;}
.col-sm-6 {display:inline-block;width:45%;}

should do for 2-col groups.

**Comment by fstorch** [comment]
That's what I'm trying to do, but face the issue with the incorrectly nested groups. That's why I recreated with plain bootstrap first. 
I'm trying to get my previous custom template, which worked fine in J!3/F!3, to work with F!4.

**Comment by trob** [comment]
Ok, I can't replicate with my setup but there is some issue with hidden elements in multi column groups. So maybe this is also yours.
Can you try in components\com_fabrik\models\group.php, change around line 550
```
		$rowIx++;
```
to
```
		if (!$element->hidden)
		{
			$rowIx++;
		}
```

**Comment by fstorch** [comment]
Unfortunately the issue didn't change by that.

**Comment by trob** [comment]
> I'm having a hard time, to set the widths in order to get a 2-column PDF Output as well.
Your form screenshot is showing correct groups/columns.

So where to you get the "nested" output, in your PDF?

PDFs are generated with **details** templates. Do have a custom one? Maybe there's a missing <div ?

**Comment by fstorch** [comment]
Sure I use a custom detail view template, where I found that issue.
So I rebuilt a testsite with plain unchanged bootstrap pdf template and the issue recreates with it.
All I did is create three two-column groups, the first and third with three elements (needs to be uneven), the second with two fields (even).
Then set PDF debug to true and use F12 to see the source.
Not sure how I could provide this as a recreate (currently on a wamp server)?

In ~\components\com_fabrik\views\details\tmpl\bootstrap\default_group.php there is:
`$rowStarted = false;`
at the beginning and at the end:
```
// If the last element was not closing the row add an additional div
if ($rowStarted === true) :?>
</div><!-- end row-fluid for open row -->
<?php endif;?>
```
though $rowstarted doesn't seem to be changed.
Whereas in the J4 bootstrap it will be changed.
Not sure if that helps.

**Comment by trob** [comment]
Ok, I can replicate.
But it doesn't look like a quick solution.

**Comment by trob** [comment]
Try 
[MultiColCroup.zip](https://github.com/joomlahenk/fabrik/files/10369540/MultiColCroup.zip)

**Comment by fstorch** [comment]
Thanxalot.
Testcase looks good now:
![grafik](https://user-images.githubusercontent.com/34415681/211221037-3995def3-b889-4c7c-bd12-fd7bcf238941.png)
Will test with main site later.
Requires adopting changes in bootstrap to custom template
