### ISSUE TITLE
Install of Beta 4b gives database warnings

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#604]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Install beya 4b over beta 3a

**Expected behavior**
No database errors

**Actual behavior**
Maintenance: Database shows: 
Warning: Attempt to read property "schemapath" on null inadministrator/components/com_installer/src/Model/DatabaseModel.php on line 180

Warning: Trying to access array offset on value of type null in administrator/components/com_installer/src/Model/DatabaseModel.php on line 180

Warning: Attempt to read property "schemapath" on null in administrator/components/com_installer/src/Model/DatabaseModel.php on line 180

Warning: Trying to access array offset on value of type null in administrator/components/com_installer/src/Model/DatabaseModel.php on line 180

Warning: Attempt to read property "schemapath" on null in administrator/components/com_installer/src/Model/DatabaseModel.php on line 180

Warning: Trying to access array offset on value of type null in administrator/components/com_installer/src/Model/DatabaseModel.php on line 180

**Screenshots**

**Additional context**

**Comment by trob** [comment]
I think this is because of glitches in beta3a.
Is it gone if you do a "Update structure"?

**Comment by EricdeWaal** [comment]
No, it's still there. And the info area shows: "info All database table structures are up to date."
The "Update structure"button is greyd out so does not work.

**Comment by trob** [comment]
These warnings are related to
element sequence
element thums
form comment
(seems Joomla is looking for
`	<update>
		<schemas>
			<schemapath type="mysql">sql/updates/mysql/</schemapath>
		</schemas>
	</update>`
in the XML )

I think for now you can ignore it.


> The "Update structure" button is greyed out so does not work.   

It will become active if you select some entry to update.

**Comment by EricdeWaal** [comment]
> It will become active if you select some entry to update.
Sorry, I missed that. Different from J3 ...
Anyway, updating the Fabrik data structure does not work, the versions still do not match:
![afbeelding](https://user-images.githubusercontent.com/5586423/209943865-f4339fb4-ed77-4b2a-9a75-6c39495fbf96.png)

**Comment by trob** [comment]
The warnings are only thrown if you had some beta3x installed before (superfluous entries in #_schemas).

If you don't need element sequence, element thumbs and form comment plugin you can just uninstall them.
If you need them you can zip the respective plugin folders (each one separately), then uninstall the plugins (will clean up #_schemas) , then install the zips again

>  the versions still do not match 
Database version and manifest version don't need to be the same, see e.g.
![grafik](https://user-images.githubusercontent.com/1045355/211159884-5aaeaf4e-5927-4f8c-ba2a-a00e04e1e4d8.png)

**Comment by EricdeWaal** [comment]
Yes, by uninstalling and reinstalling those 3 plugins the database error disappeared. Thanks!
