### ISSUE TITLE
Group Olumn Widths not working

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#607]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**

Set column width percentages for a group

**Expected behavior**

columns of the specific width

**Actual behavior**

the col width is setting a class with the percentage, rather than setting the proper boostrap 5 class.

**Screenshots**

**Additional context**

**Comment by trob** [comment]
It's working.
You must not set percentages but just bootstrap col numbers like
3,3,6 (to get 25%,25%,50%)
I'm pretty sure this is the same in F3.

**Comment by skurvish** [comment]
Yes, in F3 you could use %. The current code doesn't trim the col number so I will add that.

**Comment by skurvish** [comment]
> Especially also the handling of hidden elements in multi col groups is failing. group.php needs at least ` if (!$element->hidden) { $rowIx++; }` back around line 558 See #603, although this didn't solve his issue.

@trob have you tested this for normal multi column layouts? I would have to do some work to get a setup to test it.

**Comment by trob** [comment]
Yes. I run into it while trying to replicate 603.
Without (!$element->hidden) hidden elements are counted normally, just displayed hidden in the row and so leaving "short" rows.

But there may be still issues with the element->startrow and/or endrow setting if an element is hidden and is the 1st or last element in the row or the form and so causing a missing (or superfluous) div in \components\com_fabrik\layouts\form\fabrik-control-group.php
I had not time to dig into this.

**Comment by skurvish** [comment]
So can we close this one as fixed if we add that if statement into group.php? Issue #603 can still stand on its own.

**Comment by skurvish** [comment]
@trob will this change affect the logic handling the hidden elements at the start of the row, handled around line 526?

**Comment by trob** [comment]
This "change" is only re-adding as it was done in F3 and in my test site it's ok.
But this part of group.php has been changed pretty much so not sure if there's something more.
Keep it in mind and let's wait if anybody is complaining.
