### ISSUE TITLE
No access to records from module list

### ISSUE THREAD

**Issue by EricdeWaal** [joomlahenk/fabrik#608]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Create a list with public access to view list and view records
Create a module to display the list
Create a menu-item to display the list

**Expected behavior**
From both the module and menu the list can be displayed.
From both the records can be displayed

**Actual behavior**
From the menu list the records can be displayed bij clicking the link or magnifying glass
From the module list this results in a 403 error (no rights ...)
Edit: Search does not work either

**Screenshots**

**Additional context**
Edit: when logged in as a superuser, it does work as expected.

**Comment by trob** [comment]
I can't replicate.
Did you set ajaxfied=yes in the module? (I think there may be issues with filters and deletion if it's no, but display is working on my site even with NO)
What did you set as related menu?
Do you have a custom view link?

**Comment by EricdeWaal** [comment]
Ajaxified yes or no, in the module or the list or both, makes no difference. Details will never be shown.
The module is shown (as a test) on all pages.
I can send you a vieuw link, but prefer not to put it here (the site is a copy of a real live site containing personal data). Do you have an email address for the link, or can I make this ussue private somehow?

**Comment by trob** [comment]
> What did you set as related menu?  
If the related menu item is not public you'll get an error.

**Comment by skurvish** [comment]
Do you perhaps have a special group assigned to non registered users? Something other than Public? J4 made a change to how it handles ajax calls and if there is no itemID associated with the url doing the call J4 assumes it belongs to the default menu. if the default menu is assigned to a group other than Public, and this other group is not assigned also to registered, then you will get these access errors.

Just something to check and keep in mind.

**Comment by EricdeWaal** [comment]
I have an Access Level 'No Access' to which no user groups (and thus no users) have been assigned. 
I use that in Fabrik to deny access to some actions like "Empty records" even for superusers.
I did use that in this particular list, but setting all access levels back to Public does not make a differnce.
The rest is pretty much standard Joomla 3:
![afbeelding](https://user-images.githubusercontent.com/5586423/210826990-8197021a-f0ca-405c-b57d-0e94f6c99a2d.png)

**Comment by EricdeWaal** [comment]
And if I display the same list twice, via a menu and via the module on the same page, the first works and the second not. Ajaxified or not.

**Comment by trob** [comment]
I didn't mean the menu item you are calling but the one you selected in "Related menu item".
![grafik](https://user-images.githubusercontent.com/1045355/210831548-44d72655-bc08-4358-bd8e-1eb616ae93b2.png)

**Comment by EricdeWaal** [comment]
Ah sorry,I misunderstood. It appeared to be set to Home initially, should that be a menu-item that display the list, even if the module is on a different page?
Indeed it works now, but that has never been necessary in J3/F3 as far as I know.

**Comment by EricdeWaal** [comment]
I checked and in F3 it is not needed to set a "Related menu item" to that displays the same list, it works with any setting.
The F3 help mouseover for "Related menu item" says: "If the module's list already has a Joomla menu item created for it, then select this menu item to ensure that the modules links are the same as the menu items. This avoids duplicate SEF URLs pointing to the same content".

**Comment by trob** [comment]
In Fabrik3 you also get an error ("Please login"...) if you select a "Related menu item" where the user doesn't have access.

And it's working also in Fabrik4 with any "Related menu item" where the user has access.

**Comment by EricdeWaal** [comment]
To me it seems that the behavior is not exactly the same as in F3, but OK, as long as there is a Related menu item list with equal access rights as the module, it works so let's forget is. Closing the issue now.
