### ISSUE TITLE
List Module advanced settings 

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#609]
**Before reporting an issue please check that it has not already been fixed by reviewing the changelog in the Wiki or other open issues that may be pending confirmation. Thank you.**

**To Reproduce**
Create a list module
set 'show intro' in advanced settings to 'no'

**Expected behavior**
Intro not shown

**Actual behavior**
Intro shown

**Screenshots**

**Additional context**
#608  no issue on my side

**Comment by trob** [comment]
Will be fixed in the next version.
As a Workaround you can change 
modules\mod_fabrik_list\mod_fabrik_list.phpline 125 to

$listParams->set('show_into', $params->get('show_int**r**o', 1)); // (only!! in get(...) )

**Comment by wezetel** [comment]
Aha, an inconsistent typo :-) Thanks a lot
