### ISSUE TITLE
Upgrade: JCE editor must be reinstalled after upgrade to J4.x

### ISSUE THREAD

**Issue by gileschipper** [joomlahenk/fabrik#610]
**What happened**
Followed upgrade instructions from J3.10 to J4.2.6. All OK
Administrator back-end edit functions all failed with error after upgrade
THIS IS FOR INFORMATION ONLY - FIX IS TO REINSTALL JCE AFTER J4 UPGRADE

**To Reproduce**
All required upgrades and db fixes applied.
Attempt Fabrik Edit->Form/List in administrator back-end

**Expected behavior**
Edit Form/List as usual

**Actual behavior**
Error Unknown named parameter $params

**Error message**
Unknown named parameter $params

**Screenshots**

**Additional context**
JCE website showed many hits on this error. 
Reinstalled JCE from web and all working OK

**Comment by skurvish** [comment]
Did you have the latest JCE editor install on your J3 site prior to the upgrade? I have not run into this issue and have performed probably 50 upgrades.

Ensuring all of your components on your J3 site are current and compatible with J4 is a prerequisite to upgrading. I do have a couple that have different versions for each so have to disable or uninstall before the upgrade and then reinstall afterward. JCE is not one of them though.

**Comment by gileschipper** [comment]
I had applied all upgrades available before upgrading, and again after the upgrade, but JCE clearly does not notify of all upgrades available.
I have come across this same issue with JCE on other J3->J4 upgrades not involving Fabrik, so just wanted to save someone else the same chase around.
Keep up the great work - very pleased that Fabrik development is continuing, and happy to help with testing.

**Comment by skurvish** [comment]
Thanks for the info.
