### ISSUE TITLE
Upgrade: user_ajax.php session handler error

### ISSUE THREAD

**Issue by gileschipper** [joomlahenk/fabrik#611]
**What happened**
Testing the migration of custom Fabrik user_ajax.php and form_1.js to J4/Fabrik 4.
Changed mootools to JQuery ajax syntax in form_1.js., and all seems to work fine.
But - when joomla debug is on, the date includes warning as below.
I am aware of the warning in the upgrade instructions about debug settings breaking ajax, but this seems to be a specific error to do with session handling within the ajax framework. Config is set to default database handler
Am I missing a migration/setup step for J4? 
Seems to be very similar to this J4 bug: https://issues.joomla.org/tracker/joomla-cms/39341

**To Reproduce**
Set Setting Joomla Debug=on
Refresh Fabrik form, which calls custom ajax getClassDetails function
AJAX data is returned, but with appended session handler error
Setting Joomla Debug=off hides problem. 

**Expected behavior**
Console log reads:
response= AJAX php_getClassDetails: {"errors":"","warnings":"No Details found for Class :  "}

**Actual behavior**
Console log reads:
response= AJAX php_getClassDetails: {"errors":"","warnings":"No Details found for Class :  "}<br />
<b>Warning</b>:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) in <b>C:\Apache24\htdocs\doneasso\libraries\vendor\joomla\session\src\Storage\NativeStorage.php</b> on line <b>114</b><br />

**Error message**
14:24:35.864 form_1.js:649 response= AJAX php_getClassDetails: {"errors":"","warnings":"No Details found for Class :  "}<br />
<b>Warning</b>:  session_write_close(): Failed to write session data using user defined save handler. (session.save_path: ) in <b>C:\Apache24\htdocs\doneasso\libraries\vendor\joomla\session\src\Storage\NativeStorage.php</b> on line <b>114</b><br />

14:24:35.864 VM5372:1 Uncaught SyntaxError: Unexpected non-whitespace character after JSON at position 57
    at Function.parse [as parseJSON] (<anonymous>)
    at php_getClassDetails_response (form_1.js:650:36)
    at Object.<anonymous> (form_1.js:640:6)
    at fire (jquery.js?3.6.0:3500:31)
    at Object.fireWith [as resolveWith] (jquery.js?3.6.0:3630:7)
    at done (jquery.js?3.6.0:9796:14)
    at XMLHttpRequest.<anonymous> (jquery.js?3.6.0:10057:9)
php_getClassDetails_response @ form_1.js:650
(anonymous) @ form_1.js:640
fire @ jquery.js?3.6.0:3500
fireWith @ jquery.js?3.6.0:3630
done @ jquery.js?3.6.0:9796
(anonymous) @ jquery.js?3.6.0:10057
load (async)
send @ jquery.js?3.6.0:10076
ajax @ jquery.js?3.6.0:9690
(anonymous) @ form_1.js:620
execCb @ VM5263:29
check @ VM5263:18
enable @ VM5263:23
init @ VM5263:17
(anonymous) @ VM5263:26
setTimeout (async)
h.nextTick @ VM5263:32
g @ VM5263:26
requirejs @ VM5263:31
js_getClassDetails @ form_1.js:567
js_getRaceSeriesClasses_response @ form_1.js:553
(anonymous) @ form_1.js:455
fire @ jquery.js?3.6.0:3500
fireWith @ jquery.js?3.6.0:3630
done @ jquery.js?3.6.0:9796
(anonymous) @ jquery.js?3.6.0:10057
load (async)
send @ jquery.js?3.6.0:10076
ajax @ jquery.js?3.6.0:9690
(anonymous) @ form_1.js:437
execCb @ VM5263:29
check @ VM5263:18
enable @ VM5263:23
init @ VM5263:17
(anonymous) @ VM5263:26
setTimeout (async)
h.nextTick @ VM5263:32
g @ VM5263:26
requirejs @ VM5263:31
js_getRaceSeriesClasses @ form_1.js:397
js_getRaceSeries_response @ form_1.js:374
(anonymous) @ form_1.js:271
fire @ jquery.js?3.6.0:3500
fireWith @ jquery.js?3.6.0:3630
done @ jquery.js?3.6.0:9796
(anonymous) @ jquery.js?3.6.0:10057
load (async)
send @ jquery.js?3.6.0:10076
ajax @ jquery.js?3.6.0:9690
(anonymous) @ form_1.js:253
execCb @ VM5263:29
check @ VM5263:18
enable @ VM5263:23
init @ VM5263:17
(anonymous) @ VM5263:26
setTimeout (async)
h.nextTick @ VM5263:32
g @ VM5263:26
requirejs @ VM5263:31
js_getRaceSeries @ form_1.js:238
(anonymous) @ form_1.js:107
handleWindowTouchEnd_ @ unknown
14:24:35.899 jquery.js?3.6.0:10109 XHR finished loading: POST "http://localhost/doneasso/index.php/en/index.php?option=com_fabrik&format=raw&task=plugin.userAjax&method=php_getClassDetails".

**Screenshots**

**Additional context**
Localhost testing on Joomla 4.2.6, fabrik_4.0beta4b, Windows 10, Apache2.4, PHP8.1
Joomla debug on, session_handler=database

**Comment by trob** [comment]
I've seens Session handler errors (I can't remember if exactly this one) and JS error "Uncaught SyntaxError: Unexpected non-whitespace character after JSON " also, 
but not related to a F3 upgrade and not related to custom Ajax.

With J! System Debug off it's ok, so keep it in mind, but low prio.

**Comment by gileschipper** [comment]
I have tested that this error does not occur with the same system in F3/J3, but agree not a high priority. Thanks for response.
I am accumulating a list of migration tips for this area of Fabrik. When it is appropriate I am happy to help add to the migration documentation.

**Comment by trob** [comment]
I meant I've seen these errors in J!4 /F4 without upgrading from J!3, so no exclusive upgrade issue.

Looking at your link https://issues.joomla.org/tracker/joomla-cms/39341 it seems to be a Joomla issue.
Did you try to switch this "tracking request history" they mention? I assume it's the one in System-Debug plugin settings. (I don't have a replicatable setup for testing).

![image](https://user-images.githubusercontent.com/1045355/211623141-bbfe2204-39d4-4d3a-b617-80f045498032.png)

**Comment by gileschipper** [comment]
Thanks. I have tried that and it produces entirely dfferent warnings:
 PHP Warning:  file_get_contents(C:\Apache24\htdocs\doneasso\administrator\cache/plg_system_debug_site\X293e945344b00131b68ea6c000f981b6.php): Failed to open stream: No such file or directory in C:\Apache24\htdocs\doneasso\plugins\system\debug\src\Storage\FileStorage.php on line 61
Agree that this is a Joomla issue. I'll keep testing with debug off.

**Comment by skurvish** [comment]
using debug in any form under Joomla will break most ajax calls as Joomla just emits way to may deprecation warnings, Ajax calls almost always expect a json_encoded response and the text warnings break that. Also, J4 hs many more and many different warnings that found with J3 so you can't really compare the two.

If you really need J! debug enabled for other reasons then disable them in the ajax code with error_reporting and ini_set calls at the top of the php file.

**Comment by skurvish** [comment]
Closing as not a Fabrik issue.
