### ISSUE TITLE
Form->Email plugin - error on EmailTo eval using placeholder

### ISSUE THREAD

**Issue by gileschipper** [joomlahenk/fabrik#612]
Form has email plugin to send on submission. Send is to email field on form. Send fails with error 
![email_eval](https://user-images.githubusercontent.com/122117277/212717599-c75d2d32-ac94-48ae-b983-959adfa5fd6d.PNG)

Eval for EmailTo is as below:
use Joomla\CMS\Factory;
$name = '{ltsc_entries___EmailAddress}';
// logic to allow for debug addresses....
return $name;

Error is on screenshot:
An error has occurred with a eval'd field - please inform the web-site owner.    Debug: Caught exception on eval in email emailto : Joomla\CMS\Factory::getLanguage() is deprecated. Load the language from the dependency injection container or via Joomla\CMS\Factory::getApplication()->getLanguage().

**Comment by trob** [comment]
>  Bug report
> Don't post here. From now on post issue's on https://fabrikar.com/forums/index.php?forums/bugs-issues-suggestions.107/

**Comment by gileschipper** [comment]
Sorry. Reposted in forums, closed here
