### ISSUE TITLE
0 Class "FabrikWorker" not found

### ISSUE THREAD

**Issue by kdhoe1** [joomlahenk/fabrik#614]
Latest joomla version (fresh install) 4.2.9
php 8.2.4
mysql 8.0.32

beta 4 fabrik

error 0 Class "FabrikWorker" not found

any suggestions?

regards

**Comment by trob** [comment]
>  Bug report
> Don't post here. From now on post issue's on https://fabrikar.com/forums/index.php?forums/bugs-issues-suggestions.107/


https://fabrikar.com/forums/index.php?threads/fabrik-4-gamma2-now-available-for-download.53699/
