### ISSUE TITLE
Revert merge of PR #59

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#62]
This should not have been merged. The code was correct as written. This change will cause the wrong form to be loaded.

**Comment by trob** [comment]
hmm, this is inside the validation handling and with getJForm is't breaking, getForm is working.

**Comment by skurvish** [comment]
The reason getJform is not working is because the getJFom function inside components/com_fabrik/models/plugins.php was renamed to getForm but it needs to be getJForm. The wrong form will be loaded using getForm. This was a problem I fixed a while ago but somehow got reverted.

@trob can you change the function name in this file and change the call back and see if it is working for you? If so please PR that change.

**Comment by joomlahenk** [comment]
I was too fast this time. I will undo this change and merge

**Comment by trob** [comment]
Seem to be ok if I change it to getJForm in element.php, change the function name in plugins.php AND change the call line 282 in plugin.php also to getJForm
$form    = self::getJForm();	// We must call our getForm function, $this points to the element not this plugin.

**Comment by skurvish** [comment]
That is correct. the call to getJForm gets the plugin form which is what we want, not the element form.

**Comment by trob** [comment]
ok, I created a "revert" PR. plugin.php is already fixed by @joomlahenk in https://github.com/joomlahenk/fabrik/commit/e91dde003aac41d5bef780f64a48050aa39dabb9
