### ISSUE TITLE
commit First cut at fixing the filter options

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#64]
https://github.com/joomlahenk/fabrik/commit/f49843085c8bb77fafb71d99a7e34af09c5220c4#diff-752197e9d65d3a7127fe5b272a9b5f8de15ecca767791227f3dbff63c5dc10c1

Compile Error: Cannot use Joomla\CMS\Language\Text as Text because the name is already in use

administrator\components\com_fabrik\views\elements\view.html.php:23  

ok, if use... is removed

**Comment by joomlahenk** [comment]
Solution already merged
