### ISSUE TITLE
Tooltips not working as they should

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#66]
trob: Any idea how we get the tooltips back?

J!4 displays (some of) the old tooltips below the input fields (see e.g. breadcrumb module) but this is no solution for Fabrik's heavy "Help tooltips" in the backend forms.

Also the element validation and tips tooltips are missing.

JS is not my field ;)

**Comment by skurvish** [comment]
Tootips are a bootstrap thing and they changed a lot with bootstrap 5. I have some experience with them so will dive in once I fix the menu options issue.

**Comment by trob** [comment]
I'm on changing the layouts to bootstrap5
Tooltips (frontend form) are working meanwhile, also list buttons (Group by, CSV) and pagination.
I will do a PR as soon as I've cleaned up.

Question: is there a central place where we are initialasing the bootrap parts? It needs to load something like
HTMLHelper::_('bootstrap.tooltip','.FabrikTooltip');

**Comment by skurvish** [comment]
You can add this to both of these in the framework function:

components/com_fabrik/fabrik/fabrik/Helpers/Html.php
libraries/fabrik/fabrik/Helpers/Html.php

**Comment by joomlahenk** [comment]
HTMLHelper::_('bootstrap.tooltip'); is in every admin/views/.../tmpl/bootstrap.php
Same as in J!3
do we need to add .FabrikTooltip ?

**Comment by joomlahenk** [comment]
Once again: Ignore components/com_fabrik/fabrik/fabrik/Helpers/Html.php !
This is only used to copy libraries and is never used. We still need to get rid of it.

**Comment by trob** [comment]
Toggle and placement are clear.
The problem is the trigger. It seems to be a Joomla bootstrap issue (or some parameter more to set).
No matter which data-bs-trigger="xy" is used, it's always only triggered by click (which is the standard for popover).
Even the example copied directly from BS5, which is working there on hover is only reacting on click.

So I think if we want to have the old "hover" behaviour we have to use tooltips.

**Comment by skurvish** [comment]
Aha! The tooltips have to be activated.Check out my migration document here: http://skurvishenterprises.com/index.php/documents/migrating-extensions-to-joomla-4

**Comment by trob** [comment]
Yes, it's HTMLHelper::_('bootstrap.tooltip',' [data-bs-toggle]="tooltip"')  
A selector is also needed for popover, e.g. HTMLHelper::_('bootstrap.tooltip',' [data-bs-toggle]="popover"') 

The difference between tooltip and popover is mainly the trigger - hover or click (beside a bit different title/content attributes)
