### ISSUE TITLE
Keep FText as wrapper for Text

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#68]
There may be a lot of custom code using it

**Comment by skurvish** [comment]
That can be said of a lot of the classes. I think that given this is a break from J3 and users are going to have to go through some update process anyway, they should revise their code to the newer classnames. This should be part of the pre upgrade preperations.

**Comment by joomlahenk** [comment]
We can make an alias if needed. A lot of the old classes still work in J!4: see the classmap
