### ISSUE TITLE
Fabrik list menu: Fabrik Options missing

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#71]
You can link a list and it's working, but no content in Fabrik Options is shown.

Form list menu is looking good (I didn't test)

**Comment by skurvish** [comment]
I see the issue. I will take it.

**Comment by skurvish** [comment]
I have the form options working except the modal popups for the list elements and pre-filters. These are commented out for the moment so I can check these changes in and you can at least set up a proper fabrik list menu item. I will continue to work on the modals.

**Comment by skurvish** [comment]
I think issue #77 is related. When I get the modal popups sorted out maybe 77 will be fixed as well.

**Comment by skurvish** [comment]
I have finally figured out what the problem was with this and it looks to be a bug in the J! code. I have opened a ticket on the Joomla Issue Tracker.

**Comment by joomlahenk** [comment]
However: Issue #77 is now working

**Comment by trob** [comment]
Just found: since https://github.com/joomlahenk/fabrik/pull/87 you can't add new Fabrik menue or edit existing ones - it won't append the list/form/viz id to the url
It is working if reset to one commit before.

**Comment by skurvish** [comment]
It is working for me. Non sef mode though, haven't tried sef.

**Comment by trob** [comment]
It's working without SEF, yes, but no idea why. Because the list id is missing in the URL because it is not added in the menu item.
Until https://github.com/joomlahenk/fabrik/pull/87 it was added (only after saving the menu, it won't show on list select, but this is the same behaviour as in J!3)
Ususally the menu "Link" looks (after save) like
index.php?option=com_fabrik&view=list&listid=4
(and in this case SEF is working, too)
now it's only 
index.php?option=com_fabrik&view=list
for all lists

**Comment by trob** [comment]
see https://github.com/joomlahenk/fabrik/pull/141

**Comment by skurvish** [comment]
I am getting no response from the J! team on my issue. The problem area is the filters and the list elements, and they are a problem because of how they are configured in the menu xml file. I have a few other ideas I want to try, but if they do not pan out then we simply do not do these as modals, and simply list the rows on the menu configuration screen. If we think this will be too cumbersome on the main Fabrik list options tab, I can add an additional tab just for these 2 items.

**Comment by skurvish** [comment]
OK, I have 2 ways to solve this problem. The first is to eliminate the modal popup and just have the repeatable fields display along with all the other fields in the menu. I can put these on a separate tab but for now I have them on the Fabrik List Options tab.

Alternative, I can create a layout override which inserts my code change to handle the modal popups. If I do this then it will look just like it always looked. This is a standard layout override so would not get us into trouble with J!. I like this option over the other as it unclutters the options list and users will see the same interface they always have.

Any preference?

**Comment by skurvish** [comment]
I have the override working. A fundamental question though is that should fabrik install the layout override during the install and update processes? The install would have to query what template is running for the admin and then install it there. Admin templates rarely change if ever so I suppose it is possible to just assume the Atum template? What if the template changes at some point, the Fabrik system should detect that and copy the override.

I was hoping there was a way to use a layout override that can be installed somewhere we control but I can't see any. I was also hoping there was a way to add a layout override path to the search process but I didn't find a way to do that either.

Open to any suggestions.

**Comment by trob** [comment]
I added a layout override here
https://github.com/joomlahenk/fabrik/pull/88/files
Maybe it's also possible for your file

**Comment by skurvish** [comment]
Unfortunately no. The override you added works when Fabrik is the component that is running, but in this case it is com_menus that is running so we have a choice of override in layouts/joomla or layout/com_menus. For me com_menus is slightly less intrusive than directly of joomla.

**Comment by skurvish** [comment]
I have submitted PR #155 to fix this issue. There is now a template override in administrator/components/com_fabrik/layouts/joomla/edit/params.php

The manifest install script will copy this override to the current admin template override location. The code checks that it is not overwriting someone elses override.

I have not tested the actual install yet as I need to fix the grunt build.

In the mean time, if you wish to use this, copy the params.php override file to administrator/templates/atum/html/layouts/joomla/edit directory.

**Comment by skurvish** [comment]
Install works fine. Closing this.
