### ISSUE TITLE
Auto version on script files is not working

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#76]
The HTMLHelper script loader is not working with the auto version arguments in the call. The script does not get loaded. I had to remove these arguments to get the scripts to load. I have not pushed the changes yet as one of you may have an idea why this is happening.

**Comment by joomlahenk** [comment]
As usual, I could not find a clear documentation on what version is doing I left it on auto. I would add detectDebug anyway.
If it now works as we want and you tested it, please check in and I will merge.

**Comment by skurvish** [comment]
Check in as part of my other PR. Closing this.
