### ISSUE TITLE
List (edit) Elements table select does not close

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#77]
On the list page -> details -> tab filters -> select elements Select. A table is display with + button, rows and close button.
On close the table closes but opens splitst-up on different positions, but remains inactive covering other field.
I have been struggling with this issue for some time. At the end it looks like a JS issue, but nothing was changed in JS.

Any tips ??

**Comment by trob** [comment]
I think there are a lot of JS issues... (see also https://github.com/joomlahenk/fabrik/issues/73)
The console doesn't show any error, so no tip at the moment.
At least the selected elements are saved correctly and search all is working.

**Comment by joomlahenk** [comment]
I will try to do this with the Joomla modal. Then we don't use any fabrik JS. Maybe we can do this with more fields.

**Comment by joomlahenk** [comment]
Too bad, also for the Joomla modal we end-up in JS.
The fieldtype is also used for the module and frontend and I am not able to test those yet, so I need to pause this issue to be solved later.

**Comment by joomlahenk** [comment]
Not fixed ! I installed fabrik4 and I have params.php in admin/templates/atum/html/layouts/joomla/edit, but the modal does not close like before.

**Comment by joomlahenk** [comment]
Fixed by adding minified mootools-ext.js to media/com_fabrik/js/dist
