### ISSUE TITLE
List plugins / form plugins / element validation plugins in admin-forms are not loaded

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#78]
It stopped working with this commit
https://github.com/joomlahenk/fabrik/commit/f49843085c8bb77fafb71d99a7e34af09c5220c4

**Comment by skurvish** [comment]
I will take a look.

**Comment by skurvish** [comment]
Fixed element validation and javascript with pr #82 working on list & form.

**Comment by skurvish** [comment]
Please Select issue resolved.

@trob please test and close this issue if now working properly.

**Comment by skurvish** [comment]
There is a problem loading the form data for the email form plugin. I have been chasing it for a couple of hours now but have not sorted it. Will get back to it later. I am away a good part of tomorrow so don't know how much time I can invest in this part.
