### ISSUE TITLE
Get frontend "working"

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#9]
The frontend needs to updated to cassiopeia, but without that we should at least see some output.

But I get following errors:

Created a list menu item => ok
Select in frontend => error router SOLUTION: Set SEO off
=> ok working, but then we get:

Cannot access protected property Joomla\CMS\Menu\MenuItem::$params in site/fabrik/fabrik/Helpers/Worker.php:2550
SOLUTION: in site/fabrik/fabrik/Helpers/Worker.php:2550
change $val = $menu->params->get($name, $val); into $val = $menu->getParams($name, $val);
=> ok working, but then we get:

Call to undefined method FabrikControllerList::getError()
Does not exist indeed -> try to comment-out or change to null 
SOLUTION: Remove all $view->error = $this->getError();
=> get another issue:

ISSUE: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class Joomla\CMS\Cache\Cache does not have a method "call"

**Comment by trob** [comment]
It's $menu->getParams**->get**($name, $val); (worker.php line 2550 and 2581, but also in model/list.php etc)

The cache call stuff is also in my PR (change call to get)
https://github.com/joomlahenk/fabrik/pull/6/commits/1627eba83e9d88f952a978ac698880c45f0760bb

I'll try to create a "mergeable" PR tomorrow (it's 23:07 at my place)

**Comment by joomlahenk** [comment]
OK, continue:

ISSUE: call_user_func_array(): Argument https://github.com/joomlahenk/fabrik/pull/1 ($callback) must be a valid callback, class Joomla\CMS\Cache\Cache does not have a method "call"
JCacheController::get now requires a callable. As a result JCacheControllerCallback::call has been removed.
SOLUTION: Replace $cache->call by $cache->get
Used in:
site\models\element.php
site\models\list.php
plg_fabrik_system\fabrik.php

=> ok working, but then we get

ISSUE: Failed opening required '/var/www/html/j4fabrik/includes/application.php' (include_path='.:/usr/share/php')
in site/views/list/view.base.php:487

**Comment by joomlahenk** [comment]
OK merged pull requests and copied from GitHub => working frontend and no more warnings/ notice.
Now I don't know what caused these warnings, but ok.

We can continue styling the frontend for cassiopeia.
