### ISSUE TITLE
off topic to @skurvish

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#90]
your website is showing
![image](https://user-images.githubusercontent.com/1045355/178989253-df753a3a-bfa0-4d8e-92d9-e7f55a14deea.png)
on /products

**Comment by skurvish** [comment]
Again? Thanks. I fixed this quite some time ago.

**Comment by skurvish** [comment]
Argg.. the developer of RD Subscriptions uses an order code value that it derives from the 2 digit year followed by 8 zeros, then increments by 1 for each time someone comes to the site. Unfortunately he decided the column type should be int which has a maximum value of 2147483647, so when we flipped over to 2022 and tried to save the ordercode the first time it was fine and saved it as 2147483647, but, then next time anyone came to the site it tried to store the same number again. You saw the error.

Also unfortunately this software was abandoned by the developer. It was taken up by another developer and mostly rewritten but he wants way too much money for it.

Anyway, altering the column type to BIGINT has solved the problem. Thanks for pointing it out. I have no idea how many people came to the site, got this error, and I never heard from them.

Sigh... I am going to close this.
