### ISSUE TITLE
Frontend only working with SEO off

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#96]

**Comment by skurvish** [comment]
Yes, I saw this before as well.

**Comment by trob** [comment]
I skipped one error here https://github.com/joomlahenk/fabrik/pull/137 but this has to be resolved.

**Comment by trob** [comment]
SEF is working with https://github.com/joomlahenk/fabrik/pull/140 but I don't know at the moment how to replace 
if ($router->getMode() === (int) JROUTER_MODE_SEF)
for this hack https://github.com/joomlahenk/fabrik/pull/137 (affecting content plugin etc)

**Comment by trob** [comment]
solved with https://github.com/joomlahenk/fabrik/pull/148
