### ISSUE TITLE
Unable to find html setting

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#99]
I struggling to find the htnl code for following fields:
Lists -> New (Edit) -> data -> tab data order by => class is now inputbox but must be form-select, unable to find where this can be set.
Forms -> New (Edit) -> tab form processing -> table name => no fabrik type, class must be form-control, unable to find where this can be set.

It must be somewhere deeply burried in the source od maybe I need to add some html, but where?
Any idea's?

**Comment by trob** [comment]
Maybe
administrator\components\com_fabrik\models\forms\list.xml
and/or
administrator\components\com_fabrik\models\fields\ascendingdescending.php
etc.

**Comment by joomlahenk** [comment]
Nope, tried that already

**Comment by joomlahenk** [comment]
Most logic is in admin/views/list/view.html.php:106
I changed this to $attribs  = 'class="form-select" ';, but has no effect.

**Comment by trob** [comment]
Try
line 91ff
`foreach ($orderBys as $orderBy)
			{
				$this->order_by[] = $formModel->getElementList('order_by[]', $orderBy, true, false, false, 'id','class="form-select" ');
			}

			if (empty($this->order_by))
			{
				$this->order_by[] = $formModel->getElementList('order_by[]', '', true, false, false, 'id','class="form-select" ');`

**Comment by joomlahenk** [comment]
Thanks, this is working in list. Now the one in form.

**Comment by joomlahenk** [comment]
Updated admin/views/form/tmpl/bootstrap_process.php
